## Notebook 3 – 2006 Data Preparation

### Objective

This notebook prepares the 2006 Toronto Neighbourhood Profile dataset for predictive modelling.

The objectives are to:

- Load the raw 2006 neighbourhood profile dataset.
- Transpose the data so that neighbourhoods become observations.
- Select socioeconomic indicators that match the 2016 ML-ready dataset.
- Clean and standardize variable names.
- Handle missing values and data quality issues.
- Export the final machine learning dataset for predictive modelling.

The resulting dataset will be used as the predictor dataset in subsequent modelling notebooks.

### Section 1- Import Libs

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

### Section 2- Load Dataset

In [7]:
df_raw = pd.read_csv("../../data/raw/neighbourhood-profiles-2006-140-model.csv")

print(df_raw.shape)

df_raw.head()

(1455, 145)

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
0,1,Population,Population,"Population, 2001 - 100% data",2481494.00,28814.00,21770.00,12118.00,26689.00,23014.00,13412.00,14054.00,12404.00,13538.00,21465.00,7231.00,22964.00,22657.00,24360.00,8129.00,13833.00,8258.0,12465.00,17182.00,10577.0,10993.00,9395.00,12638.00,21854.00,19987.00,13451.00,15015.00,15753.00,10065.00,17373.00,26974.00,22307.00,36837.00,34249.00,12693.00,20275.00,14498.00,22728.00,9750.00,20062.0,18677.00,10743.00,22670.00,12288.0,11828.00,33692.0,15957.00,10277.00,11701.00,21198.00,20127.0,12848.00,18414.00,9899.00,12523.00,14706.00,14719.00,13531.00,31431.00,12153.00,11128.0,17681.00,17093.00,22634.00,8166.00,7903.00,45605.00,11743.00,13931.00,14667.00,15521.00,13517.0,10382.00,44030.00,10135.0,10145.00,26827.00,24200.00,17935.0,13088.00,12972.00,33777.00,15200.0,22836.00,11284.00,15420.00,20509.00,11219.00,12469.00,18566.00,13743.00,23324.00,19124.00,9137.0,14742.00,35823.00,8264.0,7796.00,16997.00,10898.00,11281.00,10745.00,23372.00,16012.00,19133.00,28719.00,9803.00,9988.00,17029.00,22844.00,26885.00,17368.00,24429.00,23874.00,26469.00,16207.00,19974.00,10384.0,16681.00,17424.00,5769.00,16717.00,18526.00,26707.00,32586.00,24586.00,17465.00,11677.00,27541.00,26996.00,11402.00,21926.00,51011.0,12059.0,8677.00,14767.00,10316.00,10770.00,26448.00,13817.00
1,2,Population,Population,"Population, 2006 - 100% data",2503281.00,30156.00,21562.00,11656.00,27482.00,25439.00,14945.00,15325.00,15376.00,13298.00,21961.00,6526.00,25479.00,21652.00,21720.00,7765.00,14198.00,8205.0,11596.00,17318.00,11120.0,10281.00,9815.00,12450.00,24379.00,19850.00,13732.00,14531.00,14405.00,9576.00,16500.00,26644.00,24374.00,34737.00,32010.00,11811.00,20096.00,14453.00,22387.00,9437.00,21115.0,18533.00,10675.00,21287.00,12294.0,10842.00,30886.0,14705.00,10026.00,11288.00,20969.00,19984.0,12853.00,18327.00,10531.00,12766.00,14778.00,13925.00,13025.00,32823.00,13168.00,11231.0,17034.00,17102.00,21400.00,8780.00,7780.00,45862.00,14436.00,13749.00,14827.00,15988.00,12116.0,9625.00,44324.00,10271.0,10240.00,26272.00,24973.00,17202.0,15481.00,12835.00,32127.00,15210.0,23728.00,10652.00,15557.00,20489.00,14563.00,12428.00,17114.00,13368.00,21443.00,17740.00,9019.0,13777.00,33821.00,8729.0,7688.00,16615.00,10965.00,10387.00,10725.00,22389.00,14655.00,20600.00,43191.00,9557.00,10042.00,15590.00,21013.00,24424.00,17564.00,24696.00,23809.00,27235.00,15211.00,20416.00,9928.0,17949.00,16604.00,5906.00,17047.00,26015.00,25632.00,32252.00,24403.00,16476.00,12098.00,26644.00,41054.00,12517.00,20907.00,52461.0,11550.0,8051.00,14194.00,10497.00,11235.00,26140.00,14830.00
2,3,Population,Population,"Population percentage change, 2001 to 2006",0.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Population,Land Area,"Land area in square kilometres, 2006",630.18,7.41,7.85,4.94,2.81,9.99,4.69,1.83,5.11,4.07,5.48,1.82,7.45,5.93,3.48,0.95,1.84,8.9,1.68,3.51,1.4,1.55,1.93,5.39,1.35,7.41,4.14,7.01,1.89,1.12,2.18,4.19,6.01,3.73,15.11,1.38,2.65,5.45,3.23,2.86,3.5,8.53,1.76,2.43,1.6,2.47,5.2,1.68,3.71,2.62,1.89,4.9,5.13,5.35,2.73,7.89,4.35,1.86,1.94,16.28,2.65,1.7,3.58,1.52,5.04,2.58,1.71,7.15,5.35,2.27,3.24,4.68,1.2,2.22,8.86,2.5,2.92,7.19,6.82,5.7,1.41,2.11,4.52,3.1,1.35,3.39,4.08,4.69,2.95,1.76,0.42,1.86,2.22,4.94,2.3,1.44,7.39,4.2,0.92,3.04,5.18,0.64,2.49,5.03,1.52,4.64,37.05,1.59,2.09,3.09,1.36,8.89,7.29,4.52,7.85,5.44,1.01,3.57,3.3,3.09,1.73,0.64,4.72,7.35,9.58,29.95,3.62,2.51,1.47,10.25,5.05,2.91,5.52,12.3,1.6,1.17,1.67,1.65,1.16,13.21,5.97
4,5,Population,Age characteristics,Total - Age,2503285.00,30150.00,21560.00,11655.00,27480.00,25445.00,14940.00,15325.00,15375.00,13295.00,21965.00,6525.00,25480.00,21660.00,21720.00,7765.00,14195.00,8210.0,11590.00,17320.00,11120.0,10280.00,9815.00,12450.00,24370.00,19850.00,13735.00,14530.00,14400.00,9575.00,16500.00,26650.00,24375.00,34740.00,32005.00,11810.00,20095.00,14455.00,22385.00,9435.00,21110.0,18530.00,10675.00,21285.00,12290.0,10840.00,30885.0,14705.00,10030.00,11285.00,20965.00,19985.0,12855.00,18330.00,10530.00,12760.00,14775.00,13925.00,13025.00,32820.00,13175.00,11235.0,17035.00,17100.00,21405.00,8775.00,7785.00,45860.00,14440.00,13750.00,14825.00,15990.00,12115.0,9625.00,44325.00,10270.0,10240.00,26270.00,24970.00,17205.0,15475.00,12840.00,32120.00,15215.0,23730.00,10650.00,15560.00,20485.00,14555.00,12425.00,17115.00,13365.00,21435.00,17755.00,9025.0,13770.00,33825.00,8735.0,7690.00,16605.00,10960.00,10390.00,10720.00,22390.00,14655.00,20600.00,43190.00,9560.00,10040.00,15590.00,21015.00,24415.00,17560.00,24705.00,23805.00,27235.00,15210.00,20415.00,9930.0,17945.00,16605.00,5900.00,17050.00,26020.00,25640.00,32255.00,24400.00,16475.00,12095.00,26640.00,41045.00,12515.00,20905.00,52455.0,11550.0,8050.00,14195.00,10500.00,11235.00,26145.00,14830.00

## Section 3 – Initial Data Inspection

The purpose of this section is to inspect the raw 2006 Toronto Neighbourhood Profile dataset, understand its structure, verify dimensions, identify missing values, and examine the attributes available for feature selection.

In [24]:
print(df_raw.shape)

df_raw.info()

df_raw.head()

(1455, 145)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1455 entries, 0 to 1454
Columns: 145 entries, _id to Yorkdale-Glen Park
dtypes: float64(141), int64(1), object(3)
memory usage: 1.6+ MB

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
0,1,Population,Population,"Population, 2001 - 100% data",2481494.00,28814.00,21770.00,12118.00,26689.00,23014.00,13412.00,14054.00,12404.00,13538.00,21465.00,7231.00,22964.00,22657.00,24360.00,8129.00,13833.00,8258.0,12465.00,17182.00,10577.0,10993.00,9395.00,12638.00,21854.00,19987.00,13451.00,15015.00,15753.00,10065.00,17373.00,26974.00,22307.00,36837.00,34249.00,12693.00,20275.00,14498.00,22728.00,9750.00,20062.0,18677.00,10743.00,22670.00,12288.0,11828.00,33692.0,15957.00,10277.00,11701.00,21198.00,20127.0,12848.00,18414.00,9899.00,12523.00,14706.00,14719.00,13531.00,31431.00,12153.00,11128.0,17681.00,17093.00,22634.00,8166.00,7903.00,45605.00,11743.00,13931.00,14667.00,15521.00,13517.0,10382.00,44030.00,10135.0,10145.00,26827.00,24200.00,17935.0,13088.00,12972.00,33777.00,15200.0,22836.00,11284.00,15420.00,20509.00,11219.00,12469.00,18566.00,13743.00,23324.00,19124.00,9137.0,14742.00,35823.00,8264.0,7796.00,16997.00,10898.00,11281.00,10745.00,23372.00,16012.00,19133.00,28719.00,9803.00,9988.00,17029.00,22844.00,26885.00,17368.00,24429.00,23874.00,26469.00,16207.00,19974.00,10384.0,16681.00,17424.00,5769.00,16717.00,18526.00,26707.00,32586.00,24586.00,17465.00,11677.00,27541.00,26996.00,11402.00,21926.00,51011.0,12059.0,8677.00,14767.00,10316.00,10770.00,26448.00,13817.00
1,2,Population,Population,"Population, 2006 - 100% data",2503281.00,30156.00,21562.00,11656.00,27482.00,25439.00,14945.00,15325.00,15376.00,13298.00,21961.00,6526.00,25479.00,21652.00,21720.00,7765.00,14198.00,8205.0,11596.00,17318.00,11120.0,10281.00,9815.00,12450.00,24379.00,19850.00,13732.00,14531.00,14405.00,9576.00,16500.00,26644.00,24374.00,34737.00,32010.00,11811.00,20096.00,14453.00,22387.00,9437.00,21115.0,18533.00,10675.00,21287.00,12294.0,10842.00,30886.0,14705.00,10026.00,11288.00,20969.00,19984.0,12853.00,18327.00,10531.00,12766.00,14778.00,13925.00,13025.00,32823.00,13168.00,11231.0,17034.00,17102.00,21400.00,8780.00,7780.00,45862.00,14436.00,13749.00,14827.00,15988.00,12116.0,9625.00,44324.00,10271.0,10240.00,26272.00,24973.00,17202.0,15481.00,12835.00,32127.00,15210.0,23728.00,10652.00,15557.00,20489.00,14563.00,12428.00,17114.00,13368.00,21443.00,17740.00,9019.0,13777.00,33821.00,8729.0,7688.00,16615.00,10965.00,10387.00,10725.00,22389.00,14655.00,20600.00,43191.00,9557.00,10042.00,15590.00,21013.00,24424.00,17564.00,24696.00,23809.00,27235.00,15211.00,20416.00,9928.0,17949.00,16604.00,5906.00,17047.00,26015.00,25632.00,32252.00,24403.00,16476.00,12098.00,26644.00,41054.00,12517.00,20907.00,52461.0,11550.0,8051.00,14194.00,10497.00,11235.00,26140.00,14830.00
2,3,Population,Population,"Population percentage change, 2001 to 2006",0.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Population,Land Area,"Land area in square kilometres, 2006",630.18,7.41,7.85,4.94,2.81,9.99,4.69,1.83,5.11,4.07,5.48,1.82,7.45,5.93,3.48,0.95,1.84,8.9,1.68,3.51,1.4,1.55,1.93,5.39,1.35,7.41,4.14,7.01,1.89,1.12,2.18,4.19,6.01,3.73,15.11,1.38,2.65,5.45,3.23,2.86,3.5,8.53,1.76,2.43,1.6,2.47,5.2,1.68,3.71,2.62,1.89,4.9,5.13,5.35,2.73,7.89,4.35,1.86,1.94,16.28,2.65,1.7,3.58,1.52,5.04,2.58,1.71,7.15,5.35,2.27,3.24,4.68,1.2,2.22,8.86,2.5,2.92,7.19,6.82,5.7,1.41,2.11,4.52,3.1,1.35,3.39,4.08,4.69,2.95,1.76,0.42,1.86,2.22,4.94,2.3,1.44,7.39,4.2,0.92,3.04,5.18,0.64,2.49,5.03,1.52,4.64,37.05,1.59,2.09,3.09,1.36,8.89,7.29,4.52,7.85,5.44,1.01,3.57,3.3,3.09,1.73,0.64,4.72,7.35,9.58,29.95,3.62,2.51,1.47,10.25,5.05,2.91,5.52,12.3,1.6,1.17,1.67,1.65,1.16,13.21,5.97
4,5,Population,Age characteristics,Total - Age,2503285.00,30150.00,21560.00,11655.00,27480.00,25445.00,14940.00,15325.00,15375.00,13295.00,21965.00,6525.00,25480.00,21660.00,21720.00,7765.00,14195.00,8210.0,11590.00,17320.00,11120.0,10280.00,9815.00,12450.00,24370.00,19850.00,13735.00,14530.00,14400.00,9575.00,16500.00,26650.00,24375.00,34740.00,32005.00,11810.00,20095.00,14455.00,22385.00,9435.00,21110.0,18530.00,10675.00,21285.00,12290.0,10840.00,30885.0,14705.00,10030.00,11285.00,20965.00,19985.0,12855.00,18330.00,10530.00,12760.00,14775.00,13925.00,13025.00,32820.00,13175.00,11235.0,17035.00,17100.00,21405.00,8775.00,7785.00,45860.00,14440.00,13750.00,14825.00,15990.00,12115.0,9625.00,44325.00,10270.0,10240.00,26270.00,24970.00,17205.0,15475.00,12840.00,32120.00,15215.0,23730.00,10650.00,15560.00,20485.00,14555.00,12425.00,17115.00,13365.00,21435.00,17755.00,9025.0,13770.00,33825.00,8735.0,7690.00,16605.00,10960.00,10390.00,10720.00,22390.00,14655.00,20600.00,43190.00,9560.00,10040.00,15590.00,21015.00,24415.00,17560.00,24705.00,23805.00,27235.00,15210.00,20415.00,9930.0,17945.00,16605.00,5900.00,17050.00,26020.00,25640.00,32255.00,24400.00,16475.00,12095.00,26640.00,41045.00,12515.00,20905.00,52455.0,11550.0,8050.00,14195.00,10500.00,11235.00,26145.00,14830.00

In [25]:
df_raw.columns

Index(['_id', 'Category', 'Topic', 'Attribute', 'City of Toronto',
       'Agincourt North', 'Agincourt South-Malvern West', 'Alderwood', 'Annex',
       'Banbury-Don Mills',
       ...
       'Willowdale West', 'Willowridge-Martingrove-Richview', 'Woburn',
       'Woodbine Corridor', 'Woodbine-Lumsden', 'Wychwood', 'Yonge-Eglinton',
       'Yonge-St.Clair', 'York University Heights', 'Yorkdale-Glen Park'],
      dtype='object', length=145)

In [26]:
df_raw[["Category","Topic","Attribute"]].head(20)

,Category,Topic,Attribute
0,Population,Population,"Population, 2001 - 100% data"
1,Population,Population,"Population, 2006 - 100% data"
2,Population,Population,"Population percentage change, 2001 to 2006"
3,Population,Land Area,"Land area in square kilometres, 2006"
4,Population,Age characteristics,Total - Age
5,Population,Age characteristics,0 to 4 years
6,Population,Age characteristics,5 to 9 years
7,Population,Age characteristics,10 to 14 years
8,Population,Age characteristics,15 to 19 years
9,Population,Age characteristics,20 to 24 years
10,Population,Age characteristics,25 to 29 years
11,Population,Age characteristics,30 to 34 years
12,Population,Age characteristics,35 to 39 years
13,Population,Age characteristics,40 to 44 years
14,Population,Age characteristics,45 to 49 years
15,Population,Age characteristics,50 to 54 years
16,Population,Age characteristics,55 to 59 years
17,Population,Age characteristics,60 to 64 years
18,Population,Age characteristics,65 to 69 years
19,Population,Age characteristics,70 to 74 years

### Section 4 – Identify Candidate Variables

This section searches the dataset to locate socioeconomic indicators that will later be extracted into the modelling dataset.

In [28]:
df_raw[df_raw["Attribute"].str.contains("after-tax", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
530,531,Income,Income of individuals,Total after-tax income in 2005 of population 1...,2067450.0,25285.0,18050.0,10010.0,24405.0,21485.0,12365.0,14110.0,13420.0,11340.0,17375.0,5005.0,20665.0,17875.0,16270.0,6285.0,11995.0,6210.0,9715.0,13525.0,9965.0,8390.0,8740.0,10160.0,22880.0,16035.0,11165.0,11975.0,12090.0,8015.0,14005.0,22210.0,18955.0,29570.0,26270.0,10255.0,16335.0,12320.0,17430.0,7270.0,15990.0,15505.0,8485.0,16680.0,10265.0,9185.0,23840.0,12390.0,8285.0,9130.0,18290.0,16700.0,10820.0,15985.0,8445.0,10165.0,11570.0,11715.0,10655.0,27335.0,10840.0,9240.0,13705.0,14905.0,17115.0,6955.0,6215.0,38000.0,12110.0,10765.0,11765.0,12550.0,10295.0,8110.0,34380.0,8445.0,8770.0,21935.0,21875.0,13480.0,7965.0,9900.0,24075.0,12765.0,21810.0,8750.0,13425.0,17650.0,13100.0,9645.0,14165.0,10325.0,18085.0,14420.0,7595.0,12530.0,27565.0,7110.0,6415.0,14280.0,9150.0,7410.0,8560.0,18240.0,12320.0,17725.0,33970.0,7810.0,7580.0,12020.0,16920.0,20535.0,14730.0,21275.0,19995.0,22390.0,11945.0,16815.0,7910.0,13255.0,14550.0,5025.0,13865.0,24100.0,20320.0,24895.0,21010.0,13130.0,9950.0,21945.0,36455.0,11115.0,17510.0,41570.0,9625.0,6875.0,11490.0,9115.0,10290.0,21400.0,12235.0
531,532,Income,Income of individuals,Without after-tax income,115475.0,1510.0,1290.0,370.0,765.0,970.0,735.0,675.0,830.0,775.0,810.0,330.0,1300.0,1025.0,1310.0,365.0,585.0,390.0,370.0,995.0,280.0,420.0,305.0,580.0,650.0,1065.0,635.0,685.0,695.0,380.0,645.0,1275.0,1225.0,1660.0,1265.0,440.0,910.0,615.0,1040.0,500.0,1150.0,780.0,445.0,1355.0,580.0,470.0,1675.0,645.0,265.0,540.0,1050.0,650.0,625.0,1000.0,535.0,525.0,930.0,415.0,535.0,1175.0,515.0,565.0,895.0,885.0,1085.0,280.0,350.0,2470.0,715.0,290.0,635.0,535.0,445.0,395.0,2725.0,635.0,320.0,1565.0,970.0,935.0,165.0,660.0,1880.0,430.0,865.0,420.0,805.0,1140.0,375.0,345.0,950.0,740.0,835.0,765.0,285.0,410.0,1605.0,345.0,220.0,750.0,405.0,735.0,460.0,940.0,470.0,925.0,2235.0,345.0,605.0,855.0,1080.0,1150.0,855.0,1445.0,845.0,1335.0,730.0,615.0,425.0,1200.0,670.0,160.0,605.0,695.0,1330.0,1600.0,1265.0,760.0,710.0,1050.0,2680.0,445.0,985.0,2915.0,465.0,430.0,540.0,325.0,425.0,1365.0,735.0
532,533,Income,Income of individuals,With after-tax income,1951965.0,23775.0,16760.0,9635.0,23645.0,20515.0,11630.0,13435.0,12595.0,10555.0,16590.0,4675.0,19365.0,16845.0,14950.0,5915.0,11410.0,5815.0,9345.0,12530.0,9685.0,7970.0,8430.0,9585.0,22225.0,14955.0,10530.0,11280.0,11400.0,7640.0,13365.0,20930.0,17725.0,27920.0,25005.0,9815.0,15410.0,11705.0,16385.0,6770.0,14835.0,14715.0,8030.0,15335.0,9685.0,8715.0,22150.0,11760.0,8030.0,8595.0,17245.0,16050.0,10195.0,14985.0,7910.0,9635.0,10635.0,11295.0,10120.0,26165.0,10325.0,8670.0,12810.0,14020.0,16030.0,6670.0,5865.0,35525.0,11395.0,10475.0,11115.0,12000.0,9855.0,7715.0,31650.0,7815.0,8460.0,20385.0,20895.0,12560.0,7795.0,9235.0,22180.0,12335.0,20950.0,8330.0,12630.0,16495.0,12725.0,9295.0,13220.0,9580.0,17250.0,13650.0,7310.0,12125.0,25970.0,6765.0,6185.0,13525.0,8745.0,6675.0,8100.0,17295.0,11850.0,16815.0,31735.0,7470.0,6980.0,11165.0,15850.0,19395.0,13865.0,19825.0,19135.0,21040.0,11210.0,16200.0,7485.0,12050.0,13885.0,4865.0,13255.0,23400.0,18975.0,23290.0,19750.0,12370.0,9240.0,20885.0,33765.0,10665.0,16525.0,38665.0,9160.0,6440.0,10950.0,8785.0,9865.0,20040.0,11500.0
548,549,Income,Income of individuals,Median after-tax income $,22545.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,550,Income,Income of individuals,Average after-tax income $,32113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
550,551,Income,Income of individuals,Standard error of average after-tax income $,126.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,594,Income,Income of households,After-tax income in 2005 of private households...,979440.0,8705.0,6730.0,4535.0,14740.0,10960.0,5830.0,8760.0,6135.0,4615.0,8475.0,2510.0,9065.0,9060.0,7095.0,3140.0,5680.0,2450.0,5345.0,6080.0,6060.0,3540.0,4945.0,3925.0,15630.0,7125.0,5350.0,5475.0,5165.0,3910.0,6850.0,9400.0,8315.0,13335.0,12055.0,4975.0,8745.0,5730.0,7860.0,3130.0,8085.0,6650.0,3965.0,7525.0,5375.0,4770.0,9775.0,6050.0,3885.0,4000.0,10330.0,9015.0,3560.0,6440.0,4135.0,3825.0,4605.0,6345.0,4950.0,13215.0,5275.0,4105.0,6405.0,7650.0,7610.0,3310.0,3150.0,15090.0,5975.0,5440.0,5565.0,6490.0,4825.0,4370.0,12715.0,3625.0,4210.0,7370.0,12520.0,5615.0,5310.0,4585.0,9270.0,7185.0,14750.0,4815.0,5720.0,7565.0,8010.0,4940.0,8345.0,5170.0,8645.0,7120.0,3780.0,6055.0,12710.0,2930.0,3580.0,5460.0,3805.0,3635.0,3880.0,8770.0,6460.0,9935.0,12280.0,3765.0,3590.0,5415.0,9935.0,9755.0,6315.0,7570.0,10055.0,9495.0,5960.0,9120.0,3155.0,6415.0,6420.0,2540.0,7095.0,15695.0,9340.0,8965.0,9750.0,7005.0,4305.0,9875.0,17685.0,5440.0,7840.0,18075.0,5240.0,3450.0,5885.0,5235.0,6535.0,9555.0,5425.0
605,606,Income,Income of households,Median after-tax household income $,46236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,607,Income,Income of households,Average after-tax household income $,63868.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,608,Income,Income of households,Standard error of average after-tax household ...,265.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,609,Income,Income of households,After-tax income in 2005 of one-person private...,295515.0,890.0,945.0,1170.0,7680.0,3645.0,1705.0,4410.0,1635.0,905.0,2675.0,685.0,2120.0,2940.0,1450.0,1030.0,1660.0,355.0,2055.0,1225.0,3195.0,710.0,2200.0,380.0,9650.0,1550.0,1560.0,1330.0,1120.0,1260.0,2060.0,1625.0,1810.0,3685.0,2960.0,1625.0,3205.0,1550.0,1730.0,545.0,2860.0,1240.0,1020.0,1760.0,1995.0,2010.0,1640.0,2005.0,925.0,730.0,4420.0,3395.0,295.0,1370.0,1310.0,485.0,675.0,2470.0,1285.0,3810.0,1630.0,1015.0,1835.0,3350.0,1635.0,755.0,890.0,2830.0,1740.0,1480.0,1450.0,2045.0,1500.0,1540.0,1585.0,825.0,1175.0,665.0,5435.0,1035.0,3235.0,1100.0,1325.0,2815.0,8860.0,1835.0,1345.0,1570.0,3980.0,1695.0,3805.0,1645.0,2680.0,2070.0,1160.0,2055.0,2865.0,495.0,1500.0,840.0,625.0,1090.0,1065.0,2750.0,2375.0,4365.0,1425.0,915.0,780.0,1345.0,4610.0,3165.0,1340.0,970.0,2935.0,1965.0,1780.0,3275.0,525.0,1895.0,1845.0,990.0,2435.0,8475.0,2520.0,1135.0,2600.0,2555.0,1105.0,2445.0,5675.0,1895.0,1755.0,3925.0,1965.0,1110.0,2120.0,2295.0,3415.0,2385.0,1485.0
620,621,Income,Income of households,Median after-tax household income $,27123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,622,Income,Income of households,Average after-tax household income $,35055.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,623,Income,Income of households,Standard error of average after-tax household ...,287.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,670,Income,Income of families,After-tax income in 2005 of economic families ...,651680.0,7830.0,5770.0,3290.0,5910.0,7100.0,3980.0,3640.0,4340.0,3655.0,5640.0,1775.0,6815.0,5855.0,5440.0,1945.0,3825.0,2070.0,3100.0,4690.0,2340.0,2760.0,2505.0,3505.0,4730.0,5375.0,3625.0,4060.0,3865.0,2480.0,4530.0,7600.0,6335.0,8800.0,8775.0,2895.0,5310.0,4050.0,5960.0,2555.0,4935.0,5290.0,2855.0,5465.0,3225.0,2615.0,7955.0,3790.0,2880.0,3160.0,5370.0,5245.0,3255.0,5090.0,2755.0,3290.0,3790.0,3450.0,3550.0,8990.0,3350.0,3025.0,4455.0,3560.0,5765.0,2525.0,2220.0,12320.0,4025.0,3860.0,4010.0,4300.0,2990.0,2655.0,11020.0,2770.0,2980.0,6760.0,6680.0,4510.0,1760.0,3340.0,7720.0,4095.0,5020.0,2790.0,4185.0,5775.0,3465.0,3030.0,3865.0,3360.0,5750.0,4835.0,2500.0,3235.0,9455.0,2350.0,1880.0,4655.0,3145.0,2430.0,2775.0,5870.0,3720.0,5185.0,10745.0,2735.0,2755.0,3900.0,4710.0,6145.0,4860.0,6675.0,6895.0,7495.0,3990.0,5540.0,2520.0,4350.0,4000.0,1205.0,4515.0,6355.0,6625.0,7720.0,6930.0,4190.0,3105.0,7180.0,11370.0,3460.0,5975.0,13850.0,3110.0,2235.0,3410.0,2710.0,2860.0,6675.0,3815.0
679,680,Income,Income of families,Median after-tax family income $,56980.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680,681,Income,Income of families,Average after-tax family income $,76446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
681,682,Income,Income of families,Standard error of average after-tax family inc...,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,683,Income,Income of families,After-tax income in 2005 of couple economic fa...,508845.0,6545.0,4570.0,2635.0,4915.0,6010.0,3245.0,2895.0,3505.0,3095.0,4935.0,1055.0,5410.0,4625.0,3360.0,1425.0,2915.0,1910.0,2360.0,3255.0,1900.0,2095.0,2145.0,3010.0,3755.0,4065.0,2975.0,3160.0,2975.0,1990.0,3620.0,6260.0,4885.0,6605.0,6455.0,2355.0,3905.0,3395.0,3990.0,1780.0,3645.0,4275.0,2140.0,4100.0,2620.0,2315.0,5285.0,2730.0,2350.0,2540.0,4390.0,4310.0,2775.0,4145.0,2080.0,2700.0,2895.0,2755.0,2580.0,7190.0,2500.0,2325.0,3190.0,2445.0,4340.0,2190.0,1675.0,9610.0,3425.0,3350.0,3540.0,3730.0,2240.0,2055.0,8405.0,2275.0,2515.0,5615.0,5295.0,3405.0,1400.0,2190.0,5670.0,3455.0,4005.0,1970.0,3380.0,4555.0,2665.0,2490.0,2750.0,2420.0,4210.0,3690.0,1980.0,2560.0,7180.0,1905.0,1580.0,3820.0,2760.0,1545.0,2100.0,4165.0,2970.0,4555.0,8745.0,2230.0,1635.0,2810.0,3235.0,4630.0,4070.0,5445.0,5675.0,5960.0,3090.0,4520.0,1930.0,3620.0,3145.0,955.0,3370.0,5015.0,4715.0,6070.0,5525.0,2820.0,2310.0,5505.0,9165.0,2870.0,4790.0,10775.0,2415.0,1670.0,2580.0,2320.0,2460.0,5040.0,2840.0
692,693,Income,Income of families,Median after-tax family income $,62973.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,694,Income,Income of families,Average after-tax family income $,84507.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,695,Income,Income of families,Standard error of average after-tax family inc...,454.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df_raw[df_raw["Attribute"].str.contains("employment", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
551,552,Income,Income of individuals,Total population 15 years and over with employ...,1395180.0,16555.0,11640.0,7050.0,18510.0,14250.0,7940.0,10260.0,8965.0,7200.0,12415.0,3055.0,12950.0,12570.0,9745.0,4225.0,7910.0,4375.0,6715.0,8600.0,7460.0,5635.0,6350.0,7415.0,17505.0,10455.0,7570.0,7880.0,7605.0,5430.0,9670.0,15015.0,12625.0,19760.0,16750.0,7160.0,11535.0,8740.0,11240.0,4990.0,9480.0,10325.0,5630.0,10225.0,7450.0,6550.0,13870.0,8345.0,5550.0,6360.0,13435.0,12230.0,7815.0,10175.0,4860.0,6125.0,7145.0,9060.0,6955.0,18605.0,8090.0,5920.0,8550.0,9270.0,10850.0,5035.0,4315.0,23970.0,8630.0,8475.0,9050.0,9400.0,6685.0,5925.0,23720.0,5185.0,5915.0,14195.0,15595.0,9080.0,5970.0,6425.0,16255.0,9940.0,16980.0,6090.0,8380.0,11280.0,10955.0,7480.0,9145.0,6290.0,11860.0,9485.0,5295.0,8915.0,18890.0,4700.0,5000.0,9185.0,6575.0,4000.0,5550.0,11575.0,8770.0,12770.0,25115.0,5795.0,4445.0,7280.0,10760.0,14030.0,10390.0,13265.0,13750.0,13610.0,7890.0,13440.0,5075.0,8105.0,9705.0,3665.0,8780.0,19235.0,12860.0,17515.0,13475.0,8530.0,6555.0,14000.0,23495.0,6895.0,10700.0,26190.0,7015.0,4625.0,7830.0,7090.0,7765.0,13695.0,7285.0
552,553,Income,Income of individuals,Median employment income in 2005 $,28675.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,554,Income,Income of individuals,Average employment income in 2005 $,43713.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554,555,Income,Income of individuals,Standard error of average employment inc...,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,557,Income,Income of individuals,Median employment income in 2005 $,43291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,558,Income,Income of individuals,Average employment income in 2005 $,62084.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,559,Income,Income of individuals,Standard error of average employment inc...,352.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560,561,Income,Income of individuals,Median employment income in 2005 $,14380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,562,Income,Income of individuals,Average employment income in 2005 $,26391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,563,Income,Income of individuals,Standard error of average employment inc...,317.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,655,Income,Income of families,Employment income %,79.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,659,Income,Income of families,Employment income %,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,663,Income,Income of families,Employment income %,77.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,667,Income,Income of families,Employment income %,70.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744,745,Income,Income of families,Employment income %,70.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1303,1304,Labour,Labour force status,Employment rate,60.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,1305,Labour,Labour force status,Unemployment rate,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1311,1312,Labour,Labour force status,Employment rate,46.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,1313,Labour,Labour force status,Unemployment rate,16.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1319,1320,Labour,Labour force status,Employment rate,62.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,1321,Labour,Labour force status,Unemployment rate,6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df_raw[df_raw["Attribute"].str.contains("Bachelor", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
1233,1234,Education,"Highest certificate, diploma or degree",University certificate or diploma below ...,10980.0,180.0,110.0,45.0,80.0,80.0,55.0,115.0,170.0,60.0,80.0,40.0,230.0,35.0,105.0,25.0,75.0,20.0,45.0,55.0,0.0,0.0,35.0,40.0,120.0,55.0,55.0,60.0,70.0,20.0,30.0,120.0,155.0,185.0,80.0,35.0,30.0,35.0,110.0,20.0,55.0,45.0,50.0,130.0,35.0,65.0,70.0,55.0,0.0,95.0,75.0,40.0,100.0,105.0,30.0,65.0,75.0,15.0,10.0,165.0,45.0,0.0,60.0,45.0,185.0,10.0,20.0,360.0,20.0,25.0,40.0,30.0,25.0,10.0,290.0,25.0,35.0,215.0,45.0,125.0,50.0,30.0,230.0,25.0,130.0,45.0,95.0,80.0,50.0,35.0,90.0,45.0,35.0,55.0,0.0,55.0,100.0,40.0,20.0,170.0,15.0,35.0,25.0,55.0,30.0,60.0,330.0,0.0,10.0,25.0,60.0,60.0,65.0,95.0,65.0,195.0,100.0,0.0,75.0,70.0,55.0,30.0,70.0,105.0,185.0,220.0,135.0,40.0,0.0,45.0,355.0,60.0,115.0,405.0,50.0,20.0,50.0,15.0,15.0,140.0,85.0
1235,1236,Education,"Highest certificate, diploma or degree",Bachelor's degree,28295.0,365.0,245.0,85.0,915.0,240.0,145.0,830.0,270.0,200.0,295.0,55.0,215.0,115.0,105.0,30.0,80.0,195.0,60.0,150.0,190.0,20.0,165.0,145.0,860.0,75.0,135.0,85.0,75.0,85.0,75.0,255.0,165.0,370.0,130.0,115.0,55.0,165.0,70.0,50.0,170.0,170.0,75.0,120.0,275.0,260.0,150.0,115.0,85.0,130.0,315.0,210.0,215.0,380.0,30.0,65.0,70.0,175.0,125.0,440.0,130.0,25.0,180.0,495.0,130.0,130.0,85.0,460.0,255.0,140.0,315.0,170.0,105.0,80.0,240.0,55.0,55.0,395.0,160.0,95.0,160.0,25.0,325.0,210.0,475.0,95.0,340.0,240.0,180.0,60.0,250.0,35.0,130.0,120.0,50.0,325.0,375.0,45.0,80.0,140.0,185.0,60.0,50.0,115.0,105.0,390.0,440.0,80.0,30.0,85.0,150.0,135.0,370.0,435.0,235.0,310.0,85.0,225.0,80.0,130.0,155.0,260.0,160.0,605.0,130.0,265.0,260.0,55.0,65.0,140.0,1170.0,200.0,155.0,420.0,55.0,20.0,155.0,220.0,225.0,490.0,130.0
1236,1237,Education,"Highest certificate, diploma or degree",University certificate or diploma abov...,2990.0,45.0,60.0,15.0,80.0,25.0,30.0,35.0,10.0,35.0,10.0,0.0,20.0,40.0,10.0,0.0,10.0,30.0,0.0,0.0,0.0,10.0,15.0,10.0,30.0,15.0,25.0,10.0,10.0,0.0,10.0,35.0,0.0,25.0,20.0,15.0,10.0,30.0,10.0,10.0,0.0,35.0,0.0,35.0,20.0,30.0,25.0,15.0,30.0,10.0,50.0,0.0,20.0,50.0,15.0,0.0,25.0,35.0,0.0,30.0,20.0,0.0,0.0,0.0,30.0,20.0,0.0,40.0,20.0,10.0,20.0,10.0,0.0,0.0,50.0,0.0,40.0,15.0,0.0,30.0,10.0,0.0,55.0,20.0,70.0,0.0,20.0,40.0,0.0,0.0,15.0,10.0,20.0,15.0,0.0,10.0,25.0,0.0,0.0,30.0,20.0,10.0,0.0,10.0,0.0,50.0,110.0,10.0,0.0,10.0,15.0,30.0,70.0,30.0,10.0,25.0,20.0,30.0,0.0,10.0,0.0,35.0,25.0,20.0,0.0,110.0,55.0,0.0,10.0,0.0,45.0,10.0,35.0,75.0,10.0,10.0,10.0,0.0,0.0,55.0,50.0
1247,1248,Education,"Highest certificate, diploma or degree",University certificate or diploma below ...,92070.0,1575.0,1055.0,295.0,910.0,820.0,445.0,535.0,780.0,655.0,900.0,155.0,1050.0,700.0,435.0,270.0,650.0,205.0,565.0,480.0,450.0,205.0,395.0,530.0,855.0,690.0,505.0,485.0,310.0,265.0,585.0,1410.0,1250.0,810.0,895.0,360.0,685.0,460.0,885.0,285.0,645.0,600.0,360.0,1005.0,390.0,315.0,625.0,505.0,245.0,450.0,750.0,705.0,755.0,965.0,345.0,255.0,390.0,635.0,600.0,1170.0,395.0,345.0,630.0,475.0,955.0,250.0,230.0,2335.0,720.0,365.0,425.0,495.0,285.0,310.0,2080.0,360.0,255.0,1250.0,910.0,670.0,385.0,375.0,1105.0,490.0,1120.0,465.0,660.0,1090.0,635.0,345.0,780.0,470.0,745.0,630.0,330.0,250.0,1140.0,235.0,145.0,920.0,325.0,275.0,235.0,535.0,375.0,730.0,1885.0,285.0,255.0,660.0,835.0,785.0,690.0,1170.0,610.0,1170.0,765.0,630.0,320.0,665.0,480.0,85.0,780.0,1220.0,1080.0,1205.0,1000.0,455.0,255.0,935.0,2140.0,425.0,695.0,2185.0,385.0,200.0,325.0,300.0,360.0,950.0,430.0
1249,1250,Education,"Highest certificate, diploma or degree",Bachelor's degree,319065.0,3495.0,2420.0,800.0,5935.0,4220.0,1660.0,3355.0,2850.0,2075.0,3705.0,250.0,2360.0,2080.0,740.0,1055.0,1510.0,1305.0,1290.0,960.0,2095.0,405.0,2115.0,1725.0,5455.0,1850.0,1775.0,1315.0,970.0,1275.0,2275.0,4695.0,2085.0,3255.0,1745.0,1535.0,2790.0,2060.0,1690.0,615.0,2295.0,1935.0,1005.0,2560.0,2190.0,2145.0,1005.0,1730.0,1025.0,2120.0,4210.0,3840.0,1330.0,2690.0,835.0,695.0,870.0,2610.0,1230.0,4770.0,1850.0,380.0,1475.0,2395.0,1795.0,1625.0,1225.0,4945.0,2935.0,3055.0,3410.0,3305.0,1305.0,1185.0,3245.0,760.0,1410.0,3220.0,3500.0,1285.0,1890.0,590.0,2365.0,3425.0,6115.0,955.0,2740.0,2835.0,3935.0,2410.0,2615.0,1150.0,1990.0,2040.0,1045.0,2460.0,4285.0,585.0,1545.0,2660.0,1880.0,780.0,685.0,1070.0,2300.0,4285.0,4460.0,1820.0,390.0,990.0,2400.0,3275.0,3120.0,3595.0,3485.0,3640.0,1790.0,4305.0,675.0,2280.0,2265.0,1090.0,1690.0,6775.0,1510.0,2350.0,2820.0,1110.0,525.0,2305.0,9190.0,2180.0,2010.0,5345.0,1865.0,665.0,1900.0,2565.0,2625.0,2160.0,1105.0
1250,1251,Education,"Highest certificate, diploma or degree",University certificate or diploma abov...,54180.0,475.0,380.0,205.0,735.0,780.0,545.0,430.0,450.0,385.0,850.0,50.0,400.0,455.0,130.0,140.0,355.0,280.0,290.0,155.0,285.0,110.0,380.0,215.0,725.0,265.0,300.0,210.0,185.0,240.0,395.0,800.0,375.0,475.0,395.0,195.0,485.0,415.0,345.0,115.0,520.0,410.0,225.0,500.0,470.0,305.0,235.0,215.0,235.0,350.0,840.0,655.0,225.0,435.0,250.0,120.0,145.0,405.0,190.0,745.0,280.0,70.0,200.0,225.0,450.0,280.0,185.0,680.0,515.0,445.0,510.0,650.0,130.0,180.0,460.0,105.0,345.0,380.0,700.0,315.0,280.0,160.0,515.0,580.0,1020.0,265.0,390.0,630.0,395.0,380.0,345.0,255.0,310.0,255.0,255.0,335.0,875.0,125.0,165.0,345.0,405.0,90.0,135.0,275.0,460.0,650.0,930.0,220.0,130.0,265.0,315.0,390.0,575.0,375.0,615.0,395.0,330.0,655.0,90.0,340.0,325.0,145.0,210.0,935.0,335.0,495.0,1065.0,240.0,105.0,375.0,1225.0,315.0,390.0,795.0,290.0,215.0,285.0,470.0,560.0,370.0,170.0
1261,1262,Education,"Highest certificate, diploma or degree",University certificate or diploma below ...,14755.0,205.0,105.0,50.0,255.0,440.0,85.0,85.0,225.0,160.0,275.0,30.0,190.0,90.0,55.0,0.0,95.0,80.0,100.0,40.0,75.0,0.0,135.0,70.0,145.0,65.0,50.0,75.0,20.0,45.0,60.0,255.0,70.0,95.0,60.0,10.0,40.0,70.0,105.0,25.0,160.0,170.0,55.0,110.0,55.0,150.0,75.0,20.0,80.0,115.0,125.0,130.0,85.0,210.0,55.0,30.0,10.0,75.0,50.0,230.0,20.0,10.0,110.0,90.0,135.0,125.0,35.0,480.0,115.0,70.0,90.0,160.0,25.0,30.0,110.0,0.0,185.0,120.0,130.0,125.0,50.0,40.0,100.0,135.0,135.0,35.0,160.0,165.0,45.0,25.0,50.0,15.0,90.0,50.0,45.0,35.0,245.0,20.0,20.0,60.0,150.0,0.0,60.0,95.0,30.0,300.0,150.0,20.0,30.0,105.0,20.0,90.0,165.0,150.0,175.0,185.0,65.0,90.0,55.0,100.0,20.0,20.0,120.0,185.0,170.0,135.0,195.0,95.0,10.0,215.0,310.0,245.0,200.0,315.0,65.0,35.0,120.0,90.0,135.0,115.0,20.0
1263,1264,Education,"Highest certificate, diploma or degree",Bachelor's degree,24760.0,385.0,200.0,30.0,500.0,855.0,160.0,240.0,380.0,340.0,505.0,35.0,140.0,160.0,35.0,50.0,30.0,285.0,50.0,25.0,145.0,20.0,320.0,115.0,355.0,80.0,115.0,135.0,10.0,25.0,85.0,455.0,85.0,70.0,50.0,75.0,120.0,225.0,120.0,30.0,180.0,170.0,60.0,150.0,240.0,345.0,0.0,50.0,240.0,125.0,195.0,315.0,140.0,435.0,105.0,30.0,10.0,100.0,65.0,380.0,35.0,25.0,85.0,165.0,185.0,275.0,80.0,565.0,190.0,230.0,350.0,310.0,10.0,30.0,180.0,50.0,200.0,145.0,305.0,125.0,35.0,60.0,45.0,295.0,305.0,45.0,295.0,270.0,90.0,75.0,100.0,50.0,105.0,155.0,60.0,35.0,585.0,15.0,45.0,240.0,235.0,10.0,75.0,45.0,55.0,870.0,280.0,35.0,40.0,95.0,125.0,145.0,465.0,395.0,165.0,395.0,75.0,260.0,65.0,140.0,65.0,30.0,160.0,295.0,115.0,115.0,330.0,30.0,20.0,200.0,585.0,200.0,215.0,350.0,50.0,40.0,105.0,210.0,475.0,115.0,55.0
1264,1265,Education,"Highest certificate, diploma or degree",University certificate or diploma abov...,6640.0,40.0,35.0,20.0,210.0,185.0,75.0,55.0,80.0,55.0,120.0,0.0,30.0,30.0,10.0,0.0,0.0,60.0,30.0,10.0,25.0,10.0,115.0,90.0,50.0,20.0,45.0,50.0,0.0,20.0,30.0,110.0,20.0,25.0,0.0,15.0,40.0,110.0,25.0,10.0,55.0,70.0,20.0,70.0,55.0,65.0,30.0,0.0,55.0,30.0,70.0,80.0,10.0,130.0,65.0,10.0,0.0,20.0,0.0,90.0,20.0,0.0,10.0,50.0,75.0,70.0,25.0,155.0,105.0,55.0,50.0,125.0,0.0,25.0,10.0,10.0,105.0,60.0,60.0,40.0,20.0,10.0,10.0,40.0,135.0,15.0,110.0,60.0,0.0,30.0,25.0,0.0,0.0,40.0,15.0,20.0,130.0,0.0,55.0,20.0,50.0,10.0,10.0,15.0,25.0,170.0,40.0,10.0,0.0,25.0,15.0,0.0,115.0,65.0,70.0,80.0,25.0,35.0,20.0,35.0,30.0,10.0,10.0,100.0,25.0,10.0,215.0,20.0,10.0,65.0,140.0,115.0,55.0,95.0,10.0,0.0,20.0,45.0,100.0,20.0,25.0

In [31]:
df_raw[df_raw["Attribute"].str.contains("immigrant", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
801,802,Immigration and citizenship,Immigrant status and period of immigration,Total immigrant population by period of immigr...,1237720.0,21770.0,14325.0,4310.0,8315.0,11920.0,8175.0,6660.0,9085.0,7805.0,5880.0,3315.0,13255.0,5890.0,13330.0,2925.0,8810.0,2065.0,5510.0,10020.0,3465.0,6175.0,2685.0,4360.0,8525.0,9695.0,6595.0,4855.0,7660.0,3455.0,6495.0,18615.0,14590.0,18320.0,17815.0,5870.0,5765.0,6125.0,12365.0,5085.0,9675.0,8130.0,5345.0,14330.0,4545.0,2515.0,19535.0,5675.0,2945.0,7985.0,8505.0,6325.0,6870.0,12685.0,5030.0,7980.0,9405.0,4880.0,7485.0,15370.0,5250.0,6130.0,9445.0,9080.0,11975.0,1860.0,2660.0,30350.0,5895.0,2725.0,2820.0,2935.0,5930.0,3400.0,27840.0,5580.0,3780.0,19100.0,10355.0,9660.0,3155.0,7285.0,21535.0,3925.0,9390.0,3980.0,9540.0,13005.0,5030.0,3355.0,10150.0,7805.0,11510.0,7335.0,3115.0,5460.0,18170.0,4130.0,2015.0,11120.0,3290.0,5550.0,4945.0,12220.0,5925.0,5535.0,23850.0,2805.0,5400.0,8515.0,10400.0,9825.0,7710.0,18395.0,9205.0,17405.0,9180.0,3900.0,5455.0,12090.0,7825.0,1835.0,9210.0,9940.0,12250.0,18820.0,17405.0,7660.0,6775.0,12600.0,25535.0,6440.0,9975.0,30605.0,3310.0,2785.0,5415.0,2435.0,3250.0,15695.0,8280.0
810,811,Immigration and citizenship,Age at immigration,Total immigrant population by age at immigrati...,1237720.0,21760.0,14325.0,4305.0,8325.0,11925.0,8175.0,6655.0,9085.0,7810.0,5885.0,3315.0,13250.0,5890.0,13330.0,2925.0,8805.0,2065.0,5510.0,10025.0,3465.0,6180.0,2685.0,4365.0,8525.0,9695.0,6590.0,4860.0,7665.0,3460.0,6500.0,18620.0,14590.0,18325.0,17820.0,5865.0,5760.0,6120.0,12370.0,5085.0,9675.0,8130.0,5340.0,14335.0,4550.0,2510.0,19530.0,5680.0,2940.0,7980.0,8510.0,6325.0,6870.0,12690.0,5040.0,7975.0,9400.0,4875.0,7485.0,15380.0,5245.0,6115.0,9445.0,9080.0,11970.0,1855.0,2665.0,30365.0,5900.0,2730.0,2810.0,2935.0,5935.0,3405.0,27830.0,5570.0,3780.0,19080.0,10350.0,9650.0,3155.0,7280.0,21530.0,3930.0,9385.0,3980.0,9535.0,13005.0,5035.0,3350.0,10150.0,7805.0,11510.0,7330.0,3115.0,5470.0,18170.0,4135.0,2010.0,11125.0,3285.0,5545.0,4935.0,12210.0,5925.0,5530.0,23850.0,2805.0,5400.0,8520.0,10390.0,9820.0,7710.0,18395.0,9195.0,17395.0,9180.0,3910.0,5455.0,12080.0,7830.0,1835.0,9215.0,9940.0,12250.0,18835.0,17405.0,7665.0,6780.0,12600.0,25530.0,6440.0,9975.0,30615.0,3315.0,2785.0,5405.0,2425.0,3255.0,15695.0,8275.0
816,817,Immigration and citizenship,Immigrants by selected place of birth,Total population by immigrant status and place...,2476565.0,29975.0,21475.0,11640.0,26435.0,25025.0,14615.0,15235.0,15360.0,13050.0,21875.0,6290.0,24810.0,21320.0,21565.0,7715.0,14195.0,7660.0,11365.0,17315.0,10710.0,10255.0,9785.0,12325.0,23960.0,19555.0,13685.0,14495.0,14330.0,9525.0,16455.0,26405.0,23750.0,34605.0,31960.0,11745.0,19770.0,14450.0,22190.0,9440.0,20510.0,18475.0,10295.0,21280.0,12275.0,10650.0,30710.0,14660.0,9775.0,11285.0,20720.0,19505.0,12835.0,18340.0,10065.0,12760.0,14770.0,13855.0,13010.0,32325.0,13035.0,11200.0,16920.0,16745.0,21390.0,8670.0,7785.0,45810.0,14440.0,13685.0,14825.0,15955.0,11785.0,9605.0,44285.0,10175.0,10145.0,26140.0,24885.0,16935.0,8560.0,12625.0,32100.0,15215.0,23545.0,10440.0,15150.0,20300.0,14390.0,11400.0,16905.0,13360.0,21430.0,17735.0,9020.0,13740.0,33745.0,8720.0,7540.0,16605.0,10960.0,10290.0,10445.0,22385.0,14565.0,20320.0,42815.0,9555.0,9860.0,15455.0,19845.0,23940.0,17540.0,24450.0,23695.0,26830.0,14985.0,20315.0,9760.0,17750.0,16315.0,5450.0,16730.0,25950.0,25340.0,31390.0,24400.0,16240.0,12095.0,26445.0,41030.0,12480.0,20900.0,52325.0,11510.0,8035.0,13420.0,10490.0,11235.0,25980.0,14430.0
817,818,Immigration and citizenship,Immigrants by selected place of birth,Non-immigrants,1184235.0,7665.0,6710.0,7310.0,16910.0,12685.0,6130.0,7050.0,5845.0,4990.0,15460.0,2800.0,10985.0,15305.0,7910.0,4690.0,4975.0,5465.0,5620.0,6925.0,7090.0,3870.0,6765.0,7915.0,14075.0,9595.0,6860.0,9570.0,6335.0,5930.0,9800.0,7215.0,8800.0,15365.0,13290.0,5415.0,13800.0,8175.0,9400.0,4190.0,10350.0,10205.0,4835.0,6115.0,7300.0,7835.0,10475.0,8765.0,6795.0,2940.0,11375.0,12945.0,5875.0,5275.0,4940.0,4635.0,5055.0,8650.0,5300.0,16390.0,7490.0,4920.0,7180.0,6850.0,8935.0,6755.0,5050.0,14515.0,8000.0,10795.0,11870.0,12930.0,5680.0,6065.0,15785.0,4385.0,6320.0,6490.0,13915.0,6920.0,5115.0,4960.0,9780.0,11140.0,13375.0,6310.0,4995.0,6520.0,9160.0,7905.0,5805.0,5175.0,9240.0,10220.0,5825.0,7870.0,15000.0,4470.0,5450.0,5195.0,7565.0,4580.0,5355.0,9790.0,8400.0,14290.0,18575.0,6635.0,4360.0,6525.0,8765.0,13855.0,9565.0,5680.0,14075.0,9025.0,5405.0,16135.0,4150.0,5280.0,8145.0,3295.0,7200.0,15285.0,12905.0,12065.0,6180.0,8165.0,5110.0,13425.0,13445.0,5825.0,10730.0,20430.0,8115.0,5195.0,7655.0,7850.0,7725.0,8805.0,5985.0
820,821,Immigration and citizenship,Immigrants by selected place of birth,Immigrants,1237720.0,21765.0,14325.0,4310.0,8325.0,11915.0,8180.0,6650.0,9080.0,7795.0,5880.0,3320.0,13260.0,5885.0,13330.0,2920.0,8805.0,2065.0,5510.0,10025.0,3470.0,6175.0,2680.0,4355.0,8530.0,9695.0,6590.0,4850.0,7660.0,3450.0,6495.0,18625.0,14585.0,18315.0,17815.0,5870.0,5770.0,6125.0,12370.0,5080.0,9675.0,8130.0,5340.0,14340.0,4545.0,2520.0,19540.0,5675.0,2945.0,7985.0,8505.0,6325.0,6870.0,12700.0,5030.0,7970.0,9405.0,4880.0,7490.0,15370.0,5255.0,6125.0,9440.0,9090.0,11970.0,1855.0,2665.0,30355.0,5895.0,2725.0,2815.0,2935.0,5935.0,3400.0,27825.0,5570.0,3780.0,19095.0,10360.0,9655.0,3155.0,7285.0,21535.0,3935.0,9385.0,3980.0,9545.0,13000.0,5035.0,3350.0,10150.0,7810.0,11520.0,7335.0,3110.0,5465.0,18175.0,4130.0,2010.0,11125.0,3285.0,5540.0,4935.0,12210.0,5925.0,5535.0,23850.0,2810.0,5395.0,8515.0,10395.0,9820.0,7705.0,18395.0,9200.0,17395.0,9185.0,3910.0,5455.0,12080.0,7830.0,1835.0,9220.0,9930.0,12250.0,18820.0,17400.0,7665.0,6785.0,12590.0,25530.0,6445.0,9970.0,30600.0,3310.0,2780.0,5410.0,2430.0,3250.0,15705.0,8275.0
854,855,Immigration and citizenship,Recent immigrants by selected place of birth,Total recent immigrants by selected places of ...,267855.0,4275.0,3055.0,285.0,1250.0,2405.0,2145.0,1840.0,2020.0,1700.0,775.0,405.0,2395.0,710.0,2760.0,350.0,1930.0,135.0,1300.0,2090.0,630.0,780.0,475.0,425.0,1975.0,2510.0,1305.0,630.0,715.0,465.0,810.0,6960.0,3660.0,2610.0,2985.0,1060.0,1090.0,1405.0,2665.0,925.0,1890.0,790.0,1355.0,4895.0,1610.0,410.0,3000.0,965.0,240.0,3705.0,2130.0,665.0,330.0,2345.0,835.0,1790.0,2350.0,1080.0,2095.0,3565.0,920.0,485.0,1915.0,2245.0,2885.0,100.0,400.0,7885.0,1885.0,215.0,370.0,395.0,735.0,715.0,4985.0,1105.0,545.0,3405.0,1910.0,2065.0,600.0,1435.0,7125.0,625.0,2795.0,595.0,2255.0,3780.0,785.0,450.0,3680.0,2925.0,1745.0,1930.0,405.0,515.0,5685.0,440.0,340.0,2920.0,500.0,1540.0,865.0,1525.0,1105.0,855.0,2550.0,240.0,740.0,2290.0,3735.0,1950.0,1860.0,3790.0,1745.0,5280.0,3650.0,580.0,950.0,5570.0,1070.0,245.0,2090.0,1630.0,1850.0,3825.0,5850.0,1615.0,635.0,2125.0,6425.0,1190.0,2025.0,9135.0,520.0,345.0,575.0,390.0,630.0,4135.0,1040.0

In [32]:
df_raw[df_raw["Attribute"].str.contains("visible", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
902,903,Ethnocultural diversity,Visible minority population,Total population by visible minority groups - ...,2476565.0,29980.0,21475.0,11640.0,26445.0,25025.0,14610.0,15235.0,15360.0,13045.0,21880.0,6285.0,24815.0,21310.0,21560.0,7715.0,14195.0,7660.0,11365.0,17315.0,10715.0,10250.0,9785.0,12320.0,23960.0,19565.0,13685.0,14500.0,14330.0,9525.0,16465.0,26400.0,23745.0,34615.0,31955.0,11745.0,19775.0,14445.0,22190.0,9435.0,20510.0,18475.0,10295.0,21280.0,12280.0,10650.0,30710.0,14665.0,9770.0,11285.0,20720.0,19505.0,12835.0,18340.0,10055.0,12755.0,14770.0,13855.0,13015.0,32315.0,13040.0,11200.0,16920.0,16735.0,21390.0,8670.0,7785.0,45825.0,14440.0,13690.0,14820.0,15955.0,11770.0,9610.0,44280.0,10175.0,10145.0,26150.0,24895.0,16930.0,8560.0,12635.0,32105.0,15210.0,23545.0,10440.0,15145.0,20305.0,14395.0,11405.0,16905.0,13360.0,21435.0,17735.0,9020.0,13745.0,33740.0,8720.0,7535.0,16600.0,10960.0,10295.0,10445.0,22385.0,14565.0,20320.0,42815.0,9555.0,9865.0,15460.0,19840.0,23945.0,17535.0,24450.0,23690.0,26835.0,14990.0,20315.0,9755.0,17755.0,16310.0,5440.0,16730.0,25955.0,25345.0,31380.0,24395.0,16240.0,12095.0,26445.0,41025.0,12480.0,20900.0,52310.0,11500.0,8035.0,13415.0,10485.0,11230.0,25975.0,14430.0
903,904,Ethnocultural diversity,Visible minority population,Total visible minority population,1162630.0,26440.0,16790.0,1185.0,5440.0,9660.0,3565.0,7995.0,9060.0,7580.0,2760.0,3325.0,14475.0,4415.0,16840.0,3165.0,5810.0,1545.0,2765.0,10885.0,2465.0,3605.0,1420.0,4285.0,8300.0,9645.0,4105.0,3910.0,3435.0,2540.0,4540.0,17320.0,17080.0,12825.0,15470.0,4365.0,5320.0,1875.0,15235.0,5710.0,7340.0,5120.0,3700.0,16430.0,2255.0,1190.0,22270.0,6460.0,2195.0,7935.0,4150.0,2615.0,8500.0,13245.0,2045.0,6915.0,10350.0,3945.0,8595.0,10070.0,3740.0,3845.0,10960.0,11015.0,11605.0,740.0,1625.0,34905.0,4360.0,1635.0,1335.0,1480.0,3165.0,1855.0,38350.0,3685.0,1565.0,24575.0,5935.0,11735.0,3400.0,8240.0,27380.0,1860.0,6640.0,3090.0,9265.0,8550.0,4740.0,2920.0,11530.0,9710.0,8725.0,6660.0,2095.0,3335.0,16755.0,3175.0,1120.0,10085.0,1545.0,8115.0,4370.0,10555.0,4610.0,2760.0,32415.0,1130.0,5460.0,10140.0,11010.0,11455.0,6960.0,21245.0,2750.0,18685.0,9415.0,1910.0,5250.0,13290.0,5060.0,1345.0,9150.0,9545.0,13990.0,24440.0,7320.0,8295.0,4500.0,12045.0,27710.0,4650.0,7290.0,35815.0,2870.0,2475.0,3830.0,1575.0,1440.0,16435.0,5835.0
914,915,Ethnocultural diversity,Visible minority population,"Visible minority, n.i.e.",25195.0,195.0,170.0,15.0,60.0,95.0,95.0,50.0,60.0,20.0,30.0,155.0,545.0,55.0,950.0,10.0,160.0,0.0,60.0,145.0,10.0,45.0,0.0,70.0,155.0,205.0,10.0,140.0,100.0,50.0,75.0,50.0,395.0,450.0,265.0,105.0,50.0,55.0,480.0,150.0,150.0,60.0,35.0,145.0,65.0,0.0,830.0,95.0,70.0,95.0,110.0,75.0,310.0,80.0,35.0,240.0,355.0,120.0,250.0,135.0,65.0,115.0,295.0,165.0,115.0,25.0,20.0,285.0,45.0,15.0,10.0,15.0,45.0,45.0,1485.0,120.0,10.0,185.0,260.0,215.0,70.0,235.0,1250.0,20.0,125.0,90.0,65.0,45.0,75.0,40.0,310.0,95.0,145.0,195.0,45.0,50.0,200.0,55.0,15.0,110.0,10.0,75.0,100.0,410.0,310.0,20.0,1220.0,30.0,150.0,380.0,1250.0,50.0,25.0,50.0,40.0,210.0,110.0,50.0,100.0,95.0,0.0,25.0,185.0,125.0,645.0,1055.0,70.0,105.0,95.0,405.0,100.0,50.0,170.0,905.0,95.0,95.0,100.0,25.0,15.0,295.0,95.0
915,916,Ethnocultural diversity,Visible minority population,Multiple visible minority,31100.0,440.0,380.0,45.0,270.0,185.0,80.0,205.0,145.0,150.0,45.0,75.0,550.0,240.0,565.0,50.0,150.0,55.0,105.0,205.0,105.0,75.0,85.0,140.0,275.0,165.0,155.0,105.0,130.0,80.0,50.0,205.0,615.0,590.0,380.0,110.0,360.0,30.0,485.0,145.0,210.0,90.0,55.0,340.0,50.0,10.0,815.0,230.0,145.0,100.0,85.0,90.0,130.0,280.0,35.0,85.0,80.0,135.0,340.0,215.0,185.0,80.0,510.0,350.0,185.0,65.0,45.0,700.0,150.0,65.0,55.0,75.0,100.0,45.0,1095.0,60.0,25.0,435.0,160.0,375.0,120.0,240.0,365.0,145.0,295.0,65.0,165.0,145.0,200.0,90.0,260.0,245.0,375.0,180.0,125.0,120.0,440.0,60.0,55.0,205.0,30.0,160.0,100.0,470.0,45.0,100.0,1210.0,35.0,65.0,195.0,470.0,340.0,135.0,390.0,80.0,465.0,105.0,155.0,60.0,235.0,135.0,40.0,195.0,400.0,615.0,585.0,160.0,180.0,225.0,380.0,635.0,160.0,215.0,650.0,65.0,95.0,125.0,110.0,35.0,375.0,195.0
916,917,Ethnocultural diversity,Visible minority population,Not a visible minority,1313935.0,3530.0,4685.0,10455.0,21005.0,15365.0,11050.0,7245.0,6295.0,5465.0,19120.0,2965.0,10345.0,16895.0,4725.0,4545.0,8380.0,6105.0,8600.0,6425.0,8255.0,6645.0,8365.0,8035.0,15665.0,9920.0,9580.0,10590.0,10895.0,6990.0,11920.0,9070.0,6650.0,21775.0,16480.0,7380.0,14455.0,12560.0,6960.0,3730.0,13165.0,13355.0,6595.0,4860.0,10015.0,9460.0,8435.0,8200.0,7585.0,3360.0,16565.0,16885.0,4335.0,5100.0,8010.0,5835.0,4425.0,9910.0,4405.0,22250.0,9280.0,7355.0,5955.0,5715.0,9785.0,7925.0,6155.0,10905.0,10075.0,12050.0,13485.0,14475.0,8615.0,7755.0,5940.0,6485.0,8575.0,1580.0,18955.0,5200.0,5160.0,4385.0,4735.0,13350.0,16905.0,7350.0,5885.0,11740.0,9645.0,8480.0,5370.0,3655.0,12710.0,11070.0,6915.0,10410.0,16970.0,5540.0,6420.0,6520.0,9425.0,2175.0,6075.0,11835.0,9960.0,17555.0,10385.0,8425.0,4405.0,5320.0,8825.0,12490.0,10575.0,3205.0,20945.0,8140.0,5575.0,18405.0,4505.0,4455.0,11250.0,4105.0,7575.0,16410.0,11360.0,6930.0,17075.0,7940.0,7590.0,14395.0,13315.0,7840.0,13610.0,16495.0,8635.0,5560.0,9590.0,8915.0,9790.0,9535.0,8600.0

In [34]:
df_raw[df_raw["Attribute"].str.contains("dwelling", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
1164,1165,Housing,Dwelling type,Total number of occupied private dwellings by ...,979330.0,8715.0,6740.0,4540.0,14740.0,10950.0,5820.0,8755.0,6135.0,4615.0,8480.0,2520.0,9065.0,9060.0,7105.0,3135.0,5680.0,2445.0,5345.0,6090.0,6060.0,3540.0,4955.0,3925.0,15615.0,7125.0,5350.0,5475.0,5165.0,3905.0,6850.0,9405.0,8310.0,13340.0,12075.0,4975.0,8745.0,5740.0,7870.0,3130.0,8100.0,6655.0,3970.0,7530.0,5380.0,4770.0,9785.0,6050.0,3890.0,4000.0,10330.0,9015.0,3565.0,6445.0,4135.0,3830.0,4605.0,6330.0,4955.0,13205.0,5280.0,4110.0,6400.0,7655.0,7615.0,3315.0,3150.0,15080.0,5985.0,5445.0,5570.0,6490.0,4835.0,4365.0,12710.0,3620.0,4210.0,7380.0,12530.0,5615.0,8135.0,4590.0,9270.0,7190.0,14710.0,4815.0,5725.0,7570.0,8015.0,4940.0,8355.0,5165.0,8650.0,7125.0,3790.0,6060.0,12695.0,2930.0,3585.0,5465.0,3810.0,3635.0,3880.0,8775.0,6465.0,9950.0,12285.0,3770.0,3590.0,5420.0,9945.0,9755.0,6320.0,7570.0,10055.0,9490.0,5955.0,9110.0,3150.0,6415.0,6420.0,2545.0,7095.0,15710.0,9335.0,8970.0,9740.0,7010.0,4310.0,9880.0,17685.0,5450.0,7835.0,18085.0,5240.0,3450.0,5890.0,5235.0,6535.0,9560.0,5375.0
1172,1173,Housing,Dwelling type,Movable dwelling,160.0,0.0,5.0,5.0,0.0,5.0,0.0,0.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0,10.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,10.0,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1173,1174,Housing,Housing tenure,Total number of occupied private dwellings by ...,979440.0,8705.0,6735.0,4530.0,14745.0,10955.0,5825.0,8760.0,6135.0,4610.0,8480.0,2515.0,9065.0,9060.0,7090.0,3140.0,5680.0,2440.0,5345.0,6090.0,6060.0,3545.0,4945.0,3925.0,15620.0,7120.0,5345.0,5480.0,5175.0,3905.0,6855.0,9400.0,8315.0,13330.0,12055.0,4975.0,8740.0,5725.0,7865.0,3130.0,8085.0,6655.0,3965.0,7520.0,5380.0,4775.0,9780.0,6045.0,3885.0,3990.0,10330.0,9015.0,3565.0,6440.0,4140.0,3830.0,4600.0,6345.0,4950.0,13210.0,5280.0,4105.0,6400.0,7650.0,7610.0,3305.0,3145.0,15080.0,5970.0,5440.0,5570.0,6495.0,4830.0,4365.0,12720.0,3630.0,4210.0,7375.0,12525.0,5615.0,5305.0,4585.0,9265.0,7190.0,14745.0,4810.0,5725.0,7575.0,8010.0,4940.0,8345.0,5165.0,8650.0,7120.0,3780.0,6055.0,12705.0,2930.0,3580.0,5460.0,3810.0,3635.0,3880.0,8770.0,6465.0,9935.0,12285.0,3765.0,3585.0,5420.0,9945.0,9770.0,6320.0,7560.0,10055.0,9475.0,5960.0,9110.0,3150.0,6415.0,6420.0,2540.0,7100.0,15700.0,9340.0,8970.0,9740.0,7005.0,4305.0,9875.0,17670.0,5450.0,7840.0,18065.0,5240.0,3450.0,5880.0,5230.0,6540.0,9545.0,5425.0
1177,1178,Housing,Dwelling characteristics,Total number of occupied private dwellings - 2...,979440.0,8710.0,6735.0,4535.0,14745.0,10955.0,5825.0,8750.0,6135.0,4620.0,8480.0,2510.0,9060.0,9065.0,7100.0,3135.0,5680.0,2440.0,5345.0,6080.0,6060.0,3545.0,4945.0,3925.0,15625.0,7115.0,5350.0,5475.0,5170.0,3915.0,6860.0,9395.0,8310.0,13330.0,12060.0,4975.0,8740.0,5730.0,7865.0,3130.0,8090.0,6650.0,3970.0,7520.0,5375.0,4775.0,9780.0,6050.0,3880.0,4000.0,10330.0,9015.0,3570.0,6440.0,4135.0,3825.0,4600.0,6340.0,4950.0,13200.0,5280.0,4105.0,6400.0,7650.0,7610.0,3300.0,3150.0,15075.0,5970.0,5440.0,5570.0,6495.0,4830.0,4365.0,12720.0,3630.0,4210.0,7370.0,12525.0,5615.0,5305.0,4595.0,9270.0,7185.0,14755.0,4815.0,5725.0,7570.0,8005.0,4940.0,8350.0,5165.0,8645.0,7120.0,3780.0,6060.0,12705.0,2930.0,3580.0,5465.0,3810.0,3635.0,3875.0,8775.0,6460.0,9930.0,12280.0,3770.0,3590.0,5420.0,9945.0,9755.0,6320.0,7565.0,10055.0,9475.0,5960.0,9115.0,3145.0,6415.0,6420.0,2540.0,7100.0,15695.0,9335.0,8970.0,9735.0,7005.0,4305.0,9865.0,17675.0,5445.0,7830.0,18060.0,5245.0,3450.0,5880.0,5235.0,6540.0,9560.0,5425.0
1178,1179,Housing,Dwelling characteristics,Average number of rooms per dwelling,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1179,1180,Housing,Dwelling characteristics,Average number of bedrooms per dwelling,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1180,1181,Housing,Dwelling age,Total number of occupied private dwellings by ...,979440.0,8710.0,6735.0,4530.0,14750.0,10950.0,5820.0,8750.0,6135.0,4610.0,8480.0,2510.0,9060.0,9065.0,7090.0,3135.0,5680.0,2445.0,5340.0,6080.0,6060.0,3545.0,4945.0,3925.0,15620.0,7115.0,5350.0,5475.0,5170.0,3910.0,6855.0,9400.0,8305.0,13340.0,12045.0,4975.0,8745.0,5730.0,7860.0,3130.0,8085.0,6650.0,3960.0,7515.0,5380.0,4775.0,9775.0,6055.0,3885.0,3995.0,10340.0,9015.0,3560.0,6440.0,4140.0,3830.0,4605.0,6340.0,4950.0,13210.0,5285.0,4105.0,6405.0,7650.0,7610.0,3305.0,3150.0,15080.0,5970.0,5440.0,5570.0,6495.0,4825.0,4365.0,12710.0,3625.0,4210.0,7375.0,12520.0,5615.0,5310.0,4595.0,9275.0,7185.0,14750.0,4815.0,5720.0,7570.0,8005.0,4940.0,8350.0,5165.0,8645.0,7120.0,3785.0,6060.0,12690.0,2930.0,3575.0,5455.0,3805.0,3635.0,3885.0,8770.0,6460.0,9930.0,12285.0,3765.0,3595.0,5425.0,9940.0,9760.0,6315.0,7575.0,10050.0,9470.0,5955.0,9115.0,3145.0,6415.0,6425.0,2540.0,7100.0,15700.0,9345.0,8965.0,9740.0,7005.0,4305.0,9875.0,17685.0,5450.0,7830.0,18060.0,5245.0,3450.0,5885.0,5230.0,6535.0,9560.0,5425.0
1190,1191,Housing,Dwelling condition,Total number of occupied private dwellings by ...,979440.0,8710.0,6730.0,4535.0,14745.0,10950.0,5825.0,8755.0,6130.0,4610.0,8480.0,2510.0,9055.0,9055.0,7095.0,3140.0,5680.0,2440.0,5340.0,6080.0,6060.0,3545.0,4945.0,3930.0,15620.0,7120.0,5345.0,5470.0,5165.0,3910.0,6850.0,9395.0,8315.0,13340.0,12055.0,4975.0,8750.0,5730.0,7865.0,3130.0,8085.0,6655.0,3960.0,7525.0,5380.0,4775.0,9780.0,6055.0,3885.0,3995.0,10335.0,9015.0,3570.0,6440.0,4140.0,3825.0,4605.0,6345.0,4950.0,13200.0,5280.0,4105.0,6405.0,7650.0,7610.0,3310.0,3150.0,15070.0,5970.0,5445.0,5575.0,6490.0,4825.0,4365.0,12720.0,3625.0,4210.0,7375.0,12525.0,5610.0,5310.0,4595.0,9265.0,7185.0,14740.0,4800.0,5720.0,7565.0,8010.0,4940.0,8350.0,5165.0,8645.0,7115.0,3780.0,6060.0,12695.0,2935.0,3580.0,5460.0,3805.0,3635.0,3880.0,8775.0,6460.0,9930.0,12290.0,3770.0,3585.0,5420.0,9935.0,9760.0,6315.0,7565.0,10050.0,9490.0,5955.0,9115.0,3145.0,6415.0,6415.0,2540.0,7100.0,15700.0,9345.0,8965.0,9740.0,7005.0,4305.0,9865.0,17670.0,5440.0,7840.0,18070.0,5240.0,3450.0,5880.0,5235.0,6540.0,9555.0,5425.0
1194,1195,Housing,Shelter costs,"Total number of non-farm, non-reserve private ...",979425.0,8710.0,6735.0,4535.0,14750.0,10955.0,5820.0,8750.0,6130.0,4615.0,8480.0,2510.0,9055.0,9055.0,7095.0,3140.0,5680.0,2440.0,5345.0,6090.0,6055.0,3545.0,4945.0,3920.0,15620.0,7120.0,5345.0,5475.0,5170.0,3910.0,6850.0,9390.0,8310.0,13340.0,12060.0,4975.0,8740.0,5735.0,7860.0,3130.0,8090.0,6650.0,3960.0,7525.0,5380.0,4775.0,9785.0,6055.0,3885.0,3995.0,10335.0,9015.0,3565.0,6450.0,4135.0,3830.0,4600.0,6345.0,4950.0,13210.0,5280.0,4105.0,6410.0,7650.0,7615.0,3310.0,3150.0,15075.0,5970.0,5440.0,5570.0,6495.0,4825.0,4365.0,12715.0,3630.0,4210.0,7365.0,12530.0,5615.0,5305.0,4595.0,9265.0,7190.0,14740.0,4810.0,5725.0,7570.0,8005.0,4940.0,8350.0,5165.0,8650.0,7120.0,3780.0,6060.0,12700.0,2925.0,3585.0,5460.0,3810.0,3635.0,3880.0,8775.0,6460.0,9935.0,12280.0,3765.0,3590.0,5420.0,9940.0,9750.0,6320.0,7570.0,10055.0,9480.0,5960.0,9120.0,3150.0,6415.0,6420.0,2540.0,7100.0,15695.0,9335.0,8960.0,9745.0,7010.0,4305.0,9880.0,17685.0,5445.0,7835.0,18065.0,5240.0,3450.0,5885.0,5230.0,6540.0,9545.0,5425.0
1195,1196,Housing,Shelter costs,"Tenant-occupied private non-farm, non-reserv...",446855.0,1605.0,1775.0,990.0,9400.0,4260.0,2770.0,5980.0,2145.0,1855.0,2665.0,1625.0,2890.0,2940.0,4690.0,1400.0,2880.0,130.0,3775.0,3420.0,3285.0,1120.0,3030.0,240.0,11155.0,2600.0,2475.0,1780.0,1655.0,1385.0,1940.0,4715.0,3115.0,6305.0,6485.0,2985.0,4060.0,2575.0,4275.0,1285.0,4675.0,940.0,1720.0,4175.0,3605.0,2165.0,4570.0,2385.0,820.0,2495.0,7025.0,3470.0,225.0,1470.0,1825.0,975.0,2160.0,3995.0,2930.0,5340.0,2370.0,1325.0,2860.0,5370.0,3255.0,540.0,1325.0,5215.0,2405.0,1400.0,1520.0,1740.0,2470.0,2205.0,3660.0,1680.0,990.0,1025.0,5605.0,2015.0,3105.0,2210.0,4815.0,2925.0,11900.0,2680.0,1760.0,3380.0,2935.0,2195.0,8045.0,3630.0,3945.0,3435.0,1095.0,3210.0,7665.0,500.0,1965.0,1360.0,550.0,3245.0,1750.0,3700.0,3565.0,4410.0,1640.0,735.0,2155.0,3010.0,9090.0,3915.0,2070.0,1265.0,3565.0,4165.0,3795.0,3310.0,1090.0,5835.0,2780.0,1415.0,3995.0,8135.0,3760.0,2450.0,6010.0,4355.0,1645.0,3695.0,5940.0,1635.0,3355.0,8210.0,2175.0,1035.0,3120.0,3095.0,4075.0,5340.0,2270.0
1199,1200,Housing,Shelter costs,"Owner-occupied private non-farm, non-reserve...",532575.0,7105.0,4945.0,3550.0,5340.0,6690.0,3050.0,2775.0,3985.0,2755.0,5825.0,885.0,6175.0,6125.0,2400.0,1735.0,2800.0,2310.0,1575.0,2670.0,2770.0,2425.0,1915.0,3680.0,4465.0,4525.0,2870.0,3700.0,3515.0,2525.0,4920.0,4665.0,5195.0,7030.0,5575.0,1985.0,4695.0,3160.0,3585.0,1840.0,3415.0,5710.0,2245.0,3355.0,1770.0,2610.0,5205.0,3670.0,3060.0,1500.0,3305.0,5550.0,3335.0,4960.0,2310.0,2860.0,2445.0,2345.0,2015.0,7875.0,2905.0,2785.0,3540.0,2270.0,4365.0,2780.0,1825.0,9855.0,3560.0,4040.0,4050.0,4755.0,2360.0,2155.0,9055.0,1950.0,3220.0,6345.0,6920.0,3600.0,2200.0,2385.0,4450.0,4265.0,2840.0,2130.0,3950.0,4195.0,5075.0,2745.0,305.0,1540.0,4700.0,3690.0,2685.0,2855.0,5030.0,2430.0,1620.0,4105.0,3250.0,395.0,2130.0,5080.0,2895.0,5535.0,10640.0,3025.0,1430.0,2405.0,850.0,5830.0,4245.0,6305.0,6490.0,5315.0,2160.0,5800.0,2065.0,570.0,3640.0,1125.0,3095.0,7560.0,5580.0,6505.0,3735.0,2650.0,2660.0,6170.0,11745.0,3805.0,4475.0,9865.0,3065.0,2415.0,2755.0,2135.0,2455.0,4215.0,3165.0
1200,1201,Housing,Shelter costs,Average value of dwelling $,413574.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1204,1205,Housing,Shelter costs,Tenant one-family households without additio...,204740.0,1105.0,1130.0,500.0,2370.0,2040.0,1325.0,2165.0,1100.0,1040.0,945.0,935.0,1585.0,1220.0,2760.0,595.0,1435.0,90.0,1710.0,2025.0,910.0,590.0,960.0,170.0,2520.0,1555.0,1165.0,915.0,820.0,380.0,825.0,3250.0,1885.0,2490.0,3510.0,1210.0,1520.0,1340.0,2470.0,810.0,2275.0,585.0,975.0,2650.0,1505.0,700.0,2770.0,880.0,425.0,1675.0,2615.0,1400.0,90.0,655.0,930.0,660.0,1400.0,1330.0,1640.0,2815.0,885.0,670.0,1445.0,1670.0,1935.0,260.0,680.0,2970.0,1260.0,540.0,525.0,545.0,990.0,1020.0,2300.0,965.0,570.0,600.0,2210.0,1255.0,690.0,1250.0,2965.0,865.0,3260.0,1150.0,825.0,2015.0,1110.0,735.0,3135.0,1960.0,1635.0,1725.0,470.0,840.0,4700.0,255.0,555.0,845.0,330.0,1990.0,855.0,1710.0,1290.0,1295.0,890.0,315.0,1315.0,1640.0,3450.0,1580.0,1100.0,750.0,1800.0,2315.0,2135.0,1045.0,675.0,3615.0,930.0,315.0,1890.0,2935.0,1865.0,1510.0,3760.0,1785.0,715.0,1950.0,2945.0,520.0,1895.0,4750.0,725.0,420.0,1145.0,920.0,1250.0,2725.0,1035.0
1207,1208,Housing,Shelter costs,Owner one-family households without addition...,341670.0,4405.0,3115.0,2280.0,2925.0,4350.0,2010.0,1015.0,2660.0,2015.0,4100.0,570.0,4005.0,4010.0,1335.0,1050.0,1640.0,1805.0,1010.0,1785.0,1215.0,1640.0,1300.0,2805.0,1635.0,2870.0,1970.0,2630.0,2395.0,1735.0,3085.0,3110.0,3120.0,4395.0,3695.0,1190.0,3180.0,2365.0,2180.0,1260.0,2005.0,3975.0,1445.0,1945.0,1325.0,1675.0,3260.0,2200.0,2155.0,1015.0,2295.0,3320.0,2320.0,3520.0,1460.0,1900.0,1475.0,1705.0,1230.0,5115.0,1850.0,1875.0,2025.0,1020.0,2970.0,2130.0,1345.0,6245.0,2295.0,3135.0,3250.0,3560.0,1345.0,1390.0,5765.0,1315.0,2150.0,4200.0,3720.0,2455.0,875.0,1505.0,2825.0,2955.0,1305.0,1290.0,2705.0,2890.0,1915.0,1930.0,155.0,890.0,3050.0,2430.0,1725.0,1695.0,3500.0,1690.0,1120.0,2695.0,2560.0,190.0,1410.0,3170.0,1935.0,3585.0,7250.0,2205.0,1060.0,1545.0,535.0,3380.0,3235.0,4180.0,4380.0,3595.0,1325.0,4145.0,1360.0,225.0,2115.0,705.0,2050.0,2945.0,3675.0,4145.0,2380.0,1680.0,1765.0,4010.0,6835.0,2445.0,3305.0,6460.0,2075.0,1460.0,1830.0,1605.0,1455.0,2595.0,2100.0
1210,1211,Housing,Shelter costs,"Total number of non-farm, non-reserve private ...",979425.0,8710.0,6735.0,4535.0,14750.0,10955.0,5820.0,8750.0,6130.0,4615.0,8480.0,2510.0,9055.0,9055.0,7095.0,3140.0,5680.0,2440.0,5345.0,6090.0,6055.0,3545.0,4945.0,3920.0,15620.0,7120.0,5345.0,5475.0,5170.0,3910.0,6850.0,9390.0,8310.0,13340.0,12060.0,4975.0,8740.0,5735.0,7860.0,3130.0,8090.0,6650.0,3960.0,7525.0,5380.0,4775.0,9785.0,6055.0,3885.0,3995.0,10335.0,9015.0,3565.0,6450.0,4135.0,3830.0,4600.0,6345.0,4950.0,13210.0,5280.0,4105.0,6410.0,7650.0,7615.0,3310.0,3150.0,15075.0,5970.0,5440.0,5570.0,6495.0,4825.0,4365.0,12715.0,3630.0,4210.0,7365.0,12530.0,5615.0,5305.0,4595.0,9265.0,7190.0,14740.0,4810.0,5725.0,7570.0,8005.0,4940.0,8350.0,5165.0,8650.0,7120.0,3780.0,6060.0,12700.0,2925.0,3585.0,5460.0,3810.0,3635.0,3880.0,8775.0,6460.0,9935.0,12280.0,3765.0,3590.0,5420.0,9940.0,9750.0,6320.0,7570.0,10055.0,9480.0,5960.0,9120.0,3150.0,6415.0,6420.0,2540.0,7100.0,15695.0,9335.0,8960.0,9745.0,7010.0,4305.0,9880.0,17685.0,5445.0,7835.0,18065.0,5240.0,3450.0,5885.0,5230.0,6540.0,9545.0,5425.0
1211,1212,Housing,Shelter costs,"Tenant-occupied private non-farm, non-reserv...",446855.0,1605.0,1775.0,990.0,9400.0,4260.0,2770.0,5980.0,2145.0,1855.0,2665.0,1625.0,2890.0,2940.0,4690.0,1400.0,2880.0,130.0,3775.0,3420.0,3285.0,1120.0,3030.0,240.0,11155.0,2600.0,2475.0,1780.0,1655.0,1385.0,1940.0,4715.0,3115.0,6305.0,6485.0,2985.0,4060.0,2575.0,4275.0,1285.0,4675.0,940.0,1720.0,4175.0,3605.0,2165.0,4570.0,2385.0,820.0,2495.0,7025.0,3470.0,225.0,1470.0,1825.0,975.0,2160.0,3995.0,2930.0,5340.0,2370.0,1325.0,2860.0,5370.0,3255.0,540.0,1325.0,5215.0,2405.0,1400.0,1520.0,1740.0,2470.0,2205.0,3660.0,1680.0,990.0,1025.0,5605.0,2015.0,3105.0,2210.0,4815.0,2925.0,11900.0,2680.0,1760.0,3380.0,2935.0,2195.0,8045.0,3630.0,3945.0,3435.0,1095.0,3210.0,7665.0,500.0,1965.0,1360.0,550.0,3245.0,1750.0,3700.0,3565.0,4410.0,1640.0,735.0,2155.0,3010.0,9090.0,3915.0,2070.0,1265.0,3565.0,4165.0,3795.0,3310.0,1090.0,5835.0,2780.0,1415.0,3995.0,8135.0,3760.0,2450.0,6010.0,4355.0,1645.0,3695.0,5940.0,1635.0,3355.0,8210.0,2175.0,1035.0,3120.0,3095.0,4075.0,5340.0,2270.0
1215,1216,Housing,Shelter costs,"Owner-occupied private non-farm, non-reserve...",532575.0,7105.0,4945.0,3550.0,5340.0,6690.0,3050.0,2775.0,3985.0,2755.0,5825.0,885.0,6175.0,6125.0,2400.0,1735.0,2800.0,2310.0,1575.0,2670.0,2770.0,2425.0,1915.0,3680.0,4465.0,4525.0,2870.0,3700.0,3515.0,2525.0,4920.0,4665.0,5195.0,7030.0,5575.0,1985.0,4695.0,3160.0,3585.0,1840.0,3415.0,5710.0,2245.0,3355.0,1770.0,2610.0,5205.0,3670.0,3060.0,1500.0,3305.0,5550.0,3335.0,4960.0,2310.0,2860.0,2445.0,2345.0,2015.0,7875.0,2905.0,2785.0,3540.0,2270.0,4365.0,2780.0,1825.0,9855.0,3560.0,4040.0,4050.0,4755.0,2360.0,2155.0,9055.0,1950.0,3220.0,6345.0,6920.0,3600.0,2200.0,2385.0,4450.0,4265.0,2840.0,2130.0,3950.0,4195.0,5075.0,2745.0,305.0,1540.0,4700.0,3690.0,2685.0,2855.0,5030.0,2430.0,1620.0,4105.0,3250.0,395.0,2130.0,5080.0,2895.0,5535.0,10640.0,3025.0,1430.0,2405.0,850.0,5830.0,4245.0,6305.0,6490.0,5315.0,2160.0,5800.0,2065.0,570.0,3640.0,1125.0,3095.0,7560.0,5580.0,6505.0,3735.0,2650.0,2660.0,6170.0,11745.0,3805.0,4475.0,9865.0,3065.0,2415.0,2755.0,2135.0,2455.0,4215.0,3165.0
1216,1217,Housing,Shelter costs,Average value of dwelling $,413574.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
df_raw[df_raw["Attribute"].str.contains(
    "Population, 2006",
    case=False,
    na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
1,2,Population,Population,"Population, 2006 - 100% data",2503281.0,30156.0,21562.0,11656.0,27482.0,25439.0,14945.0,15325.0,15376.0,13298.0,21961.0,6526.0,25479.0,21652.0,21720.0,7765.0,14198.0,8205.0,11596.0,17318.0,11120.0,10281.0,9815.0,12450.0,24379.0,19850.0,13732.0,14531.0,14405.0,9576.0,16500.0,26644.0,24374.0,34737.0,32010.0,11811.0,20096.0,14453.0,22387.0,9437.0,21115.0,18533.0,10675.0,21287.0,12294.0,10842.0,30886.0,14705.0,10026.0,11288.0,20969.0,19984.0,12853.0,18327.0,10531.0,12766.0,14778.0,13925.0,13025.0,32823.0,13168.0,11231.0,17034.0,17102.0,21400.0,8780.0,7780.0,45862.0,14436.0,13749.0,14827.0,15988.0,12116.0,9625.0,44324.0,10271.0,10240.0,26272.0,24973.0,17202.0,15481.0,12835.0,32127.0,15210.0,23728.0,10652.0,15557.0,20489.0,14563.0,12428.0,17114.0,13368.0,21443.0,17740.0,9019.0,13777.0,33821.0,8729.0,7688.0,16615.0,10965.0,10387.0,10725.0,22389.0,14655.0,20600.0,43191.0,9557.0,10042.0,15590.0,21013.0,24424.0,17564.0,24696.0,23809.0,27235.0,15211.0,20416.0,9928.0,17949.0,16604.0,5906.0,17047.0,26015.0,25632.0,32252.0,24403.0,16476.0,12098.0,26644.0,41054.0,12517.0,20907.0,52461.0,11550.0,8051.0,14194.0,10497.0,11235.0,26140.0,14830.0

In [39]:
df_raw[df_raw["Attribute"].str.contains("labour", case=False, na=False)]

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
1297,1298,Labour,Labour force status,Total population 15 years and over by Labour f...,2067450.0,25280.0,18050.0,10010.0,24405.0,21495.0,12370.0,14110.0,13425.0,11340.0,17390.0,5010.0,20665.0,17875.0,16260.0,6280.0,12000.0,6200.0,9705.0,13520.0,9960.0,8395.0,8735.0,10160.0,22880.0,16035.0,11165.0,11975.0,12100.0,8010.0,14005.0,22215.0,18950.0,29575.0,26260.0,10255.0,16335.0,12320.0,17430.0,7265.0,15985.0,15505.0,8485.0,16685.0,10265.0,9185.0,23840.0,12395.0,8285.0,9135.0,18290.0,16700.0,10825.0,15980.0,8445.0,10170.0,11570.0,11710.0,10650.0,27350.0,10840.0,9240.0,13715.0,14900.0,17115.0,6960.0,6215.0,37990.0,12115.0,10770.0,11755.0,12550.0,10295.0,8105.0,34375.0,8450.0,8775.0,21940.0,21870.0,13485.0,7965.0,9895.0,24070.0,12765.0,21805.0,8750.0,13430.0,17640.0,13105.0,9640.0,14170.0,10320.0,18080.0,14420.0,7595.0,12525.0,27565.0,7110.0,6415.0,14280.0,9150.0,7415.0,8560.0,18235.0,12330.0,17735.0,33960.0,7810.0,7580.0,12010.0,16925.0,20530.0,14720.0,21280.0,19990.0,22375.0,11945.0,16815.0,7905.0,13255.0,14550.0,5025.0,13860.0,24100.0,20320.0,24895.0,21015.0,13135.0,9955.0,21950.0,36455.0,11110.0,17510.0,41560.0,9625.0,6875.0,11490.0,9105.0,10290.0,21405.0,12240.0
1298,1299,Labour,Labour force status,In the labour force,1344825.0,15715.0,11045.0,6625.0,17770.0,12935.0,7725.0,9840.0,8305.0,6710.0,11300.0,2995.0,12315.0,12105.0,9740.0,4090.0,7915.0,3730.0,6785.0,8655.0,7260.0,5585.0,6075.0,6885.0,17165.0,10020.0,7295.0,7495.0,7755.0,5490.0,9420.0,14215.0,12265.0,19640.0,16530.0,7130.0,11395.0,7960.0,10905.0,4610.0,9340.0,9575.0,5490.0,10085.0,7125.0,5930.0,13740.0,8380.0,5045.0,6195.0,13010.0,11675.0,7430.0,9520.0,4625.0,5890.0,7000.0,8745.0,6750.0,17515.0,7760.0,5950.0,8260.0,9340.0,10690.0,4525.0,4180.0,22730.0,8255.0,7720.0,7950.0,8430.0,6710.0,5790.0,23290.0,5060.0,5090.0,13810.0,15285.0,8560.0,5885.0,6635.0,15875.0,9255.0,16570.0,5965.0,7975.0,11050.0,10765.0,7215.0,9390.0,6315.0,11515.0,9060.0,4995.0,8995.0,18210.0,4570.0,4740.0,8790.0,5825.0,4010.0,5400.0,11120.0,8695.0,11715.0,24195.0,5595.0,4240.0,7170.0,10905.0,13710.0,9675.0,12705.0,13125.0,12925.0,7725.0,12805.0,4895.0,7680.0,9605.0,3600.0,8340.0,18880.0,12535.0,16535.0,13130.0,8545.0,6640.0,13255.0,22815.0,6420.0,10235.0,25160.0,6865.0,4540.0,7725.0,6730.0,7170.0,13440.0,7035.0
1301,1302,Labour,Labour force status,Not in the labour force,722620.0,9565.0,7010.0,3385.0,6635.0,8555.0,4645.0,4265.0,5115.0,4630.0,6090.0,2005.0,8350.0,5780.0,6525.0,2200.0,4075.0,2485.0,2920.0,4865.0,2700.0,2805.0,2660.0,3270.0,5715.0,6010.0,3865.0,4470.0,4335.0,2515.0,4580.0,7995.0,6690.0,9930.0,9735.0,3125.0,4935.0,4365.0,6520.0,2655.0,6655.0,5925.0,2995.0,6605.0,3135.0,3245.0,10095.0,4015.0,3235.0,2935.0,5275.0,5020.0,3390.0,6460.0,3825.0,4280.0,4565.0,2960.0,3910.0,9810.0,3080.0,3290.0,5450.0,5560.0,6420.0,2430.0,2040.0,15270.0,3850.0,3045.0,3805.0,4120.0,3585.0,2320.0,11090.0,3395.0,3685.0,8125.0,6580.0,4925.0,2085.0,3255.0,8175.0,3505.0,5230.0,2780.0,5455.0,6585.0,2335.0,2425.0,4775.0,4015.0,6565.0,5355.0,2600.0,3540.0,9350.0,2540.0,1675.0,5485.0,3325.0,3405.0,3170.0,7110.0,3635.0,6015.0,9765.0,2215.0,3330.0,4850.0,6015.0,6820.0,5045.0,8570.0,6860.0,9455.0,4225.0,4015.0,3005.0,5575.0,4950.0,1420.0,5520.0,5215.0,7775.0,8385.0,7890.0,4585.0,3310.0,8695.0,13630.0,4695.0,7275.0,16410.0,2765.0,2330.0,3765.0,2375.0,3115.0,7960.0,5195.0
1305,1306,Labour,Labour force status,Population 15 to 24 years - Labour force activity,317110.0,4325.0,2990.0,1385.0,3330.0,2570.0,1615.0,2380.0,2245.0,1975.0,2565.0,935.0,3290.0,2400.0,3385.0,885.0,1705.0,1255.0,1055.0,2465.0,1075.0,1450.0,1080.0,1875.0,3330.0,2435.0,1585.0,1850.0,1855.0,1065.0,1620.0,3365.0,2805.0,4870.0,3905.0,1475.0,2300.0,2045.0,3070.0,1270.0,2520.0,2375.0,1345.0,2820.0,1595.0,1540.0,4215.0,1745.0,1070.0,1615.0,2245.0,1815.0,2205.0,2890.0,1045.0,1545.0,1975.0,1635.0,1560.0,3870.0,1605.0,1415.0,2020.0,2970.0,2825.0,915.0,890.0,6205.0,1775.0,1370.0,2025.0,1700.0,1450.0,1075.0,6720.0,1075.0,1155.0,3830.0,2315.0,2610.0,860.0,1870.0,4685.0,1430.0,2285.0,1255.0,2475.0,2950.0,1170.0,1120.0,2190.0,1655.0,2490.0,2095.0,900.0,1745.0,4515.0,1005.0,745.0,2155.0,1600.0,1715.0,1265.0,2890.0,1430.0,2075.0,6635.0,1000.0,1215.0,2245.0,2275.0,2870.0,2785.0,3680.0,2360.0,3215.0,1710.0,2010.0,1285.0,2015.0,2065.0,1105.0,1855.0,2465.0,3655.0,4585.0,3605.0,2045.0,1745.0,3200.0,6460.0,1530.0,2545.0,6760.0,1110.0,890.0,1615.0,1150.0,890.0,4240.0,1675.0
1306,1307,Labour,Labour force status,In the labour force,178105.0,2310.0,1480.0,935.0,2190.0,1230.0,920.0,1300.0,990.0,920.0,1145.0,515.0,1855.0,1405.0,1805.0,395.0,1055.0,495.0,630.0,1365.0,800.0,965.0,635.0,1145.0,2435.0,1240.0,795.0,1120.0,1235.0,685.0,955.0,1760.0,1585.0,2975.0,2445.0,980.0,1195.0,1085.0,1630.0,655.0,1120.0,1365.0,805.0,1390.0,780.0,605.0,2190.0,1095.0,655.0,850.0,1340.0,1115.0,1365.0,1360.0,600.0,905.0,1030.0,1010.0,945.0,2445.0,995.0,930.0,1070.0,1715.0,1705.0,480.0,500.0,3210.0,985.0,790.0,890.0,930.0,950.0,740.0,3620.0,640.0,710.0,1935.0,1445.0,1430.0,590.0,1110.0,2620.0,915.0,1525.0,805.0,1235.0,1715.0,760.0,685.0,1340.0,925.0,1385.0,1195.0,525.0,1225.0,2635.0,655.0,485.0,1125.0,890.0,675.0,815.0,1815.0,915.0,1060.0,3715.0,610.0,675.0,1280.0,1190.0,1515.0,1250.0,1685.0,1340.0,1455.0,830.0,1225.0,740.0,925.0,1325.0,765.0,1020.0,1710.0,2060.0,2545.0,2230.0,1290.0,1115.0,1800.0,2700.0,945.0,1585.0,3330.0,655.0,445.0,1060.0,675.0,495.0,2480.0,1045.0
1309,1310,Labour,Labour force status,Not in the labour force,139000.0,2005.0,1500.0,455.0,1140.0,1340.0,685.0,1080.0,1255.0,1060.0,1420.0,415.0,1420.0,985.0,1570.0,485.0,650.0,765.0,425.0,1090.0,275.0,490.0,440.0,730.0,890.0,1200.0,790.0,735.0,625.0,390.0,665.0,1590.0,1220.0,1900.0,1445.0,495.0,1090.0,960.0,1435.0,610.0,1390.0,1010.0,530.0,1435.0,810.0,940.0,2035.0,640.0,415.0,755.0,905.0,690.0,840.0,1520.0,445.0,640.0,950.0,625.0,615.0,1430.0,610.0,485.0,960.0,1255.0,1110.0,435.0,390.0,2985.0,795.0,585.0,1125.0,760.0,495.0,340.0,3100.0,430.0,445.0,1900.0,855.0,1175.0,275.0,750.0,2060.0,505.0,750.0,455.0,1240.0,1225.0,410.0,430.0,850.0,745.0,1105.0,905.0,375.0,510.0,1885.0,340.0,255.0,1035.0,715.0,1035.0,450.0,1070.0,520.0,1025.0,2920.0,395.0,540.0,970.0,1080.0,1360.0,1530.0,1980.0,1015.0,1750.0,880.0,785.0,545.0,1090.0,740.0,335.0,830.0,750.0,1595.0,2025.0,1390.0,760.0,630.0,1420.0,3760.0,585.0,940.0,3440.0,455.0,440.0,550.0,475.0,390.0,1750.0,625.0
1313,1314,Labour,Labour force status,Population 25 years and over - Labour force ac...,1750345.0,20960.0,15070.0,8620.0,21080.0,18915.0,10755.0,11735.0,11180.0,9355.0,14815.0,4070.0,17380.0,15480.0,12880.0,5395.0,10295.0,4950.0,8650.0,11055.0,8890.0,6945.0,7655.0,8285.0,19555.0,13595.0,9580.0,10120.0,10230.0,6940.0,12385.0,18850.0,16140.0,24700.0,22360.0,8780.0,14035.0,10275.0,14350.0,5995.0,13475.0,13125.0,7140.0,13870.0,8665.0,7635.0,19620.0,10645.0,7210.0,7530.0,16040.0,14880.0,8615.0,13100.0,7405.0,8625.0,9595.0,10065.0,9095.0,23455.0,9230.0,7820.0,11690.0,11930.0,14285.0,6035.0,5320.0,31790.0,10335.0,9390.0,9730.0,10850.0,8850.0,7030.0,27640.0,7375.0,7625.0,18110.0,19565.0,10870.0,7100.0,8030.0,19385.0,11335.0,19525.0,7495.0,10950.0,14695.0,11925.0,8520.0,11980.0,8665.0,15585.0,12310.0,6700.0,10790.0,23050.0,6105.0,5665.0,12115.0,7545.0,5700.0,7300.0,15335.0,10890.0,15640.0,27325.0,6810.0,6360.0,9760.0,14640.0,17660.0,11935.0,17600.0,17635.0,19170.0,10235.0,14795.0,6620.0,11240.0,12480.0,3925.0,12000.0,21640.0,16660.0,20310.0,17405.0,11090.0,8215.0,18740.0,29990.0,9580.0,14980.0,34805.0,8520.0,5985.0,9875.0,7965.0,9395.0,17170.0,10560.0
1314,1315,Labour,Labour force status,In the labour force,1166720.0,13420.0,9555.0,5690.0,15585.0,11705.0,6805.0,8545.0,7315.0,5790.0,10160.0,2485.0,10455.0,10695.0,7940.0,3685.0,6860.0,3230.0,6150.0,7295.0,6460.0,4625.0,5430.0,5745.0,14725.0,8775.0,6505.0,6380.0,6515.0,4810.0,8465.0,12455.0,10665.0,16655.0,14085.0,6155.0,10195.0,6870.0,9265.0,3955.0,8215.0,8205.0,4675.0,8695.0,6340.0,5330.0,11540.0,7280.0,4395.0,5350.0,11670.0,10565.0,6070.0,8160.0,4020.0,4985.0,5975.0,7730.0,5800.0,15075.0,6760.0,5020.0,7190.0,7630.0,8975.0,4045.0,3670.0,19505.0,7275.0,6925.0,7055.0,7495.0,5760.0,5060.0,19655.0,4410.0,4375.0,11870.0,13845.0,7130.0,5295.0,5520.0,13265.0,8335.0,15040.0,5160.0,6740.0,9340.0,10005.0,6530.0,8050.0,5400.0,10130.0,7870.0,4470.0,7770.0,15580.0,3910.0,4250.0,7660.0,4930.0,3325.0,4580.0,9305.0,7785.0,10660.0,20480.0,4985.0,3575.0,5880.0,9710.0,12205.0,8425.0,11015.0,11785.0,11465.0,6890.0,11575.0,4160.0,6755.0,8270.0,2840.0,7315.0,17175.0,10475.0,13970.0,10900.0,7250.0,5535.0,11455.0,20105.0,5475.0,8645.0,21830.0,6215.0,4100.0,6660.0,6060.0,6665.0,10960.0,5990.0
1317,1318,Labour,Labour force status,Not in the labour force,583620.0,7545.0,5505.0,2930.0,5495.0,7210.0,3950.0,3180.0,3860.0,3570.0,4660.0,1590.0,6925.0,4780.0,4940.0,1710.0,3435.0,1720.0,2500.0,3770.0,2425.0,2315.0,2225.0,2535.0,4825.0,4820.0,3075.0,3740.0,3710.0,2125.0,3920.0,6395.0,5470.0,8035.0,8280.0,2625.0,3840.0,3410.0,5090.0,2045.0,5250.0,4915.0,2460.0,5170.0,2325.0,2315.0,8065.0,3365.0,2815.0,2175.0,4370.0,4320.0,2550.0,4935.0,3375.0,3635.0,3625.0,2335.0,3295.0,8385.0,2465.0,2795.0,4490.0,4300.0,5305.0,1995.0,1650.0,12285.0,3055.0,2450.0,2670.0,3360.0,3090.0,1980.0,7980.0,2960.0,3240.0,6240.0,5715.0,3745.0,1805.0,2505.0,6115.0,3000.0,4485.0,2330.0,4215.0,5350.0,1915.0,1995.0,3925.0,3265.0,5450.0,4440.0,2225.0,3015.0,7460.0,2195.0,1410.0,4465.0,2610.0,2370.0,2715.0,6040.0,3115.0,4990.0,6860.0,1820.0,2790.0,3880.0,4925.0,5445.0,3520.0,6575.0,5845.0,7700.0,3345.0,3220.0,2455.0,4475.0,4200.0,1080.0,4695.0,4470.0,6180.0,6335.0,6505.0,3830.0,2675.0,7280.0,9865.0,4105.0,6325.0,12960.0,2310.0,1885.0,3205.0,1900.0,2730.0,6195.0,4570.0
1321,1322,Labour,Class of worker,Total labour force 15 years and over by class ...,1344830.0,15720.0,11035.0,6625.0,17770.0,12935.0,7725.0,9845.0,8310.0,6710.0,11305.0,3000.0,12315.0,12105.0,9745.0,4085.0,7920.0,3730.0,6785.0,8660.0,7265.0,5590.0,6075.0,6885.0,17155.0,10020.0,7300.0,7500.0,7765.0,5505.0,9420.0,14215.0,12255.0,19645.0,16535.0,7135.0,11395.0,7955.0,10900.0,4610.0,9340.0,9575.0,5485.0,10080.0,7125.0,5930.0,13735.0,8380.0,5045.0,6195.0,13000.0,11685.0,7430.0,9515.0,4625.0,5890.0,7000.0,8740.0,6745.0,17520.0,7760.0,5950.0,8255.0,9340.0,10690.0,4530.0,4180.0,22715.0,8255.0,7715.0,7950.0,8425.0,6710.0,5795.0,23285.0,5055.0,5085.0,13810.0,15285.0,8560.0,5880.0,6640.0,15880.0,9255.0,16575.0,5965.0,7980.0,11060.0,10770.0,7225.0,9390.0,6310.0,11520.0,9065.0,4995.0,8990.0,18220.0,4570.0,4735.0,8785.0,5830.0,4010.0,5400.0,11115.0,8695.0,11710.0,24200.0,5595.0,4245.0,7165.0,10910.0,13715.0,9675.0,12715.0,13130.0,12930.0,7720.0,12795.0,4900.0,7680.0,9605.0,3605.0,8335.0,18880.0,12540.0,16520.0,13130.0,8545.0,6645.0,13240.0,22815.0,6420.0,10240.0,25160.0,6865.0,4545.0,7725.0,6730.0,7170.0,13435.0,7035.0
1333,1334,Labour,Occupation - National Occupational Classificat...,Total labour force 15 years and over by occupa...,1344825.0,15720.0,11040.0,6620.0,17770.0,12940.0,7725.0,9845.0,8305.0,6715.0,11300.0,3000.0,12310.0,12105.0,9740.0,4080.0,7920.0,3725.0,6785.0,8660.0,7265.0,5585.0,6075.0,6885.0,17155.0,10020.0,7295.0,7495.0,7760.0,5500.0,9415.0,14220.0,12260.0,19645.0,16535.0,7135.0,11400.0,7960.0,10910.0,4605.0,9340.0,9570.0,5485.0,10085.0,7125.0,5930.0,13740.0,8380.0,5045.0,6195.0,13010.0,11675.0,7435.0,9515.0,4620.0,5890.0,7000.0,8745.0,6740.0,17515.0,7765.0,5950.0,8255.0,9345.0,10695.0,4540.0,4180.0,22725.0,8255.0,7715.0,7955.0,8425.0,6715.0,5790.0,23285.0,5055.0,5090.0,13810.0,15285.0,8560.0,5880.0,6635.0,15885.0,9255.0,16570.0,5965.0,7975.0,11055.0,10765.0,7215.0,9390.0,6310.0,11530.0,9070.0,4995.0,9000.0,18210.0,4570.0,4740.0,8785.0,5820.0,4005.0,5400.0,11125.0,8695.0,11705.0,24185.0,5595.0,4240.0,7165.0,10900.0,13715.0,9680.0,12700.0,13130.0,12925.0,7720.0,12800.0,4905.0,7685.0,9595.0,3605.0,8330.0,18880.0,12535.0,16520.0,13125.0,8540.0,6645.0,13245.0,22815.0,6420.0,10235.0,25150.0,6870.0,4545.0,7725.0,6735.0,7170.0,13440.0,7045.0
1382,1383,Labour,Occupation - National Occupational Classificat...,H7 Transportation equipment operators an...,30050.0,265.0,225.0,305.0,130.0,155.0,170.0,70.0,80.0,70.0,75.0,130.0,375.0,415.0,335.0,50.0,200.0,0.0,190.0,370.0,90.0,135.0,35.0,95.0,105.0,410.0,185.0,185.0,185.0,85.0,225.0,200.0,315.0,325.0,495.0,110.0,265.0,170.0,390.0,210.0,205.0,275.0,240.0,270.0,65.0,20.0,435.0,170.0,100.0,85.0,135.0,140.0,140.0,130.0,110.0,225.0,335.0,95.0,200.0,430.0,80.0,185.0,405.0,70.0,615.0,0.0,75.0,480.0,145.0,20.0,20.0,50.0,125.0,290.0,820.0,145.0,125.0,190.0,370.0,255.0,100.0,245.0,780.0,40.0,125.0,240.0,110.0,325.0,80.0,85.0,230.0,345.0,225.0,280.0,110.0,80.0,365.0,190.0,50.0,145.0,60.0,145.0,195.0,340.0,130.0,20.0,605.0,50.0,135.0,225.0,275.0,165.0,50.0,170.0,435.0,325.0,365.0,55.0,175.0,445.0,95.0,45.0,260.0,155.0,330.0,890.0,350.0,360.0,210.0,345.0,165.0,100.0,310.0,615.0,130.0,110.0,90.0,10.0,25.0,275.0,165.0
1383,1384,Labour,Occupation - National Occupational Classificat...,"H8 Trades helpers, construction and tran...",27270.0,330.0,175.0,175.0,125.0,120.0,105.0,20.0,90.0,35.0,110.0,145.0,260.0,185.0,350.0,40.0,265.0,20.0,135.0,385.0,50.0,330.0,0.0,110.0,115.0,290.0,135.0,155.0,540.0,70.0,190.0,150.0,335.0,815.0,650.0,280.0,205.0,115.0,260.0,125.0,135.0,130.0,215.0,200.0,70.0,35.0,485.0,130.0,60.0,80.0,95.0,85.0,140.0,75.0,90.0,205.0,345.0,75.0,200.0,275.0,170.0,345.0,230.0,70.0,285.0,25.0,110.0,475.0,45.0,10.0,45.0,40.0,265.0,110.0,620.0,225.0,80.0,255.0,340.0,160.0,60.0,295.0,710.0,30.0,70.0,175.0,80.0,185.0,95.0,60.0,155.0,135.0,390.0,175.0,65.0,150.0,265.0,185.0,40.0,195.0,60.0,85.0,195.0,525.0,140.0,25.0,430.0,75.0,140.0,145.0,265.0,260.0,95.0,155.0,210.0,215.0,160.0,95.0,250.0,70.0,265.0,10.0,145.0,130.0,330.0,485.0,305.0,345.0,445.0,250.0,140.0,45.0,215.0,595.0,80.0,95.0,120.0,50.0,25.0,505.0,230.0
1385,1386,Labour,Occupation - National Occupational Classificat...,"I0 Occupations unique to agriculture, ex...",1990.0,0.0,0.0,30.0,15.0,10.0,20.0,15.0,0.0,25.0,10.0,0.0,10.0,10.0,10.0,0.0,10.0,20.0,0.0,10.0,0.0,0.0,0.0,10.0,60.0,0.0,0.0,20.0,10.0,0.0,25.0,30.0,20.0,0.0,10.0,0.0,10.0,10.0,10.0,10.0,25.0,20.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,15.0,0.0,10.0,0.0,35.0,0.0,0.0,15.0,25.0,25.0,0.0,40.0,35.0,0.0,0.0,45.0,10.0,10.0,10.0,15.0,0.0,0.0,20.0,10.0,10.0,10.0,45.0,0.0,15.0,0.0,90.0,10.0,10.0,30.0,10.0,40.0,0.0,10.0,0.0,20.0,0.0,0.0,10.0,20.0,25.0,10.0,15.0,30.0,30.0,10.0,0.0,20.0,20.0,0.0,50.0,0.0,10.0,20.0,0.0,45.0,35.0,30.0,20.0,0.0,0.0,10.0,0.0,0.0,45.0,0.0,10.0,0.0,10.0,60.0,10.0,10.0,10.0,20.0,30.0,0.0,20.0,20.0,15.0,10.0,30.0,0.0,0.0,0.0,20.0
1386,1387,Labour,Occupation - National Occupational Classificat...,I1 Occupations unique to forestry operat...,235.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,20.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,10.0,0.0,0.0,10.0,10.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,10.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,10.0,0.0,10.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1387,1388,Labour,Occupation - National Occupational Classificat...,I2 Primary production labourers,5590.0,45.0,65.0,35.0,45.0,45.0,40.0,20.0,20.0,20.0,25.0,25.0,35.0,50.0,60.0,10.0,75.0,0.0,45.0,10.0,40.0,65.0,20.0,45.0,40.0,50.0,10.0,75.0,30.0,10.0,10.0,25.0,20.0,195.0,110.0,45.0,35.0,60.0,60.0,10.0,40.0,20.0,30.0,10.0,25.0,45.0,40.0,35.0,15.0,10.0,60.0,25.0,30.0,20.0,25.0,45.0,20.0,10.0,10.0,50.0,65.0,50.0,35.0,35.0,55.0,30.0,40.0,85.0,40.0,40.0,10.0,70.0,40.0,0.0,65.0,10.0,20.0,30.0,65.0,40.0,0.0,50.0,95.0,55.0,10.0,30.0,20.0,40.0,25.0,25.0,25.0,20.0,105.0,50.0,10.0,20.0,80.0,40.0,10.0,25.0,45.0,10.0,30.0,75.0,20.0,35.0,85.0,10.0,10.0,65.0,40.0,45.0,35.0,10.0,75.0,10.0,50.0,45.0,40.0,30.0,140.0,15.0,20.0,20.0,80.0,50.0,10.0,25.0,85.0,110.0,50.0,20.0,60.0,95.0,25.0,35.0,50.0,20.0,20.0,40.0,25.0
1392,1393,Labour,Occupation - National Occupational Classificat...,"J3 Labourers in processing, manufacturin...",24855.0,480.0,480.0,105.0,25.0,70.0,50.0,0.0,40.0,55.0,25.0,55.0,315.0,25.0,595.0,45.0,190.0,55.0,35.0,390.0,35.0,120.0,0.0,65.0,65.0,215.0,75.0,85.0,115.0,45.0,40.0,170.0,365.0,285.0,485.0,65.0,70.0,50.0,315.0,110.0,95.0,135.0,140.0,185.0,30.0,15.0,770.0,145.0,65.0,70.0,70.0,20.0,155.0,125.0,65.0,390.0,430.0,35.0,225.0,155.0,95.0,220.0,295.0,175.0,270.0,0.0,40.0,735.0,45.0,0.0,0.0,10.0,75.0,115.0,985.0,140.0,30.0,455.0,170.0,230.0,25.0,295.0,1100.0,0.0,20.0,120.0,10.0,115.0,50.0,55.0,195.0,180.0,180.0,180.0,30.0,80.0,170.0,60.0,10.0,125.0,45.0,60.0,195.0,350.0,185.0,0.0,585.0,20.0,105.0,335.0,300.0,240.0,35.0,300.0,100.0,290.0,135.0,30.0,210.0,125.0,190.0,0.0,155.0,35.0,320.0,1020.0,210.0,195.0,125.0,235.0,100.0,10.0,200.0,1190.0,25.0,70.0,85.0,20.0,10.0,380.0,155.0

| Final ML Variable           |        2006        | 2016 |   Use in Model  | Reason                           |
| --------------------------- | :----------------: | :--: | :-------------: | -------------------------------- |
| Population                  |          ✅         |   ✅  |        ✅        | Population size                  |
| Median Income               |          ✅         |   ✅  |        ✅        | Income level                     |
| Median After-Tax Income     |          ✅         |   ✅  |        ✅        | Disposable income                |
| Employment Rate             |          ✅         |   ✅  |        ✅        | Labour market                    |
| Participation Rate          |          ✅         |   ✅  |        ✅        | Labour force participation       |
| Unemployment Rate           | ✅ *(if available)* |   ✅  |        ✅        | Strong socioeconomic predictor   |
| Bachelor's Degree           |          ✅         |   ✅  |        ✅        | Education level                  |
| Immigrant Population        |          ✅         |   ✅  |        ✅        | Demographic characteristic       |
| Visible Minority Population |          ✅         |   ✅  |        ✅        | Demographic characteristic       |
| Housing Indicator           |          ✅         |   ✅  |        ✅        | Housing affordability/conditions |
| Renters                     | ✅ *(if available)* |   ✅  |        ✅        | Housing tenure                   |
| No Diploma                  | ✅ *(if available)* |   ✅  |        ✅        | Educational disadvantage         |
| Low Income (Target)         |          ❌         |   ✅  | **Target only** | Outcome variable from 2016       |

The 2006 Toronto Neighbourhood Profile does not provide neighbourhood-level low-income prevalence percentages. Therefore, low-income measures from the 2006 dataset will not be used as predictor variables. Instead, socioeconomic indicators from 2006 will serve as the predictor variables (X), while the 2016 neighbourhood low-income prevalence will be used as the target variable (y) during predictive modelling.

### Section 6 – Candidate Feature Identification

Based on the feature mapping completed in the previous section, only the selected socioeconomic indicators will be extracted from the raw 2006 Toronto Neighbourhood Profile dataset.

These indicators were selected because they are available in both the 2006 and 2016 datasets and represent key socioeconomic characteristics related to neighbourhood vulnerability.

The extracted variables will later be transformed into a machine-learning-ready dataset for predictive modelling.

In [41]:
feature_search = {
    "Population": "Population",
    "Median_Income": "Median income",
    "Median_AfterTax_Income": "Median after-tax income",
    "Employment_Rate": "Employment rate",
    "Participation_Rate": "Participation rate",
    "Unemployment_Rate": "Unemployment rate",
    "Bachelors_Degree": "Bachelor",
    "No_Diploma": "No certificate",
    "Immigrant_Population": "Immigrant",
    "Visible_Minority": "Visible minority",
    "Renters": "Renter",
    "Housing": "Housing"}

In [43]:
for feature, keyword in feature_search.items():
    print("=" * 60)
    print(feature)
    print(df_raw[df_raw["Attribute"].str.contains(keyword,
                                                 case=False,
                                                 na=False)][
        ["Category","Topic","Attribute"]])

============================================================
Population
                                     Category  \
0                                  Population
1                                  Population
2                                  Population
27                                 Population
140   Families, households and marital status
146   Families, households and marital status
197                                  Language
202                                  Language
209                                  Language
312                                  Language
508                                    Income
530                                    Income
551                                    Income
796               Immigration and citizenship
801               Immigration and citizenship
810               Immigration and citizenship
816               Immigration and citizenship
887               Immigration and citizenship
891                        Aboriginal Peoples
892                        Aboriginal Peoples
898                        Aboriginal Peoples
899                        Aboriginal Peoples
902                   Ethnocultural diversity
903                   Ethnocultural diversity
917                   Ethnocultural diversity
1226                                Education
1240                                Education
1254                                Education
1268                                Education
1281                                Education
1297                                   Labour
1305                                   Labour
1313                                   Labour
1434                         Language of work

                                                  Topic  \
0                                            Population
1                                            Population
2                                            Population
27                                  Age characteristics
140                                      Marital status
146                                      Marital status
197                     Knowledge of official languages
202                      First official language spoken
209                                       Mother tongue
312                  Language spoken most often at home
508                               Income of individuals
530                               Income of individuals
551                               Income of individuals
796                                         Citizenship
801          Immigrant status and period of immigration
810                                  Age at immigration
816               Immigrants by selected place of birth
887                                   Generation status
891                                 Aboriginal identity
892                                 Aboriginal identity
898                                 Aboriginal identity
899                               Aboriginal population
902                         Visible minority population
903                         Visible minority population
917                            Ethnic origin population
1226             Highest certificate, diploma or degree
1240             Highest certificate, diploma or degree
1254             Highest certificate, diploma or degree
1268  Major field of study - Classification of Instr...
1281  Location of study compared with province or te...
1297                                Labour force status
1305                                Labour force status
1313                                Labour force status
1434                   Language used most often at work

                                              Attribute
0                          Population, 2001 - 100% data
1                          Population, 2006 - 100% data
2            Population percentage change, 2001 to 2006
27    Total population by sex and age groups - 100% ...
140   Total population 15 years and over by legal ma...
146   Total population 15 years and over by common-l...
197   Total population by knowledge of official lang...
202   Total population by first official language sp...
209   Total population by mother tongue - 20% sample...
312   Total population by language spoken most often...
508   Total income in 2005 of population 15 years an...
530   Total after-tax income in 2005 of population 1...
551   Total population 15 years and over with employ...
796   Total population by citizenship - 20% sample data
801   Total immigrant population by period of immigr...
810   Total immigrant population by age at immigrati...
816   Total population by immigrant status and place...
887   Total population 15 years and older by generat...
891   Total population by Aboriginal and non-Aborigi...
892                Total Aboriginal identity population
898                  Non-Aboriginal identity population
899   Total population by Registered Indian status -...
902   Total population by visible minority groups - ...
903                   Total visible minority population
917   Total population by ethnic origin - 20% sample...
1226  Total population 15 to 24 years by highest cer...
1240  Total population 25 to 64 years by highest cer...
1254  Total population 65 years and over by highest ...
1268  Total population 25 to 64 years with postsecon...
1281  Total population 25 to 64 years with postsecon...
1297  Total population 15 years and over by Labour f...
1305  Population 15 to 24 years - Labour force activity
1313  Population 25 years and over - Labour force ac...
1434  Total population 15 years and over who worked ...
============================================================
Median_Income
    Category                  Topic          Attribute
527   Income  Income of individuals    Median income $
740   Income     Income of families    Median income $
============================================================
Median_AfterTax_Income
    Category                  Topic                    Attribute
548   Income  Income of individuals    Median after-tax income $
763   Income     Income of families    Median after-tax income $
============================================================
Employment_Rate
     Category                Topic          Attribute
1303   Labour  Labour force status    Employment rate
1304   Labour  Labour force status  Unemployment rate
1311   Labour  Labour force status    Employment rate
1312   Labour  Labour force status  Unemployment rate
1319   Labour  Labour force status    Employment rate
1320   Labour  Labour force status  Unemployment rate
============================================================
Participation_Rate
     Category                Topic           Attribute
1302   Labour  Labour force status  Participation rate
1310   Labour  Labour force status  Participation rate
1318   Labour  Labour force status  Participation rate
============================================================
Unemployment_Rate
     Category                Topic          Attribute
1304   Labour  Labour force status  Unemployment rate
1312   Labour  Labour force status  Unemployment rate
1320   Labour  Labour force status  Unemployment rate
============================================================
Bachelors_Degree
       Category                                   Topic  \
1233  Education  Highest certificate, diploma or degree
1235  Education  Highest certificate, diploma or degree
1236  Education  Highest certificate, diploma or degree
1247  Education  Highest certificate, diploma or degree
1249  Education  Highest certificate, diploma or degree
1250  Education  Highest certificate, diploma or degree
1261  Education  Highest certificate, diploma or degree
1263  Education  Highest certificate, diploma or degree
1264  Education  Highest certificate, diploma or degree

                                              Attribute
1233        University certificate or diploma below ...
1235                                  Bachelor's degree
1236          University certificate or diploma abov...
1247        University certificate or diploma below ...
1249                                  Bachelor's degree
1250          University certificate or diploma abov...
1261        University certificate or diploma below ...
1263                                  Bachelor's degree
1264          University certificate or diploma abov...
============================================================
No_Diploma
       Category                                   Topic  \
1227  Education  Highest certificate, diploma or degree
1241  Education  Highest certificate, diploma or degree
1255  Education  Highest certificate, diploma or degree

                                Attribute
1227    No certificate, diploma or degree
1241    No certificate, diploma or degree
1255    No certificate, diploma or degree
============================================================
Immigrant_Population
                        Category  \
801  Immigration and citizenship
810  Immigration and citizenship
816  Immigration and citizenship
817  Immigration and citizenship
820  Immigration and citizenship
854  Immigration and citizenship

                                            Topic  \
801    Immigrant status and period of immigration
810                            Age at immigration
816         Immigrants by selected place of birth
817         Immigrants by selected place of birth
820         Immigrants by selected place of birth
854  Recent immigrants by selected place of birth

                                             Attribute
801  Total immigrant population by period of immigr...
810  Total immigrant population by age at immigrati...
816  Total population by immigrant status and place...
817                                     Non-immigrants
820                                         Immigrants
854  Total recent immigrants by selected places of ...
============================================================
Visible_Minority
                    Category                        Topic  \
902  Ethnocultural diversity  Visible minority population
903  Ethnocultural diversity  Visible minority population
914  Ethnocultural diversity  Visible minority population
915  Ethnocultural diversity  Visible minority population
916  Ethnocultural diversity  Visible minority population

                                             Attribute
902  Total population by visible minority groups - ...
903                  Total visible minority population
914                           Visible minority, n.i.e.
915                          Multiple visible minority
916                             Not a visible minority
============================================================
Renters
Empty DataFrame
Columns: [Category, Topic, Attribute]
Index: []
============================================================
Housing
     Category                                              Topic  \
1173  Housing                                     Housing tenure
1176  Housing                                     Housing tenure
1403   Labour  Industry - North American Industry Classificat...

                                              Attribute
1173  Total number of occupied private dwellings by ...
1176                                       Band housing
1403               48-49 Transportation and warehousing

### Section 7 – Final Feature Mapping

After reviewing all candidate variables, the final socioeconomic indicators were selected.

Unlike the 2016 notebook, the variables are identified using their attribute names rather than fixed row numbers. This improves reproducibility because the notebook will continue to work even if future dataset versions change the row order.

These variables will be extracted and transformed into the machine-learning-ready dataset.

In [44]:
selected_attributes = {

    "Population":
        "Population, 2006 - 100% data",

    "Median_AfterTax_Income":
        "Median after-tax income $",

    "Employment_Rate":
        "Employment rate",

    "Participation_Rate":
        "Participation rate",

    "Unemployment_Rate":
        "Unemployment rate",

    "Bachelors_Degree":
        "Bachelor's degree",

    "Immigrant_Population":
        "Total immigrant population",

    "Visible_Minority":
        "Total visible minority population",

    "Housing":
        "Core housing need",}

In [45]:
for variable, attribute in selected_attributes.items():

    print("="*70)
    print(variable)

    result = df_raw[
        df_raw["Attribute"] == attribute ]

    print(result[["Category","Topic","Attribute"]])

======================================================================
Population
     Category       Topic                     Attribute
1  Population  Population  Population, 2006 - 100% data
======================================================================
Median_AfterTax_Income
    Category               Topic                  Attribute
763   Income  Income of families  Median after-tax income $
======================================================================
Employment_Rate
     Category                Topic        Attribute
1303   Labour  Labour force status  Employment rate
1311   Labour  Labour force status  Employment rate
1319   Labour  Labour force status  Employment rate
======================================================================
Participation_Rate
     Category                Topic           Attribute
1302   Labour  Labour force status  Participation rate
1310   Labour  Labour force status  Participation rate
1318   Labour  Labour force status  Participation rate
======================================================================
Unemployment_Rate
     Category                Topic          Attribute
1304   Labour  Labour force status  Unemployment rate
1312   Labour  Labour force status  Unemployment rate
1320   Labour  Labour force status  Unemployment rate
======================================================================
Bachelors_Degree
Empty DataFrame
Columns: [Category, Topic, Attribute]
Index: []
======================================================================
Immigrant_Population
Empty DataFrame
Columns: [Category, Topic, Attribute]
Index: []
======================================================================
Visible_Minority
Empty DataFrame
Columns: [Category, Topic, Attribute]
Index: []
======================================================================
Housing
Empty DataFrame
Columns: [Category, Topic, Attribute]
Index: []

In [56]:
feature_mapping = pd.DataFrame({
    "Variable": [
        "Population",
        "Median_AfterTax_Income",
        "Participation_Rate",
        "Employment_Rate",
        "Unemployment_Rate",
        "Bachelors_Degree",
        "Immigrant_Population",
        "Visible_Minority",
        "Rented_Dwellings" ],
    "Row": [
        1,
        763,
        1302,
        1303,
        1304,
        1235,
        801,
        903,
        1175],
    "Reason": [
        "Overall neighbourhood population",
        "Income predictor",
        "Overall labour participation",
        "Overall employment",
        "Overall unemployment",
        "Education",
        "Immigration",
        "Ethnocultural diversity",
        "Housing tenure proxy" ]})

feature_mapping

                 Variable   Row                            Reason
0              Population     1  Overall neighbourhood population
1  Median_AfterTax_Income   763                  Income predictor
2      Participation_Rate  1302      Overall labour participation
3         Employment_Rate  1303                Overall employment
4       Unemployment_Rate  1304              Overall unemployment
5        Bachelors_Degree  1235                         Education
6    Immigrant_Population   801                       Immigration
7        Visible_Minority   903           Ethnocultural diversity
8        Rented_Dwellings  1175              Housing tenure proxy

### Section 8 – Extract Selected Variables

Using the finalized feature mapping developed in the previous section, the selected socioeconomic indicators are extracted from the raw 2006 Toronto Neighbourhood Profile dataset.

Only variables that are available at the neighbourhood level and are comparable with the 2016 dataset are retained. These variables will form the basis of the machine-learning-ready dataset used in the predictive modelling phase.

In [60]:
selected_rows = {
    "Population": 1,
    "Median_AfterTax_Income": 763,
    "Participation_Rate": 1302,
    "Employment_Rate": 1303,
    "Unemployment_Rate": 1304,
    "Bachelors_Degree": 1235,
    "Immigrant_Population": 801,
    "Visible_Minority": 903,
    # "Rented_Dwellings": 1175
}

In [61]:
selected_rows

{'Population': 1,
 'Median_AfterTax_Income': 763,
 'Participation_Rate': 1302,
 'Employment_Rate': 1303,
 'Unemployment_Rate': 1304,
 'Bachelors_Degree': 1235,
 'Immigrant_Population': 801,
 'Visible_Minority': 903}

In [62]:
selected_df = df_raw.loc[list(selected_rows.values())].copy()

selected_df

,_id,Category,Topic,Attribute,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
1,2,Population,Population,"Population, 2006 - 100% data",2503281.0,30156.0,21562.0,11656.0,27482.0,25439.0,14945.0,15325.0,15376.0,13298.0,21961.0,6526.0,25479.0,21652.0,21720.0,7765.0,14198.0,8205.0,11596.0,17318.0,11120.0,10281.0,9815.0,12450.0,24379.0,19850.0,13732.0,14531.0,14405.0,9576.0,16500.0,26644.0,24374.0,34737.0,32010.0,11811.0,20096.0,14453.0,22387.0,9437.0,21115.0,18533.0,10675.0,21287.0,12294.0,10842.0,30886.0,14705.0,10026.0,11288.0,20969.0,19984.0,12853.0,18327.0,10531.0,12766.0,14778.0,13925.0,13025.0,32823.0,13168.0,11231.0,17034.0,17102.0,21400.0,8780.0,7780.0,45862.0,14436.0,13749.0,14827.0,15988.0,12116.0,9625.0,44324.0,10271.0,10240.0,26272.0,24973.0,17202.0,15481.0,12835.0,32127.0,15210.0,23728.0,10652.0,15557.0,20489.0,14563.0,12428.0,17114.0,13368.0,21443.0,17740.0,9019.0,13777.0,33821.0,8729.0,7688.0,16615.0,10965.0,10387.0,10725.0,22389.0,14655.0,20600.0,43191.0,9557.0,10042.0,15590.0,21013.0,24424.0,17564.0,24696.0,23809.0,27235.0,15211.0,20416.0,9928.0,17949.0,16604.0,5906.0,17047.0,26015.0,25632.0,32252.0,24403.0,16476.0,12098.0,26644.0,41054.0,12517.0,20907.0,52461.0,11550.0,8051.0,14194.0,10497.0,11235.0,26140.0,14830.0
763,764,Income,Income of families,Median after-tax income $,24478.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,1303,Labour,Labour force status,Participation rate,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1303,1304,Labour,Labour force status,Employment rate,60.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,1305,Labour,Labour force status,Unemployment rate,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1235,1236,Education,"Highest certificate, diploma or degree",Bachelor's degree,28295.0,365.0,245.0,85.0,915.0,240.0,145.0,830.0,270.0,200.0,295.0,55.0,215.0,115.0,105.0,30.0,80.0,195.0,60.0,150.0,190.0,20.0,165.0,145.0,860.0,75.0,135.0,85.0,75.0,85.0,75.0,255.0,165.0,370.0,130.0,115.0,55.0,165.0,70.0,50.0,170.0,170.0,75.0,120.0,275.0,260.0,150.0,115.0,85.0,130.0,315.0,210.0,215.0,380.0,30.0,65.0,70.0,175.0,125.0,440.0,130.0,25.0,180.0,495.0,130.0,130.0,85.0,460.0,255.0,140.0,315.0,170.0,105.0,80.0,240.0,55.0,55.0,395.0,160.0,95.0,160.0,25.0,325.0,210.0,475.0,95.0,340.0,240.0,180.0,60.0,250.0,35.0,130.0,120.0,50.0,325.0,375.0,45.0,80.0,140.0,185.0,60.0,50.0,115.0,105.0,390.0,440.0,80.0,30.0,85.0,150.0,135.0,370.0,435.0,235.0,310.0,85.0,225.0,80.0,130.0,155.0,260.0,160.0,605.0,130.0,265.0,260.0,55.0,65.0,140.0,1170.0,200.0,155.0,420.0,55.0,20.0,155.0,220.0,225.0,490.0,130.0
801,802,Immigration and citizenship,Immigrant status and period of immigration,Total immigrant population by period of immigr...,1237720.0,21770.0,14325.0,4310.0,8315.0,11920.0,8175.0,6660.0,9085.0,7805.0,5880.0,3315.0,13255.0,5890.0,13330.0,2925.0,8810.0,2065.0,5510.0,10020.0,3465.0,6175.0,2685.0,4360.0,8525.0,9695.0,6595.0,4855.0,7660.0,3455.0,6495.0,18615.0,14590.0,18320.0,17815.0,5870.0,5765.0,6125.0,12365.0,5085.0,9675.0,8130.0,5345.0,14330.0,4545.0,2515.0,19535.0,5675.0,2945.0,7985.0,8505.0,6325.0,6870.0,12685.0,5030.0,7980.0,9405.0,4880.0,7485.0,15370.0,5250.0,6130.0,9445.0,9080.0,11975.0,1860.0,2660.0,30350.0,5895.0,2725.0,2820.0,2935.0,5930.0,3400.0,27840.0,5580.0,3780.0,19100.0,10355.0,9660.0,3155.0,7285.0,21535.0,3925.0,9390.0,3980.0,9540.0,13005.0,5030.0,3355.0,10150.0,7805.0,11510.0,7335.0,3115.0,5460.0,18170.0,4130.0,2015.0,11120.0,3290.0,5550.0,4945.0,12220.0,5925.0,5535.0,23850.0,2805.0,5400.0,8515.0,10400.0,9825.0,7710.0,18395.0,9205.0,17405.0,9180.0,3900.0,5455.0,12090.0,7825.0,1835.0,9210.0,9940.0,12250.0,18820.0,17405.0,7660.0,6775.0,12600.0,25535.0,6440.0,9975.0,30605.0,3310.0,2785.0,5415.0,2435.0,3250.0,15695.0,8280.0
903,904,Ethnocultural diversity,Visible minority population,Total visible minority population,1162630.0,26440.0,16790.0,1185.0,5440.0,9660.0,3565.0,7995.0,9060.0,7580.0,2760.0,3325.0,14475.0,4415.0,16840.0,3165.0,5810.0,1545.0,2765.0,10885.0,2465.0,3605.0,1420.0,4285.0,8300.0,9645.0,4105.0,3910.0,3435.0,2540.0,4540.0,17320.0,17080.0,12825.0,15470.0,4365.0,5320.0,1875.0,15235.0,5710.0,7340.0,5120.0,3700.0,16430.0,2255.0,1190.0,22270.0,6460.0,2195.0,7935.0,4150.0,2615.0,8500.0,13245.0,2045.0,6915.0,10350.0,3945.0,8595.0,10070.0,3740.0,3845.0,10960.0,11015.0,11605.0,740.0,1625.0,34905.0,4360.0,1635.0,1335.0,1480.0,3165.0,1855.0,38350.0,3685.0,1565.0,24575.0,5935.0,11735.0,3400.0,8240.0,27380.0,1860.0,6640.0,3090.0,9265.0,8550.0,4740.0,2920.0,11530.0,9710.0,8725.0,6660.0,2095.0,3335.0,16755.0,3175.0,1120.0,10085.0,1545.0,8115.0,4370.0,10555.0,4610.0,2760.0,32415.0,1130.0,5460.0,10140.0,11010.0,11455.0,6960.0,21245.0,2750.0,18685.0,9415.0,1910.0,5250.0,13290.0,5060.0,1345.0,9150.0,9545.0,13990.0,24440.0,7320.0,8295.0,4500.0,12045.0,27710.0,4650.0,7290.0,35815.0,2870.0,2475.0,3830.0,1575.0,1440.0,16435.0,5835.0

In [63]:
selected_df[["Category", "Topic", "Attribute"]]

,Category,Topic,Attribute
1,Population,Population,"Population, 2006 - 100% data"
763,Income,Income of families,Median after-tax income $
1302,Labour,Labour force status,Participation rate
1303,Labour,Labour force status,Employment rate
1304,Labour,Labour force status,Unemployment rate
1235,Education,"Highest certificate, diploma or degree",Bachelor's degree
801,Immigration and citizenship,Immigrant status and period of immigration,Total immigrant population by period of immigr...
903,Ethnocultural diversity,Visible minority population,Total visible minority population

In [65]:
df_raw[
    df_raw["Category"].str.contains("Labour", case=False, na=False)
][["Category", "Topic", "Attribute"]]

,Category,Topic,Attribute
1297,Labour,Labour force status,Total population 15 years and over by Labour f...
1298,Labour,Labour force status,In the labour force
1299,Labour,Labour force status,Employed
1300,Labour,Labour force status,Unemployed
1301,Labour,Labour force status,Not in the labour force
...,...,...,...
1416,Labour,Place of work status,Total employed labour force 15 years and over ...
1417,Labour,Place of work status,Usual place of work
1418,Labour,Place of work status,At home
1419,Labour,Place of work status,Outside Canada
1420,Labour,Place of work status,No fixed workplace address

In [66]:
df_raw[
    df_raw["Attribute"].str.contains(
        "labour|employment|participation|unemployment",
        case=False,
        na=False,
        regex=True
    )
][["Category", "Topic", "Attribute"]]

,Category,Topic,Attribute
551,Income,Income of individuals,Total population 15 years and over with employ...
552,Income,Income of individuals,Median employment income in 2005 $
553,Income,Income of individuals,Average employment income in 2005 $
554,Income,Income of individuals,Standard error of average employment inc...
556,Income,Income of individuals,Median employment income in 2005 $
557,Income,Income of individuals,Average employment income in 2005 $
558,Income,Income of individuals,Standard error of average employment inc...
560,Income,Income of individuals,Median employment income in 2005 $
561,Income,Income of individuals,Average employment income in 2005 $
562,Income,Income of individuals,Standard error of average employment inc...
654,Income,Income of families,Employment income %
658,Income,Income of families,Employment income %
662,Income,Income of families,Employment income %
666,Income,Income of families,Employment income %
744,Income,Income of families,Employment income %
1297,Labour,Labour force status,Total population 15 years and over by Labour f...
1298,Labour,Labour force status,In the labour force
1301,Labour,Labour force status,Not in the labour force
1302,Labour,Labour force status,Participation rate
1303,Labour,Labour force status,Employment rate
1304,Labour,Labour force status,Unemployment rate
1305,Labour,Labour force status,Population 15 to 24 years - Labour force activity
1306,Labour,Labour force status,In the labour force
1309,Labour,Labour force status,Not in the labour force
1310,Labour,Labour force status,Participation rate
1311,Labour,Labour force status,Employment rate
1312,Labour,Labour force status,Unemployment rate
1313,Labour,Labour force status,Population 25 years and over - Labour force ac...
1314,Labour,Labour force status,In the labour force
1317,Labour,Labour force status,Not in the labour force
1318,Labour,Labour force status,Participation rate
1319,Labour,Labour force status,Employment rate
1320,Labour,Labour force status,Unemployment rate
1321,Labour,Class of worker,Total labour force 15 years and over by class ...
1333,Labour,Occupation - National Occupational Classificat...,Total labour force 15 years and over by occupa...
1382,Labour,Occupation - National Occupational Classificat...,H7 Transportation equipment operators an...
1383,Labour,Occupation - National Occupational Classificat...,"H8 Trades helpers, construction and tran..."
1385,Labour,Occupation - National Occupational Classificat...,"I0 Occupations unique to agriculture, ex..."
1386,Labour,Occupation - National Occupational Classificat...,I1 Occupations unique to forestry operat...
1387,Labour,Occupation - National Occupational Classificat...,I2 Primary production labourers
1392,Labour,Occupation - National Occupational Classificat...,"J3 Labourers in processing, manufacturin..."
1393,Labour,Industry - North American Industry Classificat...,Total labour force 15 years and over by indust...
1416,Labour,Place of work status,Total employed labour force 15 years and over ...
1421,Journey to work,Commuting destination,Total employed labour force 15 years and over ...
1425,Journey to work,Main mode of commuting,Total employed labour force 15 years and over ...

### Methodological Note

During feature extraction, the 2006 Toronto Neighbourhood Profile dataset was examined for neighbourhood-level labour market indicators, including employment rate, participation rate, and unemployment rate.

Although these variables exist in the dataset, they contain values only for the City of Toronto aggregate and are unavailable at the neighbourhood level. Consequently, these variables were excluded from the machine-learning-ready dataset to avoid introducing predictors with predominantly missing values.

The final predictor set therefore consists only of neighbourhood-level variables that are consistently available and suitable for predictive modelling.

### Section 9 – Transform into Machine Learning Dataset

The extracted indicators are currently stored as rows, while neighbourhoods are stored as columns.

To prepare the dataset for predictive modelling, the data structure will be transposed so that:

- each row represents one neighbourhood;
- each column represents one socioeconomic indicator.

This produces the standard machine-learning format where observations are stored as rows and variables are stored as columns.

In [68]:
features_only = selected_df.drop(
    columns=["_id", "Category", "Topic", "Attribute"]
)

features_only.head()

,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,Bayview Woods-Steeles,Bedford Park-Nortown,Beechborough-Greenbrook,Bendale,Birchcliffe-Cliffside,Black Creek,Blake-Jones,Briar Hill-Belgravia,Bridle Path-Sunnybrook-York Mills,Broadview North,Brookhaven-Amesbury,Cabbagetown-South St. James Town,Caledonia-Fairbank,Casa Loma,Centennial Scarborough,Church-Yonge Corridor,Clairlea-Birchmount,Clanton Park,Cliffcrest,Corso Italia-Davenport,Danforth,Danforth East York,Don Valley Village,Dorset Park,Dovercourt-Wallace Emerson-Junction,Downsview-Roding-CFB,Dufferin Grove,East End-Danforth,Edenbridge-Humber Valley,Eglinton East,Elms-Old Rexdale,Englemount-Lawrence,Eringate-Centennial-West Deane,Etobicoke West Mall,Flemingdon Park,Forest Hill North,Forest Hill South,Glenfield-Jane Heights,Greenwood-Coxwell,Guildwood,Henry Farm,High Park North,High Park-Swansea,Highland Creek,Hillcrest Village,Humber Heights-Westmount,Humber Summit,Humbermede,Humewood-Cedarvale,Ionview,Islington-City Centre West,Junction Area,Keelesdale-Eglinton West,Kennedy Park,Kensington-Chinatown,Kingsview Village-The Westway,Kingsway South,Lambton Baby Point,L'Amoreaux,Lansing-Westgate,Lawrence Park North,Lawrence Park South,Leaside-Bennington,Little Portugal,Long Branch,Malvern,Maple Leaf,Markland Wood,Milliken,Mimico (includes Humber Bay Shores),Morningside,Moss Park,Mount Dennis,Mount Olive-Silverstone-Jamestown,Mount Pleasant East,Mount Pleasant West,New Toronto,Newtonbrook East,Newtonbrook West,Niagara,North Riverdale,North St. James Town,Oakridge,Oakwood Village,O'Connor-Parkview,Old East York,Palmerston-Little Italy,Parkwoods-Donalda,Pelmo Park-Humberlea,Playter Estates-Danforth,Pleasant View,Princess-Rosethorn,Regent Park,Rexdale-Kipling,Rockcliffe-Smythe,Roncesvalles,Rosedale-Moore Park,Rouge,Runnymede-Bloor West Village,Rustic,Scarborough Village,South Parkdale,South Riverdale,St.Andrew-Windfields,Steeles,Stonegate-Queensway,Tam O'Shanter-Sullivan,Taylor-Massey,The Beaches,Thistletown-Beaumond Heights,Thorncliffe Park,Trinity-Bellwoods,University,Victoria Village,Waterfront Communities-The Island,West Hill,West Humber-Clairville,Westminster-Branson,Weston,Weston-Pelham Park,Wexford/Maryvale,Willowdale East,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
1,2503281.0,30156.0,21562.0,11656.0,27482.0,25439.0,14945.0,15325.0,15376.0,13298.0,21961.0,6526.0,25479.0,21652.0,21720.0,7765.0,14198.0,8205.0,11596.0,17318.0,11120.0,10281.0,9815.0,12450.0,24379.0,19850.0,13732.0,14531.0,14405.0,9576.0,16500.0,26644.0,24374.0,34737.0,32010.0,11811.0,20096.0,14453.0,22387.0,9437.0,21115.0,18533.0,10675.0,21287.0,12294.0,10842.0,30886.0,14705.0,10026.0,11288.0,20969.0,19984.0,12853.0,18327.0,10531.0,12766.0,14778.0,13925.0,13025.0,32823.0,13168.0,11231.0,17034.0,17102.0,21400.0,8780.0,7780.0,45862.0,14436.0,13749.0,14827.0,15988.0,12116.0,9625.0,44324.0,10271.0,10240.0,26272.0,24973.0,17202.0,15481.0,12835.0,32127.0,15210.0,23728.0,10652.0,15557.0,20489.0,14563.0,12428.0,17114.0,13368.0,21443.0,17740.0,9019.0,13777.0,33821.0,8729.0,7688.0,16615.0,10965.0,10387.0,10725.0,22389.0,14655.0,20600.0,43191.0,9557.0,10042.0,15590.0,21013.0,24424.0,17564.0,24696.0,23809.0,27235.0,15211.0,20416.0,9928.0,17949.0,16604.0,5906.0,17047.0,26015.0,25632.0,32252.0,24403.0,16476.0,12098.0,26644.0,41054.0,12517.0,20907.0,52461.0,11550.0,8051.0,14194.0,10497.0,11235.0,26140.0,14830.0
763,24478.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1303,60.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
ml_df = features_only.T

ml_df.head()

,1,763,1302,1303,1304,1235,801,903
City of Toronto,2503281.0,24478.0,65.0,60.1,7.6,28295.0,1237720.0,1162630.0
Agincourt North,30156.0,NaN,NaN,NaN,NaN,365.0,21770.0,26440.0
Agincourt South-Malvern West,21562.0,NaN,NaN,NaN,NaN,245.0,14325.0,16790.0
Alderwood,11656.0,NaN,NaN,NaN,NaN,85.0,4310.0,1185.0
Annex,27482.0,NaN,NaN,NaN,NaN,915.0,8315.0,5440.0

In [70]:
ml_df.columns = list(selected_rows.keys())

ml_df.head()

,Population,Median_AfterTax_Income,Participation_Rate,Employment_Rate,Unemployment_Rate,Bachelors_Degree,Immigrant_Population,Visible_Minority
City of Toronto,2503281.0,24478.0,65.0,60.1,7.6,28295.0,1237720.0,1162630.0
Agincourt North,30156.0,NaN,NaN,NaN,NaN,365.0,21770.0,26440.0
Agincourt South-Malvern West,21562.0,NaN,NaN,NaN,NaN,245.0,14325.0,16790.0
Alderwood,11656.0,NaN,NaN,NaN,NaN,85.0,4310.0,1185.0
Annex,27482.0,NaN,NaN,NaN,NaN,915.0,8315.0,5440.0

In [71]:
ml_df.reset_index(inplace=True)

ml_df.rename(
    columns={"index": "Neighbourhood"},
    inplace=True
)

ml_df.head()

,Neighbourhood,Population,Median_AfterTax_Income,Participation_Rate,Employment_Rate,Unemployment_Rate,Bachelors_Degree,Immigrant_Population,Visible_Minority
0,City of Toronto,2503281.0,24478.0,65.0,60.1,7.6,28295.0,1237720.0,1162630.0
1,Agincourt North,30156.0,NaN,NaN,NaN,NaN,365.0,21770.0,26440.0
2,Agincourt South-Malvern West,21562.0,NaN,NaN,NaN,NaN,245.0,14325.0,16790.0
3,Alderwood,11656.0,NaN,NaN,NaN,NaN,85.0,4310.0,1185.0
4,Annex,27482.0,NaN,NaN,NaN,NaN,915.0,8315.0,5440.0

In [72]:
ml_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Neighbourhood           141 non-null    object
 1   Population              141 non-null    float64
 2   Median_AfterTax_Income  1 non-null      float64
 3   Participation_Rate      1 non-null      float64
 4   Employment_Rate         1 non-null      float64
 5   Unemployment_Rate       1 non-null      float64
 6   Bachelors_Degree        141 non-null    float64
 7   Immigrant_Population    141 non-null    float64
 8   Visible_Minority        141 non-null    float64
dtypes: float64(8), object(1)
memory usage: 10.0+ KB

In [73]:
ml_df.shape

(141, 9)

## Section 10 – Summary and Next Steps

### Summary

This notebook completed the data preparation and feature extraction process for the 2006 Toronto Neighbourhood Profile dataset.

The raw dataset was explored to identify socioeconomic indicators that could potentially support longitudinal analysis and predictive modelling. Candidate variables were systematically searched, compared with the 2016 dataset, and evaluated based on neighbourhood-level availability and completeness.

The dataset was successfully transformed into a machine-learning format by transposing the neighbourhood profiles so that each row represents a neighbourhood and each column represents a socioeconomic indicator.

The final extracted variables included:

- Population
- Median After-Tax Income
- Employment Rate
- Participation Rate
- Unemployment Rate
- Bachelor's Degree
- Immigrant Population
- Visible Minority Population

### Data Quality Assessment

During the extraction process, an important limitation of the 2006 dataset was identified.

Although labour force and income indicators exist within the dataset, several of these variables contain neighbourhood-level values only for the City of Toronto aggregate while most individual neighbourhood observations are missing.

As a result, variables such as:

- Median After-Tax Income
- Employment Rate
- Participation Rate
- Unemployment Rate

contain substantial missing values and are not suitable for direct use in predictive modelling without introducing significant bias or data loss.

In contrast, variables such as:

- Population
- Bachelor's Degree
- Immigrant Population
- Visible Minority Population

were available for nearly all neighbourhoods and were successfully extracted.

### Conclusion

The 2006 dataset remains valuable for historical comparison and exploratory analysis of neighbourhood socioeconomic conditions. However, its limitations in neighbourhood-level labour market variables make it less suitable as the primary predictor dataset for the planned predictive modelling stage.

Based on these findings, the next phase of the project will evaluate the 2011 Toronto Neighbourhood Profile dataset as a more complete historical baseline for predicting neighbourhood-level socioeconomic outcomes observed in 2016.

This approach is expected to improve data completeness, maintain variable consistency across time periods, and provide a stronger foundation for supervised machine learning models while preserving the 2006 dataset as an important historical reference.