# 2016 Dataset Enhancement

This notebook supplements the existing 2016 ml ready dataset by extracting additional socioeconomic indicators required for the predictive modelling stage.

The objective is to align the 2016 dataset with the standardized feature set used in the 2011 dataset.

In [4]:
from pathlib import Path
import pandas as pd

project_root = Path.cwd().parents[1]

file_path = project_root / "data" / "raw" / "neighbourhood-profiles-2016-140-model.csv"

print(file_path)

df_raw = pd.read_csv(file_path)

print(df_raw.shape)
display(df_raw.head())

c:\Users\ksalyamova\Desktop\CIND 820\CIND820-Capstone-Project\data\raw\neighbourhood-profiles-2016-140-model.csv
(2383, 146)

,_id,Category,Topic,Data Source,Characteristic,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,...,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
0,1,Neighbourhood Information,Neighbourhood Information,City of Toronto,Neighbourhood Number,NaN,129,128,20,95,...,37,7,137,64,60,94,100,97,27,31
1,2,Neighbourhood Information,Neighbourhood Information,City of Toronto,TSNS2020 Designation,NaN,No Designation,No Designation,No Designation,No Designation,...,No Designation,No Designation,NIA,No Designation,No Designation,No Designation,No Designation,No Designation,NIA,Emerging Neighbourhood
2,3,Population,Population and dwellings,Census Profile 98-316-X2016001,"Population, 2016","2,731,571","29,113","23,757","12,054","30,526",...,"16,936","22,156","53,485","12,541","7,865","14,349","11,817","12,528","27,593","14,804"
3,4,Population,Population and dwellings,Census Profile 98-316-X2016001,"Population, 2011","2,615,060","30,279","21,988","11,904","29,177",...,"15,004","21,343","53,350","11,703","7,826","13,986","10,578","11,652","27,713","14,687"
4,5,Population,Population and dwellings,Census Profile 98-316-X2016001,Population Change 2011-2016,4.50%,-3.90%,8.00%,1.30%,4.60%,...,12.90%,3.80%,0.30%,7.20%,0.50%,2.60%,11.70%,7.50%,-0.40%,0.80%

### 1. Variable Identification

The required socioeconomic indicators are identified within the 2016 Toronto Neighbourhood Profile.

A helper function is used to search the dataset by keyword to verify the availability and location of each research variable before extraction.

In [5]:
def find_indicator(keyword):
    """
    Search the Characteristic column for a keyword.
    """
    results = df_raw[
        df_raw["Characteristic"].str.contains(keyword, case=False, na=False)
    ]

    return results[["_id", "Category", "Topic", "Characteristic"]]

In [6]:
find_indicator("Population, 2016")

   _id    Category                     Topic    Characteristic
2    3  Population  Population and dwellings  Population, 2016

In [7]:
find_indicator("Median income")

Empty DataFrame
Columns: [_id, Category, Topic, Characteristic]
Index: []

In [8]:
find_indicator("Median after-tax income")

,_id,Category,Topic,Characteristic
948,949,Income,Income of individuals in 2015,Median after-tax income in 2015 among reci...
1019,1020,Income,Income of households in 2015,Median after-tax income of households in 201...
1022,1023,Income,Income of households in 2015,Median after-tax income of one-person ho...
1025,1026,Income,Income of households in 2015,Median after-tax income of two-or-more-p...
1077,1078,Income,Income of economic families in 2015,Median after-tax income of economic families...
1082,1083,Income,Income of economic families in 2015,Median after-tax income of couple economic f...
1086,1087,Income,Income of economic families in 2015,Median after-tax income of couple economic f...
1089,1090,Income,Income of economic families in 2015,Median after-tax income of lone-parent econo...
1106,1107,Income,Income of economic families in 2015,Median after-tax income in 2015 for persons ...

In [9]:
find_indicator("income in 2015")

,_id,Category,Topic,Characteristic
946,947,Income,Income of individuals in 2015,Median total income in 2015 among recipien...
948,949,Income,Income of individuals in 2015,Median after-tax income in 2015 among reci...
951,952,Income,Income of individuals in 2015,Median market income in 2015 among recipie...
955,956,Income,Income of individuals in 2015,Median employment income in 2015 among rec...
959,960,Income,Income of individuals in 2015,Average total income in 2015 among recipie...
961,962,Income,Income of individuals in 2015,Average after-tax income in 2015 among rec...
963,964,Income,Income of individuals in 2015,Average market income in 2015 among recipi...
968,969,Income,Income of individuals in 2015,Average employment income in 2015 among re...
971,972,Income,Income of individuals in 2015,Median employment income in 2015 for full-year...
972,973,Income,Income of individuals in 2015,Average employment income in 2015 for full-yea...
973,974,Income,Income of individuals in 2015,Composition of total income in 2015 of the pop...
1105,1106,Income,Income of economic families in 2015,Median total income in 2015 for persons aged...
1106,1107,Income,Income of economic families in 2015,Median after-tax income in 2015 for persons ...

In [10]:
find_indicator("Median")

,_id,Category,Topic,Characteristic
946,947,Income,Income of individuals in 2015,Median total income in 2015 among recipien...
948,949,Income,Income of individuals in 2015,Median after-tax income in 2015 among reci...
951,952,Income,Income of individuals in 2015,Median market income in 2015 among recipie...
953,954,Income,Income of individuals in 2015,Median government transfers in 2015 among ...
955,956,Income,Income of individuals in 2015,Median employment income in 2015 among rec...
971,972,Income,Income of individuals in 2015,Median employment income in 2015 for full-year...
1014,1015,Income,Income of households in 2015,Median total income of one-person househ...
1018,1019,Income,Income of households in 2015,Median total income of households in 2015 ($)
1019,1020,Income,Income of households in 2015,Median after-tax income of households in 201...
1022,1023,Income,Income of households in 2015,Median after-tax income of one-person ho...
1024,1025,Income,Income of households in 2015,Median total income of two-or-more-perso...
1025,1026,Income,Income of households in 2015,Median after-tax income of two-or-more-p...
1076,1077,Income,Income of economic families in 2015,Median total income of economic families in ...
1077,1078,Income,Income of economic families in 2015,Median after-tax income of economic families...
1080,1081,Income,Income of economic families in 2015,Median total income of couple economic famil...
1082,1083,Income,Income of economic families in 2015,Median after-tax income of couple economic f...
1085,1086,Income,Income of economic families in 2015,Median total income of couple economic famil...
1086,1087,Income,Income of economic families in 2015,Median after-tax income of couple economic f...
1088,1089,Income,Income of economic families in 2015,Median total income of lone-parent economic ...
1089,1090,Income,Income of economic families in 2015,Median after-tax income of lone-parent econo...
1105,1106,Income,Income of economic families in 2015,Median total income in 2015 for persons aged...
1106,1107,Income,Income of economic families in 2015,Median after-tax income in 2015 for persons ...

In [11]:
find_indicator("individuals in 2015")

Empty DataFrame
Columns: [_id, Category, Topic, Characteristic]
Index: []

In [12]:
df_raw.loc[946]

_id                                                                      947
Category                                                              Income
Topic                                          Income of individuals in 2015
Data Source                                   Census Profile 98-316-X2016001
Characteristic                 Median total income in 2015 among recipien...
                                                 ...
Wychwood                                                                 NaN
Yonge-Eglinton                                                           NaN
Yonge-St.Clair                                                           NaN
York University Heights                                                  NaN
Yorkdale-Glen Park                                                       NaN
Name: 946, Length: 146, dtype: object

In [13]:
df_raw.loc[948]

_id                                                                      949
Category                                                              Income
Topic                                          Income of individuals in 2015
Data Source                                   Census Profile 98-316-X2016001
Characteristic                 Median after-tax income in 2015 among reci...
                                                 ...
Wychwood                                                                 NaN
Yonge-Eglinton                                                           NaN
Yonge-St.Clair                                                           NaN
York University Heights                                                  NaN
Yorkdale-Glen Park                                                       NaN
Name: 948, Length: 146, dtype: object

In [14]:
df_raw.loc[
    946,
    ["Characteristic",
     "City of Toronto",
     "Agincourt North",
     "Annex",
     "Alderwood"]
]

Characteristic         Median total income in 2015 among recipien...
City of Toronto                                               30,089
Agincourt North                                                  NaN
Annex                                                            NaN
Alderwood                                                        NaN
Name: 946, dtype: object

In [15]:
df_raw.loc[
    948,
    ["Characteristic",
     "City of Toronto",
     "Agincourt North",
     "Annex",
     "Alderwood"]
]

Characteristic         Median after-tax income in 2015 among reci...
City of Toronto                                               27,958
Agincourt North                                                  NaN
Annex                                                            NaN
Alderwood                                                        NaN
Name: 948, dtype: object