In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/neighbourhood_profiles_ml_ready.csv")

print(df.shape)

(143, 2384)

In [5]:
for col in df.columns:
    print(col)

Unnamed: 0
Neighbourhood Information | Neighbourhood Information | Neighbourhood Number
Neighbourhood Information | Neighbourhood Information | TSNS2020 Designation
Population | Population and dwellings | Population, 2016
Population | Population and dwellings | Population, 2011
Population | Population and dwellings | Population Change 2011-2016
Population | Population and dwellings | Total private dwellings
Population | Population and dwellings | Private dwellings occupied by usual residents
Population | Population and dwellings | Population density per square kilometre
Population | Population and dwellings | Land area in square kilometres
Population | Age characteristics | Children (0-14 years)
Population | Age characteristics | Youth (15-24 years)
Population | Age characteristics | Working Age (25-54 years)
Population | Age characteristics | Pre-retirement (55-64 years)
Population | Age characteristics | Seniors (65+ years)
Population | Age characteristics | Older Seniors (85+ years)
Population | Age characteristics | Male: 0 to 04 years
Population | Age characteristics | Male: 05 to 09 years
Population | Age characteristics | Male: 10 to 14 years
Population | Age characteristics | Male: 15 to 19 years
Population | Age characteristics | Male: 20 to 24 years
Population | Age characteristics | Male: 25 to 29 years
Population | Age characteristics | Male: 30 to 34 years
Population | Age characteristics | Male: 35 to 39 years
Population | Age characteristics | Male: 40 to 44 years
Population | Age characteristics | Male: 45 to 49 years
Population | Age characteristics | Male: 50 to 54 years
Population | Age characteristics | Male: 55 to 59 years
Population | Age characteristics | Male: 60 to 64 years
Population | Age characteristics | Male: 65 to 69 years
Population | Age characteristics | Male: 70 to 74 years
Population | Age characteristics | Male: 75 to 79 years
Population | Age characteristics | Female: 10 to 14 years
Population | Age characteristics | Male: 80 to 84 years
Population | Age characteristics | Male: 85 to 89 years
Population | Age characteristics | Male: 90 to 94 years
Population | Age characteristics | Male: 95 to 99 years
Population | Age characteristics | Male: 100 years and over
Population | Age characteristics | Female: 0 to 04 years
Population | Age characteristics | Female: 05 to 09 years
Population | Age characteristics | Female: 15 to 19 years
Population | Age characteristics | Female: 20 to 24 years
Population | Age characteristics | Female: 25 to 29 years
Population | Age characteristics | Female: 30 to 34 years
Population | Age characteristics | Female: 35 to 39 years
Population | Age characteristics | Female: 40 to 44 years
Population | Age characteristics | Female: 45 to 49 years
Population | Age characteristics | Female: 50 to 54 years
Population | Age characteristics | Female: 55 to 59 years
Population | Age characteristics | Female: 60 to 64 years
Population | Age characteristics | Female: 65 to 69 years
Population | Age characteristics | Female: 70 to 74 years
Population | Age characteristics | Female: 75 to 79 years
Population | Age characteristics | Female: 80 to 84 years
Population | Age characteristics | Female: 85 to 89 years
Population | Age characteristics | Female: 90 to 94 years
Population | Age characteristics | Female: 95 to 99 years
Population | Age characteristics | Female: 100 years and over
Families, households and marital status | Household and dwelling characteristics | Occupied private dwellings by structural type of dwelling
Families, households and marital status | Household and dwelling characteristics |   Single-detached house
Families, households and marital status | Household and dwelling characteristics |   Apartment in a building that has five or more storeys
Families, households and marital status | Household and dwelling characteristics |   Other attached dwelling
Families, households and marital status | Household and dwelling characteristics |     Semi-detached house
Families, households and marital status | Household and dwelling characteristics |     Row house
Families, households and marital status | Household and dwelling characteristics |     Apartment or flat in a duplex
Families, households and marital status | Household and dwelling characteristics |     Apartment in a building that has fewer than five storeys
Families, households and marital status | Household and dwelling characteristics |     Other single-attached house
Families, households and marital status | Household and dwelling characteristics |   Movable dwelling
Families, households and marital status | Household and dwelling characteristics | Private households by household size
Families, households and marital status | Household and dwelling characteristics |   1 person
Families, households and marital status | Household and dwelling characteristics |   2 persons
Families, households and marital status | Household and dwelling characteristics |   3 persons
Families, households and marital status | Household and dwelling characteristics |   4 persons
Families, households and marital status | Household and dwelling characteristics |   5 or more persons
Families, households and marital status | Household and dwelling characteristics | Number of persons in private households
Families, households and marital status | Household and dwelling characteristics |  Average household size
Families, households and marital status | Marital status | Marital status for the population aged 15 years and over
Families, households and marital status | Marital status |   Married or living common law
Families, households and marital status | Marital status |     Married
Families, households and marital status | Marital status |     Living common law
Families, households and marital status | Marital status |   Not married and not living common law
Families, households and marital status | Marital status |     Never married
Families, households and marital status | Marital status |     Separated
Families, households and marital status | Marital status |     Divorced
Families, households and marital status | Marital status |     Widowed
Families, households and marital status | Family characteristics | Census families in private households by family size
Families, households and marital status | Family characteristics |   2 persons
Families, households and marital status | Family characteristics |   3 persons
Families, households and marital status | Family characteristics |   4 persons
Families, households and marital status | Family characteristics |   5 or more persons
Families, households and marital status | Family characteristics |   Couples without children
Families, households and marital status | Family characteristics | Total number of census families in private households
Families, households and marital status | Family characteristics |   Total couple families
Families, households and marital status | Family characteristics |     Married couples
Families, households and marital status | Family characteristics |     Common-law couples
Families, households and marital status | Family characteristics |   Total lone-parent families by sex of parent
Families, households and marital status | Family characteristics |     Female parent
Families, households and marital status | Family characteristics |     Male parent
Families, households and marital status | Family characteristics | Couple census families in private households
Families, households and marital status | Family characteristics |   Couples with children
Families, households and marital status | Family characteristics |     1 child
Families, households and marital status | Family characteristics |     2 children
Families, households and marital status | Family characteristics |     3 or more children
Families, households and marital status | Family characteristics | Lone-parent census families in private households
Families, households and marital status | Family characteristics |   1 child
Families, households and marital status | Family characteristics |   2 children
Families, households and marital status | Household type |   Non-census-family households
Families, households and marital status | Family characteristics |   3 or more children
Families, households and marital status | Family characteristics | Persons not in census families in private households
Families, households and marital status | Household type | Private households by household type
Families, households and marital status | Household type |   One-census-family households
Families, households and marital status | Household type |     Without children in a census family
Families, households and marital status | Household type |     With children in a census family
Families, households and marital status | Household type |   Multiple-census-family households
Families, households and marital status | Household type |     One-person households
Families, households and marital status | Household type |     Two-or-more person non-census-family households
Families, households and marital status | Family characteristics of adults | Total population (age 15+) by family characteristics
Families, households and marital status | Family characteristics of adults | Persons living alone (total)
Families, households and marital status | Family characteristics of adults | Persons living alone (per cent)
Families, households and marital status | Family characteristics of adults | Population age 65+ by family characteristics
Families, households and marital status | Family characteristics of adults | Persons age 65+ living alone (total)
Families, households and marital status | Family characteristics of adults | Persons age 65+ living alone (per cent)
Families, households and marital status | Family characteristics of adults | Population age 85+ by family characteristics
Families, households and marital status | Family characteristics of adults | Persons age 85+ living alone (total)
Families, households and marital status | Family characteristics of adults | Persons age 85+ living alone (per cent)
Families, households and marital status | Family characteristics of adults | Population age 20-34 by family characteristics
Families, households and marital status | Family characteristics of adults | Single young adults (age 20-34) living at home (total)
Families, households and marital status | Family characteristics of adults | Single young adults (age 20-34) living at home (per cent)
Language | Knowledge of official languages | Knowledge of official languages for the total population excluding institutional residents
Language | Knowledge of official languages |   English only
Language | Knowledge of official languages |   French only
Language | Knowledge of official languages |   English and French
Language | Knowledge of official languages |   Neither English nor French
Language | First official language spoken | First official language spoken for the total population excluding institutional residents
Language | First official language spoken |   English
Language | First official language spoken | Official language minority (percentage)
Language | First official language spoken |   French
Language | First official language spoken |   English and French
Language | First official language spoken |   Neither English nor French
Language | First official language spoken | Official language minority (number)
Language | Mother tongue | Mother tongue for the total population excluding institutional residents
Language | Mother tongue |   Single responses
Language | Mother tongue |     Official languages
Language | Mother tongue |       English
Language | Mother tongue |       French
Language | Mother tongue |     Non-official languages
Language | Mother tongue |       Aboriginal languages
Language | Mother tongue |         Algonquian languages
Language | Mother tongue |           Blackfoot
Language | Mother tongue |           Cree-Montagnais languages
Language | Mother tongue |           Eastern Algonquian languages
Language | Mother tongue |           Ojibway-Potawatomi languages
Language | Mother tongue |           Algonquian languages, n.i.e.
Language | Mother tongue |         Athabaskan languages
Language | Mother tongue |           Northern Athabaskan languages
Language | Mother tongue |             Babine (Wetsuwet'en)
Language | Mother tongue |             Beaver
Language | Mother tongue |             Carrier
Language | Mother tongue |             Chilcotin
Language | Mother tongue |             Dene
Language | Mother tongue |             Dogrib (Tlicho)
Language | Mother tongue |             Gwich'in
Language | Mother tongue |             Sarsi (Sarcee)
Language | Mother tongue |             Sekani
Language | Mother tongue |             Slavey-Hare languages
Language | Mother tongue |               North Slavey (Hare)
Language | Mother tongue |               South Slavey
Language | Mother tongue |               Slavey, n.o.s.
Language | Mother tongue |             Tahltan languages
Language | Mother tongue |               Kaska (Nahani)
Language | Mother tongue |               Tahltan
Language | Mother tongue |             Tutchone languages
Language | Mother tongue |               Northern Tutchone
Language | Mother tongue |               Southern Tutchone
Language | Mother tongue |           Athabaskan languages, n.i.e.
Language | Mother tongue |         Haida
Language | Mother tongue |         Inuit languages
Language | Mother tongue |           Inuinnaqtun (Inuvialuktun)
Language | Mother tongue |           Inuktitut
Language | Mother tongue |           Inuit languages, n.i.e.
Language | Mother tongue |         Iroquoian languages
Language | Mother tongue |           Cayuga
Language | Mother tongue |           Mohawk
Language | Mother tongue |           Oneida
Language | Mother tongue |           Iroquoian languages, n.i.e.
Language | Mother tongue |         Kutenai
Language | Mother tongue |         Michif
Language | Mother tongue |         Salish languages
Language | Mother tongue |           Comox
Language | Mother tongue |           Halkomelem
Language | Mother tongue |           Lillooet
Language | Mother tongue |           Okanagan
Language | Mother tongue |           Shuswap (Secwepemctsin)
Language | Mother tongue |           Squamish
Language | Mother tongue |           Straits
Language | Mother tongue |           Thompson (Ntlakapamux)
Language | Mother tongue |           Salish languages, n.i.e.
Language | Mother tongue |         Siouan languages
Language | Mother tongue |           Dakota
Language | Mother tongue |           Stoney
Language | Mother tongue |           Siouan languages, n.i.e.
Language | Mother tongue |         Tlingit
Language | Mother tongue |         Tsimshian languages
Language | Mother tongue |           Gitxsan (Gitksan)
Language | Mother tongue |           Nisga'a
Language | Mother tongue |           Tsimshian
Language | Mother tongue |         Wakashan languages
Language | Mother tongue |           Haisla
Language | Mother tongue |           Heiltsuk
Language | Mother tongue |           Kwakiutl (Kwak'wala)
Language | Mother tongue |           Nuu-chah-nulth (Nootka)
Language | Mother tongue |           Wakashan languages, n.i.e.
Language | Mother tongue |         Aboriginal languages, n.o.s.
Language | Mother tongue |       Non-Aboriginal languages
Language | Mother tongue |         Afro-Asiatic languages
Language | Mother tongue |           Berber languages
Language | Mother tongue |             Kabyle
Language | Mother tongue |             Berber languages, n.i.e.
Language | Mother tongue |           Cushitic languages
Language | Mother tongue |             Bilen
Language | Mother tongue |             Oromo
Language | Mother tongue |             Somali
Language | Mother tongue |             Cushitic languages, n.i.e.
Language | Mother tongue |           Semitic languages
Language | Mother tongue |             Amharic
Language | Knowledge of languages |       Haida
Language | Mother tongue |             Arabic
Language | Mother tongue |             Assyrian Neo-Aramaic
Language | Mother tongue |             Chaldean Neo-Aramaic
Language | Mother tongue |             Harari
Language | Mother tongue |             Hebrew
Language | Mother tongue |             Maltese
Language | Mother tongue |             Tigrigna
Language | Mother tongue |             Semitic languages, n.i.e.
Language | Mother tongue |           Afro-Asiatic languages, n.i.e.
Language | Mother tongue |         Austro-Asiatic languages
Language | Mother tongue |           Khmer (Cambodian)
Language | Mother tongue |           Vietnamese
Language | Mother tongue |           Austro-Asiatic languages, n.i.e
Language | Mother tongue |         Austronesian languages
Language | Mother tongue |           Bikol
Language | Mother tongue |           Cebuano
Language | Mother tongue |           Fijian
Language | Mother tongue |           Hiligaynon
Language | Mother tongue |           Ilocano
Language | Mother tongue |           Malagasy
Language | Mother tongue |           Malay
Language | Mother tongue |           Pampangan (Kapampangan, Pampango)
Language | Mother tongue |           Pangasinan
Language | Mother tongue |           Tagalog (Pilipino, Filipino)
Language | Mother tongue |           Waray-Waray
Language | Mother tongue |           Austronesian languages, n.i.e.
Language | Mother tongue |         Creole languages
Language | Mother tongue |           Haitian Creole
Language | Mother tongue |           Creole, n.o.s.
Language | Mother tongue |           Creole languages, n.i.e.
Language | Mother tongue |         Dravidian languages
Language | Mother tongue |           Kannada
Language | Mother tongue |           Malayalam
Language | Mother tongue |           Tamil
Language | Mother tongue |           Telugu
Language | Mother tongue |           Dravidian languages, n.i.e.
Language | Mother tongue |         Hmong-Mien languages
Language | Mother tongue |         Indo-European languages
Language | Mother tongue |           Albanian
Language | Mother tongue |           Armenian
Language | Mother tongue |           Balto-Slavic languages
Language | Mother tongue |             Baltic languages
Language | Mother tongue |               Latvian
Income | Income of households in 2015 |     $150,000 to $199,999
Language | Mother tongue |               Lithuanian
Language | Mother tongue |             Slavic languages
Language | Mother tongue |               Belarusan
Language | Mother tongue |               Bosnian
Language | Mother tongue |               Bulgarian
Language | Mother tongue |               Croatian
Language | Mother tongue |               Czech
Language | Mother tongue |             Norwegian
Language | Mother tongue |               Macedonian
Language | Mother tongue |               Polish
Language | Mother tongue |               Russian
Language | Mother tongue |               Serbian
Language | Mother tongue |               Serbo-Croatian
Language | Mother tongue |               Slovak
Language | Mother tongue |               Slovene (Slovenian)
Language | Mother tongue |               Ukrainian
Language | Mother tongue |               Slavic languages, n.i.e.
Language | Mother tongue |           Celtic languages
Language | Mother tongue |             Scottish Gaelic
Language | Mother tongue |             Welsh
Language | Mother tongue |             Celtic languages, n.i.e.
Language | Mother tongue |             Swedish
Language | Mother tongue |           Germanic languages
Language | Mother tongue |             Afrikaans
Language | Mother tongue |             Danish
Language | Mother tongue |             Dutch
Language | Mother tongue |             Frisian
Language | Mother tongue |             German
Language | Mother tongue |             Icelandic
Language | Mother tongue |             Vlaams (Flemish)
Language | Mother tongue |             Yiddish

In [6]:
income_cols = [col for col in df.columns if "Income" in col]

print(len(income_cols))

for col in income_cols[:100]:
    print(col)

311
Income | Income of households in 2015 |     $150,000 to $199,999
Income | Income of individuals in 2015 |     $60,000 to $69,999
Income | Income of individuals in 2015 |     $70,000 to $79,999
Income | Income of individuals in 2015 |     $80,000 to $89,999
Income | Income of individuals in 2015 |     $90,000 to $99,999
Income | Income of individuals in 2015 |       $150,000 and over
Income | Income of individuals in 2015 |       $100,000 and over
Income | Income of individuals in 2015 |     $100,000 and over
Income | Income of individuals in 2015 |       $100,000 to $149,999
Income | Income of individuals in 2015 | Total - Income statistics in 2015 for the population aged 15 years and over in private households
Income | Income of individuals in 2015 |   Number of total income recipients aged 15 years and over in private households
Income | Income of individuals in 2015 |     Median total income in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of after-tax income recipients aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |     Median after-tax income in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of market income recipients aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |     $30,000 to $39,999
Income | Income of individuals in 2015 |     Median market income in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of government transfers recipients aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |     Median government transfers in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of employment income recipients aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |     Median employment income in 2015 among recipients ($)
Income | Income of individuals in 2015 | Total - Income statistics in 2015 for the population aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     $40,000 to $49,999
Income | Income of individuals in 2015 |   Number of total income recipients aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     Average total income in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of after-tax income recipients aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     Average after-tax income in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of market income recipients aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     Average market income in 2015 among recipients ($)
Income | Income of individuals in 2015 |     $50,000 to $59,999
Income | Income of individuals in 2015 |   Number of government transfers recipients aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     Average government transfers in 2015 among recipients ($)
Income | Income of individuals in 2015 |   Number of employment income recipients aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     Average employment income in 2015 among recipients ($)
Income | Income of individuals in 2015 | Total - Employment income statistics for the population aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 | Number of employment income recipients aged 15 years and over in private households who worked full year full time in 2015 - 25% sample data
Income | Income of individuals in 2015 | Median employment income in 2015 for full-year full-time workers ($)
Income | Income of individuals in 2015 | Average employment income in 2015 for full-year full-time workers ($)
Income | Income of individuals in 2015 | Composition of total income in 2015 of the population aged 15 years and over in private households (%) - 100% data
Income | Income of individuals in 2015 |   Market income (%)
Income | Income of individuals in 2015 |     Employment income (%)
Income | Income of individuals in 2015 |   Government transfers (%)
Income | Income of individuals in 2015 | Total - Total income groups in 2015 for the population aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |   Without total income
Income | Income of individuals in 2015 |   With total income
Income | Income of individuals in 2015 |   Percentage with total income
Income | Income of individuals in 2015 |     Under $10,000 (including loss)
Income | Income of individuals in 2015 |     $10,000 to $19,999
Income | Income of individuals in 2015 |     $20,000 to $29,999
Income | Income of individuals in 2015 | Total - After-tax income groups in 2015 for the population aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |   Without after-tax income
Income | Income of individuals in 2015 |   With after-tax income
Income | Income of individuals in 2015 |   Percentage with after-tax income
Income | Income of individuals in 2015 |     Under $10,000 (including loss).1
Income | Income of individuals in 2015 |     $10,000 to $19,999.1
Income | Income of individuals in 2015 |     $20,000 to $29,999.1
Income | Income of individuals in 2015 |     $30,000 to $39,999.1
Income | Income of individuals in 2015 |     $40,000 to $49,999.1
Income | Income of individuals in 2015 |     $50,000 to $59,999.1
Income | Income of individuals in 2015 |     $60,000 to $69,999.1
Income | Income of individuals in 2015 |     $70,000 to $79,999.1
Income | Income of individuals in 2015 |     $80,000 and over
Income | Income of individuals in 2015 |       $80,000 to $89,999
Income | Income of individuals in 2015 |       $90,000 to $99,999
Income | Income of individuals in 2015 | Total - Employment income groups in 2015 for the population aged 15 years and over in private households - 100% data
Income | Income of individuals in 2015 |   Without employment income
Income | Income of individuals in 2015 |   With employment income
Income | Income of individuals in 2015 |   Percentage with employment income
Income | Income of individuals in 2015 |     Under $5,000 (including loss)
Income | Income of individuals in 2015 |     $5,000 to $9,999
Income | Income of individuals in 2015 |     $10,000 to $19,999.2
Income | Income of individuals in 2015 |     $20,000 to $29,999.2
Income | Income of individuals in 2015 |     $30,000 to $39,999.2
Income | Income of individuals in 2015 |     $40,000 to $49,999.2
Income | Income of individuals in 2015 |     $50,000 to $59,999.2
Income | Income of individuals in 2015 |     $60,000 to $69,999.2
Income | Income of individuals in 2015 |     $70,000 to $79,999.2
Income | Income of individuals in 2015 |     $80,000 and over.1
Income | Income of individuals in 2015 |       $80,000 to $89,999.1
Income | Income of households in 2015 |       Median total income of one-person households in 2015 ($)
Income | Income of individuals in 2015 |       $90,000 to $99,999.1
Income | Income of individuals in 2015 |       $100,000 and over.1
Income | Income of households in 2015 | Total - Income statistics in 2015 for private households by household size - 100% data
Income | Income of households in 2015 |   Median total income of households in 2015 ($)
Income | Income of households in 2015 |   Median after-tax income of households in 2015 ($)
Income | Income of households in 2015 |     Total - Income statistics in 2015 for one-person private households - 100% data
Income | Income of households in 2015 |   $15,000 to $19,999
Income | Income of households in 2015 |       Median after-tax income of one-person households in 2015 ($)
Income | Income of households in 2015 |     Total - Income statistics in 2015 for two-or-more-person private households - 100% data
Income | Income of households in 2015 |       Median total income of two-or-more-person households in 2015 ($)
Income | Income of households in 2015 |       Median after-tax income of two-or-more-person households in 2015 ($)
Income | Income of households in 2015 | Total - Income statistics in 2015for private households by household size - 25% sampledata
Income | Income of households in 2015 |   Average total income of households in 2015 ($)
Income | Income of households in 2015 |     $100,000 to $124,999
Income | Income of households in 2015 |   Average after-tax income of households in 2015 ($)
Income | Income of households in 2015 |     Total - Income statistics in 2015 for one-person private households - 25% sample data
Income | Income of households in 2015 |       Average total income of one-person households in 2015 ($)
Income | Income of households in 2015 |       Average after-tax income of one-person households in 2015 ($)
Income | Income of households in 2015 |     Total - Income statistics in 2015 for two-or-more-person private households - 25% sample data
Income | Income of households in 2015 |       Average total income of two-or-more-person households in 2015 ($)

In [7]:
employment_cols = [col for col in df.columns if "Employment" in col]

print(len(employment_cols))

for col in employment_cols:
    print(col)

12
Income | Income of individuals in 2015 | Total - Employment income statistics for the population aged 15 years and over in private households - 25% sample data
Income | Income of individuals in 2015 |     Employment income (%)
Income | Income of individuals in 2015 | Total - Employment income groups in 2015 for the population aged 15 years and over in private households - 100% data
Labour | Labour force status | Employment rate
Labour | Labour force status | Employment rate (Males)
Labour | Labour force status | Employment rate (Females)
Income | Income sources |     Employment income: Population with an amount
Income | Income sources |     Employment income: Average amount ($)
Income | Income sources |     Employment income: Aggregate amount ($'000)
Income | Income sources |     Employment Insurance (EI) benefits: Population with an amount
Income | Income sources |     Employment Insurance (EI) benefits: Average amount ($)
Income | Income sources |     Employment Insurance (EI) benefits: Aggregate amount ($'000)

In [9]:
education_cols = [col for col in df.columns if "Education" in col]

print(len(education_cols))

for col in education_cols:
    print(col)

183
Education | Highest certificate, diploma or degree |       Master's degree
Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree
Education | Highest certificate, diploma or degree |     Apprenticeship or trades certificate or diploma
Education | Highest certificate, diploma or degree | Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data
Education | Highest certificate, diploma or degree |   No certificate, diploma or degree
Education | Highest certificate, diploma or degree |   Secondary (high) school diploma or equivalency certificate
Education | Highest certificate, diploma or degree |       Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification
Education | Highest certificate, diploma or degree |       Certificate of Apprenticeship or Certificate of Qualification
Education | Highest certificate, diploma or degree |     College, CEGEP or other non-university certificate or diploma
Education | Highest certificate, diploma or degree |     University certificate or diploma below bachelor level
Education | Highest certificate, diploma or degree |     University certificate, diploma or degree at bachelor level or above
Education | Highest certificate, diploma or degree |       Bachelor's degree
Education | Highest certificate, diploma or degree |       University certificate or diploma above bachelor level
Education | Highest certificate, diploma or degree |       Degree in medicine, dentistry, veterinary medicine or optometry
Education | Highest certificate, diploma or degree |       Earned doctorate
Education | Highest certificate, diploma or degree | Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households - 25% sample data
Education | Highest certificate, diploma or degree |   No certificate, diploma or degree.1
Education | Highest certificate, diploma or degree |   Secondary (high) school diploma or equivalency certificate.1
Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree.1
Education | Highest certificate, diploma or degree |     Apprenticeship or trades certificate or diploma.1
Education | Highest certificate, diploma or degree |       Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification.1
Education | Highest certificate, diploma or degree |       Master's degree.1
Education | Highest certificate, diploma or degree |       Certificate of Apprenticeship or Certificate of Qualification.1
Education | Highest certificate, diploma or degree |     College, CEGEP or other non-university certificate or diploma.1
Education | Highest certificate, diploma or degree |     University certificate or diploma below bachelor level.1
Education | Highest certificate, diploma or degree |     University certificate, diploma or degree at bachelor level or above.1
Education | Highest certificate, diploma or degree |       Bachelor's degree.1
Education | Highest certificate, diploma or degree |       University certificate or diploma above bachelor level.1
Education | Highest certificate, diploma or degree |       Degree in medicine, dentistry, veterinary medicine or optometry.1
Education | Highest certificate, diploma or degree |       Earned doctorate.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 | Total - Major field of study - Classification of Instructional Programs (CIP) 2016 for the population aged 15 years and over in private households - 25% sample data
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   No postsecondary certificate, diploma or degree
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Education
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     13. Education
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Visual and performing arts, and communications technologies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     10. Communications technologies/technicians and support services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     50. Visual and performing arts
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Humanities
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     16. Aboriginal and foreign languages, literatures and linguistics
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     23. English language and literature/letters
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     24. Liberal arts and sciences, general studies and humanities
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     52. Business, management, marketing and related support services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30A Interdisciplinary humanities
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     38. Philosophy and religious studies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     39. Theology and religious vocations
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     54. History
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     55. French language and literature/letters
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Social and behavioural sciences and law
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     05. Area, ethnic, cultural, gender, and group studies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     09. Communication, journalism and related programs
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     19. Family and consumer sciences/human sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     22. Legal professions and studies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30B Interdisciplinary social and behavioural sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     42. Psychology
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     45. Social sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Business, management and public administration
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.16 Accounting and computer science
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     44. Public administration and social service professions
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Physical and life sciences and technologies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     26. Biological and biomedical sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.01 Biological and physical sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30C Other interdisciplinary physical and life sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     40. Physical sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     41. Science technologies/technicians
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Mathematics, computer and information sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     11. Computer and information sciences and support services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     25. Library science
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     27. Mathematics and statistics
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30D Interdisciplinary mathematics, computer and information sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Architecture, engineering, and related technologies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     04. Architecture and related services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     14. Engineering
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     15. Engineering technologies and engineering-related fields
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.12 Historic preservation and conservation
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     46. Construction trades
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     03. Natural resources and conservation
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     47. Mechanic and repair technologies/technicians
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     48. Precision production
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Agriculture, natural resources and conservation
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     01. Agriculture, agriculture operations and related sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Health and related fields
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     31. Parks, recreation, leisure and fitness studies
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     51. Health professions and related programs
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     60. Dental, medical and veterinary residency programs
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Personal, protective and transportation services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     12. Personal and culinary services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     28. Military science, leadership and operational art
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     29. Military technologies and applied sciences
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     43. Security and protective services
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     49. Transportation and materials moving
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Other
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.99 Multidisciplinary/interdisciplinary studies, other
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 | Total - Major field of study - Classification of Instructional Programs (CIP) 2016 for the population aged 25 to 64 years in private households - 25% sample data
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   No postsecondary certificate, diploma or degree.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Personal, protective and transportation services.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Education.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     13. Education.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Visual and performing arts, and communications technologies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     10. Communications technologies/technicians and support services.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     50. Visual and performing arts.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Humanities.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     39. Theology and religious vocations.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     16. Aboriginal and foreign languages, literatures and linguistics.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     23. English language and literature/letters.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     24. Liberal arts and sciences, general studies and humanities.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30A Interdisciplinary humanities.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     38. Philosophy and religious studies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     54. History.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     55. French language and literature/letters.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Social and behavioural sciences and law.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     05. Area, ethnic, cultural, gender, and group studies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     09. Communication, journalism and related programs.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Business, management and public administration.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     19. Family and consumer sciences/human sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     22. Legal professions and studies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30B Interdisciplinary social and behavioural sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     42. Psychology.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     45. Social sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.16 Accounting and computer science.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     44. Public administration and social service professions.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     52. Business, management, marketing and related support services.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Physical and life sciences and technologies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     26. Biological and biomedical sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.01 Biological and physical sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30C Other interdisciplinary physical and life sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     40. Physical sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     41. Science technologies/technicians.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Mathematics, computer and information sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     11. Computer and information sciences and support services.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     25. Library science.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.99 Multidisciplinary/interdisciplinary studies, other.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     27. Mathematics and statistics.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30D Interdisciplinary mathematics, computer and information sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Architecture, engineering, and related technologies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     04. Architecture and related services.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     14. Engineering.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Agriculture, natural resources and conservation.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     15. Engineering technologies and engineering-related fields.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     30.12 Historic preservation and conservation.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     46. Construction trades.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     47. Mechanic and repair technologies/technicians.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     48. Precision production.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     01. Agriculture, agriculture operations and related sciences.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     03. Natural resources and conservation.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |   Health and related fields.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     31. Parks, recreation, leisure and fitness studies.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     51. Health professions and related programs.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     60. Dental, medical and veterinary residency programs.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     12. Personal and culinary services.1
Education | Major field of study - Classification of Instructional Programs (CIP) 2016 |     28. Military science, leadership and operational art.1

In [10]:
housing_cols = [col for col in df.columns if "Housing" in col]

print(len(housing_cols))

for col in housing_cols:
    print(col)

74
Housing | Household characteristics |   1981 to 1990
Housing | Household characteristics | Total - Private households by tenure - 25% sample data
Housing | Household characteristics |   Owner
Housing | Household characteristics |   Renter
Housing | Household characteristics |   Band housing
Housing | Household characteristics | Total - Occupied private dwellings by condominium status - 25% sample data
Housing | Household characteristics |   Condominium
Housing | Household characteristics |   Not condominium
Housing | Household characteristics | Total - Occupied private dwellings by number of bedrooms - 25% sample data
Housing | Household characteristics |   No bedrooms
Housing | Household characteristics |   1 bedroom
Housing | Household characteristics |   2 bedrooms
Housing | Household characteristics |   3 bedrooms
Housing | Household characteristics |   1991 to 2000
Housing | Household characteristics |   4 or more bedrooms
Housing | Household characteristics | Total - Occupied private dwellings by number of rooms - 25% sample data
Housing | Household characteristics |   1 to 4 rooms
Housing | Household characteristics |   5 rooms
Housing | Household characteristics |   6 rooms
Housing | Household characteristics |   7 rooms
Housing | Household characteristics |   8 or more rooms
Housing | Household characteristics | Total - Private households by number of persons per room - 25% sample data
Housing | Household characteristics |   Major repairs needed
Housing | Household characteristics |   One person or fewer per room
Housing | Household characteristics |   More than 1 person per room
Housing | Household characteristics | Total - Private households by housing suitability - 25% sample data
Housing | Household characteristics |   Suitable
Housing | Household characteristics |   Not suitable
Housing | Household characteristics | Total - Occupied private dwellings by period of construction - 25% sample data
Housing | Household characteristics |   1960 or before
Housing | Household characteristics |   1961 to 1980
Housing | Household characteristics |   2001 to 2005
Housing | Household characteristics |   2006 to 2010
Housing | Household characteristics |   2011 to 2016
Housing | Household characteristics | Total - Occupied private dwellings by dwelling condition - 25% sample data
Housing | Household characteristics |   Only regular maintenance or minor repairs needed
Housing | Household characteristics | Total - Private households by number of household maintainers - 25% sample data
Housing | Household characteristics |   1 household maintainer
Housing | Household characteristics |   2 household maintainers
Housing | Household characteristics |   3 or more household maintainers
Housing | Household characteristics | Total - Private households by age of primary household maintainers - 25% sample data
Housing | Household characteristics |   15 to 24 years
Housing | Household characteristics |   25 to 34 years
Housing | Household characteristics |   35 to 44 years
Housing | Household characteristics |   45 to 54 years
Housing | Household characteristics |   55 to 64 years
Housing | Household characteristics |   65 to 74 years
Housing | Household characteristics |   75 to 84 years
Housing | Household characteristics |   85 years and over
Housing | Household characteristics | Total -  Owner and tenant households with household total income greater than zero; in non-farm; non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data
Housing | Household characteristics |   Spending less than 30% of income on shelter costs
Housing | Household characteristics |   Spending 30% or more of income on shelter costs
Housing | Household characteristics |     30% to less than 100%
Housing | Core housing need | Occupied private dwellings
Housing | Core housing need | Rate of core housing need
Housing | Core housing need | Number of households in core housing need
Housing | Core housing need | Core housing need, Unsuitable only
Housing | Core housing need | Core housing need, Inadequate only
Housing | Core housing need | Core housing need, Unaffordable only
Housing | Core housing need | Core housing need, two or more dimensions
Housing | Core housing need | Rate of unaffordable housing
Housing | Core housing need | Unaffordable housing not in core need
Housing | Core housing need | Unaffordable housing in core need
Housing | Core housing need | Unaffordable housing not applicable for core need
Housing | Core housing need | Rate of unaffordable housing, owner-households
Housing | Core housing need | Rate of unaffordable housing, renter-households
Housing | Core housing need | Rate of inadequate housing
Housing | Core housing need | Inadequate housing not in core need
Housing | Core housing need | Inadequate housing in core need
Housing | Core housing need | Inadequate housing not applicable for core need
Housing | Core housing need | Rate of unsuitable housing
Housing | Core housing need | Unsuitable housing not in core need
Housing | Core housing need | Unsuitable housing in core need
Housing | Core housing need | Unsuitable housing not applicable for core need

In [11]:
selected_cols = ["Unnamed: 0",

    # Population
    "Population, 2016",
    "Population Change 2011-2016",
    "Population density per square kilometre",

    # Income
    "Median total income of households in 2015 ($)",
    "Median after-tax income of households in 2015 ($)",
    "Average total income of households in 2015 ($)",
    "Average after-tax income of households in 2015 ($)",

    # Employment
    "Employment rate",
    "Employment rate (Males)",
    "Employment rate (Females)",

    # Education
    "No certificate, diploma or degree",
    "Secondary (high) school diploma or equivalency certificate",
    "Postsecondary certificate, diploma or degree",
    "Bachelor's degree",
    "Master's degree"]

In [12]:
for col in selected_cols:
    print(col in df.columns, col)

True Unnamed: 0
False Population, 2016
False Population Change 2011-2016
False Population density per square kilometre
False Median total income of households in 2015 ($)
False Median after-tax income of households in 2015 ($)
False Average total income of households in 2015 ($)
False Average after-tax income of households in 2015 ($)
False Employment rate
False Employment rate (Males)
False Employment rate (Females)
False No certificate, diploma or degree
False Secondary (high) school diploma or equivalency certificate
False Postsecondary certificate, diploma or degree
False Bachelor's degree
False Master's degree

In [13]:
for col in df.columns:
    if "Population, 2016" in col:
        print(col)

Population | Population and dwellings | Population, 2016

In [14]:
for col in df.columns:
    if "Employment rate" in col:
        print(col)

Labour | Labour force status | Employment rate
Labour | Labour force status | Employment rate (Males)
Labour | Labour force status | Employment rate (Females)

In [15]:
for col in df.columns:
    if "Median total income" in col:
        print(col)

Income | Income of individuals in 2015 |     Median total income in 2015 among recipients ($)
Income | Income of households in 2015 |       Median total income of one-person households in 2015 ($)
Income | Income of households in 2015 |   Median total income of households in 2015 ($)
Income | Income of households in 2015 |       Median total income of two-or-more-person households in 2015 ($)
Income | Income of economic families in 2015 |   Median total income of economic families in 2015 ($)
Income | Income of economic families in 2015 |   Median total income of couple economic families without children or other relatives in 2015 ($)
Income | Income of economic families in 2015 |   Median total income of couple economic families with children in 2015 ($)
Income | Income of economic families in 2015 |   Median total income of lone-parent economic families in 2015 ($)
Income | Income of economic families in 2015 |   Median total income in 2015 for persons aged 15 years and over not in economic families ($)

In [16]:
for col in df.columns:
    if "Bachelor" in col:
        print(col)

Education | Highest certificate, diploma or degree |       Bachelor's degree
Education | Highest certificate, diploma or degree |       Bachelor's degree.1

In [17]:
for col in df.columns:
    if "Median after-tax income" in col:
        print(col)

Income | Income of individuals in 2015 |     Median after-tax income in 2015 among recipients ($)
Income | Income of households in 2015 |   Median after-tax income of households in 2015 ($)
Income | Income of households in 2015 |       Median after-tax income of one-person households in 2015 ($)
Income | Income of households in 2015 |       Median after-tax income of two-or-more-person households in 2015 ($)
Income | Income of economic families in 2015 |   Median after-tax income of economic families in 2015 ($)
Income | Income of economic families in 2015 |   Median after-tax income of couple economic families without children or other relatives in 2015 ($)
Income | Income of economic families in 2015 |   Median after-tax income of couple economic families with children in 2015 ($)
Income | Income of economic families in 2015 |   Median after-tax income of lone-parent economic families in 2015 ($)
Income | Income of economic families in 2015 |   Median after-tax income in 2015 for persons aged 15 years and over not in economic families ($)

In [18]:
for col in df.columns:
    if "Government transfers" in col:
        print(col)

Income | Income of individuals in 2015 |   Government transfers (%)
Income | Income sources |   Government transfers: Population with an amount
Income | Income sources |   Government transfers: Average amount ($)
Income | Income sources |   Government transfers: Aggregate amount ($'000)
Income | Income sources |       Government transfers not included elsewhere: Population with an amount
Income | Income sources |       Government transfers not included elsewhere: Average amount ($)
Income | Income sources |       Government transfers not included elsewhere: Aggregate amount ($'000)

In [19]:
for col in df.columns:
    if "No certificate" in col:
        print(col)

Education | Highest certificate, diploma or degree |   No certificate, diploma or degree
Education | Highest certificate, diploma or degree |   No certificate, diploma or degree.1

In [20]:
for col in df.columns:
    if "Postsecondary certificate" in col:
        print(col)

Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree
Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree.1
Education | Location of study compared with province or territory of residence with countries outside Canada |   Postsecondary certificate, diploma or degree
Education | Location of study compared with province or territory of residence with countries outside Canada |   Postsecondary certificate, diploma or degree.1

In [21]:
for col in df.columns:
    if "Master" in col:
        print(col)

Education | Highest certificate, diploma or degree |       Master's degree
Education | Highest certificate, diploma or degree |       Master's degree.1

In [22]:
for col in df.columns:
    if "Rate of core housing need" in col:
        print(col)

Housing | Core housing need | Rate of core housing need

In [23]:
for col in df.columns:
    if "30% or more of income on shelter costs" in col:
        print(col)

Housing | Household characteristics |   Spending 30% or more of income on shelter costs

In [24]:
for col in df.columns:
    if "Low" in col:
        print(col)

Income | Low income in 2015 |   18 to 64 years (%)
Income | Low income in 2015 |     0 to 5 years (%)
Income | Low income in 2015 | Total - Low-income status in 2015 for the population in private households to whom low-income concepts are applicable - 100% data
Income | Low income in 2015 |   0 to 17 years
Income | Low income in 2015 |     0 to 5 years
Income | Low income in 2015 |   18 to 64 years
Income | Low income in 2015 |   65 years and over
Income | Low income in 2015 | In low income based on the Low-income measure, after tax (LIM-AT)
Income | Low income in 2015 |   0 to 17 years.1
Income | Low income in 2015 |     0 to 5 years.1
Income | Low income in 2015 |   18 to 64 years.1
Income | Low income in 2015 |   65 years and over.1
Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)
Income | Low income in 2015 |   0 to 17 years (%)
Income | Low income in 2015 |   65 years and over (%)
Income | Low income in 2015 | In low income based on the Low-income cut-offs, after tax (LICO-AT)
Income | Low income in 2015 |   0 to 17 years.2
Income | Low income in 2015 |     0 to 5 years.2
Income | Low income in 2015 |   18 to 64 years.2
Income | Low income in 2015 |   65 years and over.2
Income | Low income in 2015 | Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)
Income | Low income in 2015 |   0 to 17 years (%).1
Income | Low income in 2015 |     0 to 5 years (%).1
Income | Low income in 2015 |   18 to 64 years (%).1
Income | Low income in 2015 |   65 years and over (%).1

In [25]:
for col in df.columns:
    if "LIM" in col or "LICO" in col:
        print(col)

Income | Low income in 2015 | In low income based on the Low-income measure, after tax (LIM-AT)
Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)
Income | Low income in 2015 | In low income based on the Low-income cut-offs, after tax (LICO-AT)
Income | Low income in 2015 | Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)

In [29]:
selected_cols = ["Unnamed: 0",

    "Population | Population and dwellings | Population, 2016",

    "Income | Income of households in 2015 |   Median total income of households in 2015 ($)",
    "Income | Income of households in 2015 |   Median after-tax income of households in 2015 ($)",
    "Income | Income of individuals in 2015 |     Government transfers (%)",

    "Labour | Labour force status | Employment rate",
    "Labour | Labour force status | Employment rate (Males)",
    "Labour | Labour force status | Employment rate (Females)",

    "Education | Highest certificate, diploma or degree | No certificate, diploma or degree",
    "Education | Highest certificate, diploma or degree | Postsecondary certificate, diploma or degree",
    "Education | Highest certificate, diploma or degree | Bachelor's degree",
    "Education | Highest certificate, diploma or degree | Master's degree",

    "Housing | Core housing need | Rate of core housing need",

    "Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT)"]

for col in selected_cols:
    if col not in df.columns:
        print("MISSING:", repr(col))

MISSING: 'Income | Income of individuals in 2015 |     Government transfers (%)'
MISSING: 'Education | Highest certificate, diploma or degree | No certificate, diploma or degree'
MISSING: 'Education | Highest certificate, diploma or degree | Postsecondary certificate, diploma or degree'
MISSING: "Education | Highest certificate, diploma or degree | Bachelor's degree"
MISSING: "Education | Highest certificate, diploma or degree | Master's degree"
MISSING: 'Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT)'

In [30]:
for col in df.columns:
    if "Government transfers" in col:
        print(repr(col))

'Income | Income of individuals in 2015 |   Government transfers (%)'
'Income | Income sources |   Government transfers: Population with an amount'
'Income | Income sources |   Government transfers: Average amount ($)'
"Income | Income sources |   Government transfers: Aggregate amount ($'000)"
'Income | Income sources |       Government transfers not included elsewhere: Population with an amount'
'Income | Income sources |       Government transfers not included elsewhere: Average amount ($)'
"Income | Income sources |       Government transfers not included elsewhere: Aggregate amount ($'000)"

In [31]:
for col in df.columns:
    if "No certificate" in col:
        print(repr(col))

'Education | Highest certificate, diploma or degree |   No certificate, diploma or degree'
'Education | Highest certificate, diploma or degree |   No certificate, diploma or degree.1'

In [32]:
for col in df.columns:
    if "Postsecondary certificate" in col:
        print(repr(col))

'Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree'
'Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree.1'
'Education | Location of study compared with province or territory of residence with countries outside Canada |   Postsecondary certificate, diploma or degree'
'Education | Location of study compared with province or territory of residence with countries outside Canada |   Postsecondary certificate, diploma or degree.1'

In [33]:
for col in df.columns:
    if "Bachelor" in col:
        print(repr(col))

"Education | Highest certificate, diploma or degree |       Bachelor's degree"
"Education | Highest certificate, diploma or degree |       Bachelor's degree.1"

In [34]:
for col in df.columns:
    if "Master" in col:
        print(repr(col))

"Education | Highest certificate, diploma or degree |       Master's degree"
"Education | Highest certificate, diploma or degree |       Master's degree.1"

In [35]:
for col in df.columns:
    if "Prevalence of low income" in col:
        print(repr(col))

'Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)'
'Income | Low income in 2015 | Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)'

In [37]:
candidate_cols = []

for col in df.columns:
    if "Population, 2016" in col:
        candidate_cols.append(col)

    elif "Median total income of households in 2015 ($)" in col:
        candidate_cols.append(col)

    elif "Median after-tax income of households in 2015 ($)" in col:
        candidate_cols.append(col)

    elif "Government transfers (%)" in col:
        candidate_cols.append(col)

    elif col.endswith("Employment rate"):
        candidate_cols.append(col)

    elif "Employment rate (Males)" in col:
        candidate_cols.append(col)

    elif "Employment rate (Females)" in col:
        candidate_cols.append(col)

    elif col.endswith("No certificate, diploma or degree"):
        candidate_cols.append(col)

    elif col.endswith("Postsecondary certificate, diploma or degree"):
        candidate_cols.append(col)

    elif col.endswith("Bachelor's degree"):
        candidate_cols.append(col)

    elif col.endswith("Master's degree"):
        candidate_cols.append(col)

    elif "Rate of core housing need" in col:
        candidate_cols.append(col)

    elif "Prevalence of low income based on the Low-income measure" in col:
        candidate_cols.append(col)

print("Number found:", len(candidate_cols))

for c in candidate_cols:
    print(c)

Number found: 14
Population | Population and dwellings | Population, 2016
Income | Income of individuals in 2015 |   Government transfers (%)
Income | Income of households in 2015 |   Median total income of households in 2015 ($)
Income | Income of households in 2015 |   Median after-tax income of households in 2015 ($)
Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)
Education | Highest certificate, diploma or degree |       Master's degree
Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree
Housing | Core housing need | Rate of core housing need
Education | Highest certificate, diploma or degree |   No certificate, diploma or degree
Education | Highest certificate, diploma or degree |       Bachelor's degree
Education | Location of study compared with province or territory of residence with countries outside Canada |   Postsecondary certificate, diploma or degree
Labour | Labour force status | Employment rate
Labour | Labour force status | Employment rate (Males)
Labour | Labour force status | Employment rate (Females)

In [38]:
analysis_df = df[["Unnamed: 0",

    "Population | Population and dwellings | Population, 2016",

    "Income | Income of households in 2015 |   Median total income of households in 2015 ($)",

    "Income | Income of households in 2015 |   Median after-tax income of households in 2015 ($)",

    "Income | Income of individuals in 2015 |   Government transfers (%)",

    "Labour | Labour force status | Employment rate",

    "Labour | Labour force status | Employment rate (Males)",

    "Labour | Labour force status | Employment rate (Females)",

    "Education | Highest certificate, diploma or degree |   No certificate, diploma or degree",

    "Education | Highest certificate, diploma or degree |   Postsecondary certificate, diploma or degree",

    "Education | Highest certificate, diploma or degree |       Bachelor's degree",

    "Education | Highest certificate, diploma or degree |       Master's degree",

    "Housing | Core housing need | Rate of core housing need",

    "Income | Low income in 2015 | Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)"]]

print(analysis_df.shape)

(143, 14)

In [39]:
analysis_df.columns = ["Neighbourhood",
    "Population_2016",
    "Median_Income",
    "Median_AfterTax_Income",
    "Government_Transfers_Pct",
    "Employment_Rate",
    "Employment_Rate_Male",
    "Employment_Rate_Female",
    "No_Degree_Pct",
    "Postsecondary_Pct",
    "Bachelors_Pct",
    "Masters_Pct",
    "Core_Housing_Need_Pct",
    "Low_Income_Pct"]

analysis_df.head()

,Neighbourhood,Population_2016,Median_Income,Median_AfterTax_Income,Government_Transfers_Pct,Employment_Rate,Employment_Rate_Male,Employment_Rate_Female,No_Degree_Pct,Postsecondary_Pct,Bachelors_Pct,Masters_Pct,Core_Housing_Need_Pct,Low_Income_Pct
0,City of Toronto,2731571.0,65829.0,58264.0,9.4,59.3,63.8,55.2,377340.0,1356360.0,534610.0,192120.0,23.3,20.2
1,Agincourt North,29113.0,NaN,NaN,NaN,50.0,54.5,46.0,6550.0,10985.0,4380.0,890.0,NaN,21.3
2,Agincourt South-Malvern West,23757.0,NaN,NaN,NaN,53.2,58.2,48.7,4035.0,10285.0,4210.0,1020.0,NaN,22.6
3,Alderwood,12054.0,NaN,NaN,NaN,62.4,67.1,57.9,2005.0,5300.0,1660.0,430.0,NaN,8.2
4,Annex,30526.0,NaN,NaN,NaN,65.8,68.9,63.1,1585.0,20430.0,9135.0,4795.0,NaN,18.3

In [40]:
analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Neighbourhood             143 non-null    object
 1   Population_2016           141 non-null    float64
 2   Median_Income             1 non-null      float64
 3   Median_AfterTax_Income    1 non-null      float64
 4   Government_Transfers_Pct  1 non-null      float64
 5   Employment_Rate           141 non-null    float64
 6   Employment_Rate_Male      141 non-null    float64
 7   Employment_Rate_Female    141 non-null    float64
 8   No_Degree_Pct             141 non-null    float64
 9   Postsecondary_Pct         141 non-null    float64
 10  Bachelors_Pct             141 non-null    float64
 11  Masters_Pct               141 non-null    float64
 12  Core_Housing_Need_Pct     1 non-null      float64
 13  Low_Income_Pct            141 non-null    float64
dtypes: float64(13), object(1)
memory usage: 15.8+ KB

In [41]:
analysis_df.isnull().sum()

Neighbourhood                 0
Population_2016               2
Median_Income               142
Median_AfterTax_Income      142
Government_Transfers_Pct    142
Employment_Rate               2
Employment_Rate_Male          2
Employment_Rate_Female        2
No_Degree_Pct                 2
Postsecondary_Pct             2
Bachelors_Pct                 2
Masters_Pct                   2
Core_Housing_Need_Pct       142
Low_Income_Pct                2
dtype: int64

In [42]:
analysis_df[
[
    "Neighbourhood",
    "Median_Income",
    "Median_AfterTax_Income",
    "Government_Transfers_Pct",
    "Core_Housing_Need_Pct"
]
].head(10)

,Neighbourhood,Median_Income,Median_AfterTax_Income,Government_Transfers_Pct,Core_Housing_Need_Pct
0,City of Toronto,65829.0,58264.0,9.4,23.3
1,Agincourt North,NaN,NaN,NaN,NaN
2,Agincourt South-Malvern West,NaN,NaN,NaN,NaN
3,Alderwood,NaN,NaN,NaN,NaN
4,Annex,NaN,NaN,NaN,NaN
5,Banbury-Don Mills,NaN,NaN,NaN,NaN
6,Bathurst Manor,NaN,NaN,NaN,NaN
7,Bay Street Corridor,NaN,NaN,NaN,NaN
8,Bayview Village,NaN,NaN,NaN,NaN
9,Bayview Woods-Steeles,NaN,NaN,NaN,NaN

In [43]:
for col in df.columns:
    if "Median total income of households in 2015" in col:
        print(col)

Income | Income of households in 2015 |   Median total income of households in 2015 ($)

In [44]:
df[[
    "Unnamed: 0",
    [c for c in df.columns if "Median total income of households in 2015" in c][0]]
].head(10)

,Unnamed: 0,Income | Income of households in 2015 | Median total income of households in 2015 ($)
0,City of Toronto,65829.0
1,Agincourt North,NaN
2,Agincourt South-Malvern West,NaN
3,Alderwood,NaN
4,Annex,NaN
5,Banbury-Don Mills,NaN
6,Bathurst Manor,NaN
7,Bay Street Corridor,NaN
8,Bayview Village,NaN
9,Bayview Woods-Steeles,NaN

In [45]:
analysis_df.head(10)

,Neighbourhood,Population_2016,Median_Income,Median_AfterTax_Income,Government_Transfers_Pct,Employment_Rate,Employment_Rate_Male,Employment_Rate_Female,No_Degree_Pct,Postsecondary_Pct,Bachelors_Pct,Masters_Pct,Core_Housing_Need_Pct,Low_Income_Pct
0,City of Toronto,2731571.0,65829.0,58264.0,9.4,59.3,63.8,55.2,377340.0,1356360.0,534610.0,192120.0,23.3,20.2
1,Agincourt North,29113.0,NaN,NaN,NaN,50.0,54.5,46.0,6550.0,10985.0,4380.0,890.0,NaN,21.3
2,Agincourt South-Malvern West,23757.0,NaN,NaN,NaN,53.2,58.2,48.7,4035.0,10285.0,4210.0,1020.0,NaN,22.6
3,Alderwood,12054.0,NaN,NaN,NaN,62.4,67.1,57.9,2005.0,5300.0,1660.0,430.0,NaN,8.2
4,Annex,30526.0,NaN,NaN,NaN,65.8,68.9,63.1,1585.0,20430.0,9135.0,4795.0,NaN,18.3
5,Banbury-Don Mills,27695.0,NaN,NaN,NaN,55.6,62.0,50.2,2295.0,15950.0,6500.0,2575.0,NaN,13.7
6,Bathurst Manor,15873.0,NaN,NaN,NaN,60.3,64.6,56.4,1665.0,8200.0,3075.0,1055.0,NaN,17.0
7,Bay Street Corridor,25797.0,NaN,NaN,NaN,56.2,61.2,51.7,700.0,17505.0,8370.0,3810.0,NaN,37.7
8,Bayview Village,21396.0,NaN,NaN,NaN,58.5,63.7,54.0,1310.0,13740.0,6055.0,2360.0,NaN,23.7
9,Bayview Woods-Steeles,13154.0,NaN,NaN,NaN,51.3,56.6,46.8,1295.0,7470.0,3060.0,1140.0,NaN,18.4

In [46]:
for col in df.columns:
    if "Median total income of households in 2015" in col:
        print(col)

Income | Income of households in 2015 |   Median total income of households in 2015 ($)

In [48]:
for col in df.columns:
    if "Core housing need" in col:
        print(repr(col))

'Housing | Core housing need | Occupied private dwellings'
'Housing | Core housing need | Rate of core housing need'
'Housing | Core housing need | Number of households in core housing need'
'Housing | Core housing need | Core housing need, Unsuitable only'
'Housing | Core housing need | Core housing need, Inadequate only'
'Housing | Core housing need | Core housing need, Unaffordable only'
'Housing | Core housing need | Core housing need, two or more dimensions'
'Housing | Core housing need | Rate of unaffordable housing'
'Housing | Core housing need | Unaffordable housing not in core need'
'Housing | Core housing need | Unaffordable housing in core need'
'Housing | Core housing need | Unaffordable housing not applicable for core need'
'Housing | Core housing need | Rate of unaffordable housing, owner-households'
'Housing | Core housing need | Rate of unaffordable housing, renter-households'
'Housing | Core housing need | Rate of inadequate housing'
'Housing | Core housing need | Inadequate housing not in core need'
'Housing | Core housing need | Inadequate housing in core need'
'Housing | Core housing need | Inadequate housing not applicable for core need'
'Housing | Core housing need | Rate of unsuitable housing'
'Housing | Core housing need | Unsuitable housing not in core need'
'Housing | Core housing need | Unsuitable housing in core need'
'Housing | Core housing need | Unsuitable housing not applicable for core need'

In [49]:
for col in df.columns:
    if "Government transfers (%)" in col:
        print(repr(col))

'Income | Income of individuals in 2015 |   Government transfers (%)'

In [50]:
df[[
    "Unnamed: 0",
    "Income | Income of households in 2015 |   Median total income of households in 2015 ($)"]
].head(10)

,Unnamed: 0,Income | Income of households in 2015 | Median total income of households in 2015 ($)
0,City of Toronto,65829.0
1,Agincourt North,NaN
2,Agincourt South-Malvern West,NaN
3,Alderwood,NaN
4,Annex,NaN
5,Banbury-Don Mills,NaN
6,Bathurst Manor,NaN
7,Bay Street Corridor,NaN
8,Bayview Village,NaN
9,Bayview Woods-Steeles,NaN

In [51]:
df[[
    "Unnamed: 0",
    "Income | Income of households in 2015 |   Median after-tax income of households in 2015 ($)"]
].head(10)

,Unnamed: 0,Income | Income of households in 2015 | Median after-tax income of households in 2015 ($)
0,City of Toronto,58264.0
1,Agincourt North,NaN
2,Agincourt South-Malvern West,NaN
3,Alderwood,NaN
4,Annex,NaN
5,Banbury-Don Mills,NaN
6,Bathurst Manor,NaN
7,Bay Street Corridor,NaN
8,Bayview Village,NaN
9,Bayview Woods-Steeles,NaN

In [52]:
df[[
    "Unnamed: 0",
    "Income | Income of individuals in 2015 |   Government transfers (%)"]
].head(10)

,Unnamed: 0,Income | Income of individuals in 2015 | Government transfers (%)
0,City of Toronto,9.4
1,Agincourt North,NaN
2,Agincourt South-Malvern West,NaN
3,Alderwood,NaN
4,Annex,NaN
5,Banbury-Don Mills,NaN
6,Bathurst Manor,NaN
7,Bay Street Corridor,NaN
8,Bayview Village,NaN
9,Bayview Woods-Steeles,NaN

In [53]:
df[[
    "Unnamed: 0",
    "Housing | Core housing need | Rate of core housing need"]
].head(10)

,Unnamed: 0,Housing | Core housing need | Rate of core housing need
0,City of Toronto,23.3
1,Agincourt North,NaN
2,Agincourt South-Malvern West,NaN
3,Alderwood,NaN
4,Annex,NaN
5,Banbury-Don Mills,NaN
6,Bathurst Manor,NaN
7,Bay Street Corridor,NaN
8,Bayview Village,NaN
9,Bayview Woods-Steeles,NaN